#!/bin/sh
# Install the Antumbra kernel modules (the kernel Image itself goes into the
# boot image, not the root filesystem).
set -eu
: "${KERNEL_RELEASE:?}"
SRC=/run/antumbra-build/kernel
tar -C /usr --zstd --keep-directory-symlink -xf "${SRC}/modules.tar.zst"
depmod -a "${KERNEL_RELEASE}"
install -m 0644 "${SRC}/config" "/boot/config-${KERNEL_RELEASE}"
mkdir -p /etc/antumbra
install -m 0644 "${SRC}/live-fs-uuid" /etc/antumbra/live-fs-uuid
printf '%s\n' "${KERNEL_RELEASE}" > /etc/antumbra/kernel-release
# The initramfs itself is generated by 80-base-initramfs.sh, once every
# modprobe.d blocklist that must be carried into it is in place.
