#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# Android apps (Waydroid), only in images built with ANTUMBRA_ANDROID=1;
# docs/architecture.md, "Android apps". At run time they stay off until the
# user turns them on at the Welcome screen, for one session.
#
# Here: the pinned images where "waydroid init" finds them preinstalled (so
# it never downloads), F-Droid, LXC's own bridge and services masked,
# Waydroid's container service kept from starting at boot, Waydroid's LXC
# templates moved to the Tor-only bridge and hardened, Waydroid patched to
# keep cameras out, pkexec without its setuid bit, Tor's listeners for
# Android, and the "Android" Persistent Storage feature. Every change is
# checked; a template or package that no longer matches fails the build.
set -eu
if [ "${ANTUMBRA_ANDROID:-}" != "1" ]; then
    echo "no Android apps in this image (ANTUMBRA_ANDROID is not 1)"
    exit 0
fi
SRC=/run/antumbra-build/android
IMAGES=/usr/share/waydroid-extra/images
ANDROID_DIR=/usr/share/antumbra/android
CONFIGS=/usr/lib/waydroid/data/configs
die() { echo "56-session-android: $*" >&2; exit 1; }

# --- The images (copied in by build/rootfs.sh) and F-Droid ---------------------------
( cd "${IMAGES}" && sha256sum --check --quiet "${SRC}/images.sha256" ) || die "Waydroid images missing or not the fetched ones"
chown root:root "${IMAGES}/system.img" "${IMAGES}/vendor.img"
chmod 0644 "${IMAGES}/system.img" "${IMAGES}/vendor.img"
printf '%s  %s\n' "$(cat "${SRC}/F-Droid.apk.sha256")" "${SRC}/F-Droid.apk" | sha256sum --check --quiet || die "F-Droid.apk is not the pinned one"
install -m 0644 "${SRC}/F-Droid.apk" "${ANDROID_DIR}/F-Droid.apk"
# The identity Android reports instead of the phone's device-tree model:
# the Waydroid image's own build values, as on any host without a device
# tree. antumbra-waydroid writes them into waydroid.cfg.
case "$(cat "${SRC}/variant")" in
    arm64) model="WayDroid arm64 Device"; device=waydroid_arm64 ;;
    arm64_only) model="WayDroid arm64 only Device"; device=waydroid_arm64_only ;;
    *) die "unknown Waydroid image variant $(cat "${SRC}/variant")" ;;
esac
cat > "${ANDROID_DIR}/product.prop" <<EOF
# Generated by config/hooks/56-session-android.sh: the Waydroid image's own
# product values (android_device_waydroid_waydroid, lineage_${device}.mk).
ro.product.waydroid.brand=waydroid
ro.product.waydroid.manufacturer=Waydroid
ro.product.waydroid.model=${model}
ro.product.waydroid.device=${device}
ro.product.waydroid.name=lineage_${device}
EOF
# Debian's postinst ran "waydroid upgrade -o", which only created a log;
# Waydroid's state is created at run time, in the RAM overlay.
rm -rf /var/lib/waydroid

# --- LXC's own bridge and services: never ---------------------------------------------
# Debian's lxc enables lxc-net (lxcbr0 with NAT, DHCP and DNS, ip_forward),
# lxc (autostart) and lxc-monitord. A mask in /etc wins over the package's
# re-enabling on upgrade.
systemctl mask lxc-net.service lxc.service lxc-monitord.service
sed -i 's/^USE_LXC_BRIDGE=.*/USE_LXC_BRIDGE="false"/' /etc/default/lxc-net
grep -qx 'USE_LXC_BRIDGE="false"' /etc/default/lxc-net || die "/etc/default/lxc-net still enables lxcbr0"

# --- Waydroid's container service: not at boot ------------------------------------------
# debhelper enabled it (WantedBy=multi-user.target). The drop-in in /etc
# makes it, and D-Bus activation of it, depend on the Welcome screen's
# choice; antumbra-waydroid.service starts it.
systemctl disable waydroid-container.service
[ ! -e /etc/systemd/system/multi-user.target.wants/waydroid-container.service ] || die "waydroid-container.service is still enabled"
[ -f /etc/systemd/system/waydroid-container.service.d/antumbra.conf ] || die "the waydroid-container drop-in is missing"
# The user's session starts Android, keeps the app grid's Android folder.
systemctl --global enable antumbra-android-session.path antumbra-android-folder.path antumbra-android-folder.service

# --- Waydroid's LXC templates -------------------------------------------------------------
# Waydroid regenerates the container's configuration from these on every
# "init" and "upgrade". The start-host hook re-checks the result at every
# container start.
# 1. The Tor-only bridge instead of waydroid0. Waydroid's own network script
#    (waydroid-net.sh: NAT, ip_forward, a DNS-serving dnsmasq) then bails out.
sed -i 's/^\(lxc\.net\.0\.link\|lxc\.network\.link\) = waydroid0$/\1 = waydroid-tor/' "${CONFIGS}/config_1" "${CONFIGS}/config_3"
grep -qx 'lxc.net.0.link = waydroid-tor' "${CONFIGS}/config_3" || die "config_3: link not moved to waydroid-tor"
grep -qx 'lxc.network.link = waydroid-tor' "${CONFIGS}/config_1" || die "config_1: link not moved to waydroid-tor"
! grep -q waydroid0 "${CONFIGS}/config_1" "${CONFIGS}/config_3" || die "a template still names waydroid0"
grep -qx 'lxc.net.0.hwaddr = 00:16:3e:f9:d3:03' "${CONFIGS}/config_3" || die "config_3: the container MAC address changed (antumbra-waydroid-dhcp.service reserves it)"
# 2. No sys_time. Waydroid's seccomp profile already turns the set-time calls
#    into no-ops; this is defence in depth.
sed -i '/^lxc\.cap\.keep/ s/ sys_time\b//g' "${CONFIGS}/config_base"
grep -q '^lxc\.cap\.keep = .*sys_admin' "${CONFIGS}/config_base" || die "config_base: lxc.cap.keep not found"
! grep '^lxc\.cap\.keep' "${CONFIGS}/config_base" | grep -qw sys_time || die "config_base: sys_time still kept"
# 3. The start-host hook (fails closed), no V4L2 devices, and no device tree:
#    the container mounts the host's sysfs, where /sys/firmware/devicetree
#    (and /proc/device-tree) would tell apps the phone's model. Without
#    "optional", a failed mount aborts the container start.
cat >> "${CONFIGS}/config_3" <<'EOF'

# Antumbra (config/hooks/56-session-android.sh): start only on the Tor-only
# network; no camera devices; no device tree.
lxc.hook.start-host = /usr/local/lib/antumbra-waydroid-start-host
lxc.cgroup2.devices.deny = c 81:* rwm
lxc.mount.entry = tmpfs sys/firmware tmpfs ro,nosuid,nodev,noexec,mode=0555,size=4k 0 0
EOF
[ "$(grep -c '^lxc.hook.start-host = /usr/local/lib/antumbra-waydroid-start-host$' "${CONFIGS}/config_3")" = "1" ] || die "config_3: start-host hook not set once"
[ -x /usr/local/lib/antumbra-waydroid-start-host ] || die "the start-host hook is missing"

# --- Waydroid itself: no camera devices --------------------------------------------------
PATCH=/usr/share/antumbra/patches/waydroid-no-video.diff
patch -p1 -d / --dry-run -s -N < "${PATCH}" >/dev/null || die "$(basename "${PATCH}") does not apply to this waydroid package"
patch -p1 -d / -s -N < "${PATCH}"
! grep -q 'glob("/dev/video' /usr/lib/waydroid/tools/actions/container_manager.py /usr/lib/waydroid/tools/helpers/lxc.py || die "Waydroid still passes /dev/video* on"

# --- pkexec: a Waydroid dependency it never calls (1.6.3 asks polkitd over D-Bus) ----------
if ! dpkg-statoverride --list /usr/bin/pkexec >/dev/null; then
    dpkg-statoverride --update --add root root 0755 /usr/bin/pkexec
fi
[ "$(stat -c %a /usr/bin/pkexec)" = "755" ] || die "pkexec is still setuid"

# --- AppArmor: Waydroid's container profile must parse -----------------------------------
# It lives in a subdirectory, which hook 48 does not check; antumbra-waydroid
# loads it at run time (complain mode, as Debian ships it).
apparmor_parser -Q -K /etc/apparmor.d/lxc/lxc-waydroid >/dev/null || die "the lxc-waydroid AppArmor profile does not parse"

# --- Tor's listeners for Android -------------------------------------------------------------
! grep -q '^TransPort 10\.200\.2\.1:' /etc/tor/torrc || die "/etc/tor/torrc already has the Android TransPort"
cat "${ANDROID_DIR}/torrc" >> /etc/tor/torrc
grep -q '^TransPort 10\.200\.2\.1:9041 ' /etc/tor/torrc || die "Tor's Android TransPort not configured"
grep -qx 'DNSPort 10.200.2.1:5354' /etc/tor/torrc || die "Tor's Android DNSPort not configured"

# --- The "Android" Persistent Storage feature (off by default) ------------------------------
printf 'android|waydroid|/home/amnesia/.local/share/waydroid|amnesia:amnesia|0700|off\n' >> /etc/antumbra/persistence-features.conf

echo "Android apps: Waydroid $(dpkg-query -W -f '${Version}' waydroid), $(cat "${SRC}/variant") images, F-Droid"
