#!/bin/sh
# The user's session, started by greetd on the Welcome screen's request.
# phosh-session does not export the session variables itself.
set -eu
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=Phosh:GNOME
export XDG_SESSION_DESKTOP=phosh
export GDMSESSION=phosh
# shellcheck source=antumbra-session-env
. /usr/libexec/antumbra-session-env
exec /usr/bin/phosh-session
