#!/bin/sh
# Tails' hooks/shutdown: ship systemd-shutdown and the pre-shutdown hook in the
# initramfs, so systemd can return to it at shutdown and unmount everything
# before the memory is released (docs: tails.net memory_erasure design).
PREREQ=""
prereqs() { echo "${PREREQ}"; }
case "${1:-}" in prereqs) prereqs; exit 0 ;; esac
. /usr/share/initramfs-tools/hook-functions
copy_exec /lib/systemd/systemd-shutdown /shutdown
mkdir -p "${DESTDIR}/lib/systemd/system-shutdown"
copy_file "regular file" /usr/local/lib/initramfs-pre-shutdown-hook /lib/systemd/system-shutdown/antumbra
copy_exec /bin/mount /usr/bin
copy_exec /bin/umount /usr/bin
copy_exec /sbin/losetup /sbin
copy_exec /sbin/veritysetup /sbin
copy_exec /sbin/dmsetup /sbin
touch "${DESTDIR}/etc/initrd-release"
exit 0
