import { LifeEventTemplate } from '../types';
import { E, application, care, career, celebration, emergency, enrollment, finance, homeProject, legal, lossRecovery, medical, purchase } from './builder';

/** Extended important-events catalog — compact, archetype-based events. */

/** 5th, 10th, 15th… anniversaries count as milestones. */
function milestoneAnniversaryYear(answers: Record<string, string | boolean>): boolean {
  const year = parseInt(String(answers['anniversary_year'] ?? '').replace(/\D/g, ''), 10);
  return year > 0 && year % 5 === 0;
}

export const weddingAnniversary: LifeEventTemplate = E({
  id: 'wedding-anniversary',
  name: 'Our wedding anniversary',
  emoji: '💞',
  category: 'important',
  summary:
    'Plan the anniversary properly — and if it\'s a 5th, 10th, 25th… year, this becomes a milestone plan worth the extra effort.',
  pack: celebration('the anniversary'),
  phrases: ['wedding anniversary', 'marriage anniversary', 'our anniversary', 'anniversary coming up', 'planned my marriage anniversary', 'planning our anniversary'],
  keywords: ['anniversary', 'anniversaries'],
  questions: [
    { id: 'event_date', prompt: 'When is the anniversary?', kind: 'date' },
    { id: 'anniversary_year', prompt: 'Which anniversary is it? (year number, e.g. 5)', kind: 'text' },
  ],
  isMilestone: milestoneAnniversaryYear,
});

export const extraImportant: LifeEventTemplate[] = [
  weddingAnniversary,
  E({ id: 'promotion', name: 'I got promoted', emoji: '📊', category: 'important', pack: career('the promotion'),
    phrases: ['i got promoted', 'got a promotion', 'i was promoted', 'getting promoted'], keywords: ['promoted', 'promotion', 'raise'] }),
  E({ id: 'career-change', name: "I'm changing careers", emoji: '🔄', category: 'important', pack: career('the career change'),
    phrases: ['changing careers', 'career change', 'switching fields', 'new career'], keywords: ['career', 'retraining', 'pivot'] }),
  E({ id: 'remote-work', name: "I'm switching to remote work", emoji: '💻', category: 'important', pack: career('the switch to remote work'),
    phrases: ['working remotely', 'switching to remote', 'going remote', 'work from home now'], keywords: ['remote', 'wfh', 'telecommute'] }),
  E({ id: 'return-to-office', name: "I'm returning to the office", emoji: '🏢', category: 'important', pack: career('the return to office'),
    phrases: ['returning to the office', 'back to the office', 'return to office'], keywords: ['office', 'commute', 'rto'] }),
  E({ id: 'workplace-injury', name: 'I was injured at work', emoji: '🤕', category: 'important', pack: legal('the workplace injury'),
    phrases: ['injured at work', 'workplace injury', 'hurt on the job', 'work accident'], keywords: ['injury', 'injured', 'compensation'] }),
  E({ id: 'parental-leave', name: "I'm going on parental leave", emoji: '🍼', category: 'important', pack: application('parental leave and benefits', 'Employer + benefits agency'),
    phrases: ['going on parental leave', 'maternity leave', 'paternity leave', 'taking parental leave'], keywords: ['leave', 'maternity', 'paternity'] }),
  E({ id: 'return-from-leave', name: "I'm returning from parental leave", emoji: '👔', category: 'important', pack: career('the return from leave'),
    phrases: ['returning from parental leave', 'back from maternity leave', 'returning to work after baby'], keywords: ['returning', 'childcare'] }),
  E({ id: 'started-freelancing', name: 'I started freelancing', emoji: '🧑‍💻', category: 'important', pack: career('the move to freelancing'),
    phrases: ['started freelancing', 'going freelance', 'becoming a freelancer', 'freelancing full time'], keywords: ['freelance', 'freelancer', 'contractor', 'gig'] }),
  E({ id: 'side-gig-taxes', name: 'I started a side gig', emoji: '💡', category: 'important', pack: finance('the side gig money and taxes'),
    phrases: ['started a side gig', 'side hustle', 'earning on the side'], keywords: ['side', 'hustle', 'gig', 'etsy', 'uber'] }),
  E({ id: 'tax-season', name: "It's tax season", emoji: '🧾', category: 'important', pack: finance('this year\'s tax filing'),
    phrases: ['tax season', 'filing my taxes', 'doing my taxes', 'tax return due'], keywords: ['tax', 'taxes', 'filing', 'deduction', 'refund'] }),
  E({ id: 'tax-audit', name: "I'm being audited", emoji: '🔍', category: 'important', pack: legal('the tax audit'),
    phrases: ['being audited', 'tax audit', 'audit letter from the irs', 'cra audit'], keywords: ['audit', 'audited', 'auditor'] }),
  E({ id: 'first-tax-return', name: "I'm filing taxes for the first time", emoji: '🧾', category: 'important', pack: finance('your first tax return'),
    phrases: ['filing taxes for the first time', 'first tax return', 'never filed taxes before'], keywords: ['w2', 't4', 'deadline'] }),
  E({ id: 'mortgage-application', name: "I'm applying for a mortgage", emoji: '🏦', category: 'important', pack: application('the mortgage', 'Lender'),
    phrases: ['applying for a mortgage', 'mortgage application', 'getting pre-approved', 'mortgage preapproval'], keywords: ['mortgage', 'preapproval', 'lender', 'downpayment'] }),
  E({ id: 'mortgage-refinance', name: "I'm refinancing the mortgage", emoji: '📉', category: 'important', pack: finance('the refinance'),
    phrases: ['refinancing the mortgage', 'refinance my mortgage', 'remortgaging'], keywords: ['refinance', 'refinancing', 'remortgage', 'rate'] }),
  E({ id: 'lease-renewal', name: 'My lease is up for renewal', emoji: '📋', category: 'important', pack: legal('the lease renewal'),
    phrases: ['lease is up for renewal', 'renewing my lease', 'lease renewal', 'lease expiring'], keywords: ['lease', 'renewal', 'landlord', 'tenancy'] }),
  E({ id: 'rent-increase', name: 'My rent is being increased', emoji: '📈', category: 'important', pack: legal('the rent increase'),
    phrases: ['rent increase', 'rent is going up', 'landlord raising the rent'], keywords: ['rent', 'increase', 'tenant'] }),
  E({ id: 'eviction-notice', name: 'I received an eviction notice', emoji: '⚠️', category: 'important', pack: legal('the eviction notice'),
    phrases: ['eviction notice', 'being evicted', 'notice to vacate'], keywords: ['eviction', 'evicted', 'vacate'] }),
  E({ id: 'sold-house', name: "I'm selling my house", emoji: '🏷️', category: 'important', pack: legal('the house sale'),
    phrases: ['selling my house', 'selling our home', 'putting the house on the market', 'i sold my house'], keywords: ['selling', 'sale', 'realtor', 'listing'] }),
  E({ id: 'sold-car', name: "I'm selling my car", emoji: '🚙', category: 'important', pack: finance('the car sale'),
    phrases: ['selling my car', 'i sold my car', 'selling the car'], keywords: ['selling', 'sale'] }),
  E({ id: 'car-accident', name: 'I was in a car accident', emoji: '💥', category: 'important', pack: emergency('the accident'),
    phrases: ['car accident', 'car crash', 'i was in an accident', 'fender bender'], keywords: ['accident', 'crash', 'collision', 'whiplash'] }),
  E({ id: 'car-stolen', name: 'My car was stolen', emoji: '🚨', category: 'important', pack: lossRecovery('the stolen car'),
    phrases: ['my car was stolen', 'car got stolen', 'vehicle theft'], keywords: ['stolen', 'theft'] }),
  E({ id: 'house-fire', name: 'We had a house fire', emoji: '🔥', category: 'important', pack: emergency('the fire'),
    phrases: ['house fire', 'fire at home', 'fire damage'], keywords: ['fire', 'smoke', 'damage'] }),
  E({ id: 'flood-damage', name: 'We have flood/water damage', emoji: '🌊', category: 'important', pack: emergency('the water damage'),
    phrases: ['flood damage', 'water damage', 'basement flooded', 'burst pipe'], keywords: ['flood', 'flooded', 'leak', 'water'] }),
  E({ id: 'burglary', name: 'We were burgled', emoji: '🚪', category: 'important', pack: emergency('the break-in'),
    phrases: ['we were burgled', 'house was broken into', 'we got robbed', 'break in at home'], keywords: ['burglary', 'burgled', 'robbed', 'break-in'] }),
  E({ id: 'identity-theft', name: 'My identity was stolen', emoji: '🪪', category: 'important', pack: lossRecovery('the identity theft'),
    phrases: ['identity theft', 'identity was stolen', 'someone opened accounts in my name', 'my identity got stolen'], keywords: ['identity', 'fraud', 'phishing', 'scammed'] }),
  E({ id: 'lost-wallet', name: 'I lost my wallet', emoji: '👛', category: 'important', pack: lossRecovery('the lost wallet'),
    phrases: ['lost my wallet', 'wallet was stolen', 'lost my purse'], keywords: ['wallet', 'purse', 'cards'] }),
  E({ id: 'lost-passport', name: 'I lost my passport', emoji: '🛂', category: 'important', pack: lossRecovery('the lost passport'),
    phrases: ['lost my passport', 'passport was stolen', 'missing passport'], keywords: ['passport'] }),
  E({ id: 'lost-phone', name: 'I lost my phone', emoji: '📱', category: 'important', pack: lossRecovery('the lost phone'),
    phrases: ['lost my phone', 'phone was stolen', 'my phone got stolen'], keywords: ['phone', 'iphone', 'android', 'sim'] }),
  E({ id: 'switching-banks', name: "I'm switching banks", emoji: '🏦', category: 'important', pack: finance('the bank switch'),
    phrases: ['switching banks', 'changing banks', 'moving my accounts to a new bank'], keywords: ['bank', 'banking', 'account'] }),
  E({ id: 'debt-consolidation', name: "I'm consolidating my debt", emoji: '📊', category: 'important', pack: finance('the debt consolidation'),
    phrases: ['consolidating my debt', 'debt consolidation', 'consolidate my loans'], keywords: ['consolidation', 'consolidate', 'refinance'] }),
  E({ id: 'bankruptcy', name: "I'm considering bankruptcy", emoji: '⚖️', category: 'important', pack: legal('the insolvency process'),
    phrases: ['considering bankruptcy', 'filing for bankruptcy', 'declaring bankruptcy', 'insolvency'], keywords: ['bankruptcy', 'bankrupt', 'insolvency', 'creditors'] }),
  E({ id: 'starting-investing', name: "I'm starting to invest", emoji: '📈', category: 'important', pack: finance('your first investments'),
    phrases: ['starting to invest', 'start investing', 'opening a brokerage account', 'buying stocks for the first time'], keywords: ['invest', 'investing', 'stocks', 'etf', 'brokerage'] }),
  E({ id: 'retirement-account', name: "I'm opening a retirement account", emoji: '🏦', category: 'important', pack: finance('the retirement account'),
    phrases: ['opening a retirement account', 'opening an ira', 'starting a 401k', 'setting up my pension'], keywords: ['ira', '401k', 'rrsp', 'pension'] }),
  E({ id: 'college-fund', name: "I'm starting a college fund", emoji: '🎓', category: 'important', pack: finance('the education fund'),
    phrases: ['starting a college fund', 'education savings', '529 plan', 'resp'], keywords: ['529', 'fund', 'savings'] }),
  E({ id: 'cosigning-loan', name: "I'm co-signing a loan", emoji: '🖊️', category: 'important', pack: legal('the co-signing decision'),
    phrases: ['cosigning a loan', 'co-signing', 'asked to cosign'], keywords: ['cosign', 'cosigner', 'guarantor'] }),
  E({ id: 'open-enrollment', name: "It's insurance open enrollment", emoji: '🗓️', category: 'important', pack: finance('this year\'s benefits elections'),
    phrases: ['open enrollment', 'benefits enrollment period', 'choosing my benefits'], keywords: ['enrollment', 'benefits', 'premiums'] }),
  E({ id: 'switching-health-insurance', name: "I'm switching health insurance", emoji: '🏥', category: 'important', pack: finance('the insurance switch'),
    phrases: ['switching health insurance', 'changing health plans', 'new health insurance'], keywords: ['insurance', 'coverage', 'deductible'] }),
  E({ id: 'medicare-enrollment', name: "I'm enrolling in Medicare", emoji: '🏥', category: 'important', pack: application('Medicare enrollment', 'Medicare'),
    phrases: ['enrolling in medicare', 'medicare enrollment', 'signing up for medicare'], keywords: ['medicare', 'medigap'] }),
  E({ id: 'disability-application', name: "I'm applying for disability benefits", emoji: '♿', category: 'important', pack: application('disability benefits', 'Benefits agency'),
    phrases: ['applying for disability', 'disability benefits', 'disability claim'], keywords: ['disability', 'ssdi', 'benefits'] }),
  E({ id: 'veteran-benefits', name: "I'm claiming veteran benefits", emoji: '🎖️', category: 'important', pack: application('veteran benefits', 'Veterans affairs'),
    phrases: ['claiming veteran benefits', 'va benefits', 'veterans benefits'], keywords: ['va', 'gi'] }),
  E({ id: 'financial-aid', name: "I'm applying for financial aid", emoji: '🎓', category: 'important', pack: application('financial aid', 'Aid office'),
    phrases: ['applying for financial aid', 'fafsa', 'student aid application'], keywords: ['aid', 'grant', 'bursary'] }),
  E({ id: 'scholarship-hunt', name: "I'm applying for scholarships", emoji: '🏅', category: 'important', pack: application('scholarships', 'Scholarship programs'),
    phrases: ['applying for scholarships', 'scholarship applications', 'scholarship hunt'], keywords: ['scholarship', 'scholarships'] }),
  E({ id: 'visa-renewal', name: 'My visa needs renewing', emoji: '🛂', category: 'important', pack: application('the visa renewal', 'Immigration authority'),
    phrases: ['visa needs renewing', 'renewing my visa', 'visa renewal', 'visa expiring'], keywords: ['visa', 'renewal', 'status'] }),
  E({ id: 'work-permit', name: "I'm applying for a work permit", emoji: '🪪', category: 'important', pack: application('the work permit', 'Immigration authority'),
    phrases: ['applying for a work permit', 'work permit application', 'work authorization'], keywords: ['permit', 'authorization', 'sponsor'] }),
  E({ id: 'green-card', name: "I'm applying for a green card", emoji: '🟩', category: 'important', pack: application('the green card', 'USCIS'),
    phrases: ['applying for a green card', 'green card application', 'adjustment of status'], keywords: ['uscis', 'i-485'] }),
  E({ id: 'sponsoring-spouse', name: "I'm sponsoring my spouse's visa", emoji: '💑', category: 'important', pack: application('the spousal sponsorship', 'Immigration authority'),
    phrases: ['sponsoring my spouse', 'spousal sponsorship', 'sponsor my wife', 'sponsor my husband', 'partner visa'],
    keywords: ['sponsorship', 'sponsoring', 'spousal'] }),
  E({ id: 'passport-renewal', name: 'My passport needs renewing', emoji: '📕', category: 'important', pack: application('the passport renewal', 'Passport office'),
    phrases: ['passport needs renewing', 'renewing my passport', 'passport renewal', 'passport expired', 'passport expiring'], keywords: ['renewal', 'expiring'] }),
  E({ id: 'jury-duty', name: 'I was called for jury duty', emoji: '⚖️', category: 'important', pack: legal('jury duty'),
    phrases: ['jury duty', 'jury summons', 'called for jury service'], keywords: ['jury', 'juror', 'summons'] }),
  E({ id: 'court-summons', name: 'I received a court summons', emoji: '📨', category: 'important', pack: legal('the summons'),
    phrases: ['court summons', 'summoned to court', 'being sued', 'court date'], keywords: ['court', 'sued', 'lawsuit', 'hearing'] }),
  E({ id: 'small-claims', name: "I'm filing a small claims case", emoji: '🧑‍⚖️', category: 'important', pack: legal('the small claims case'),
    phrases: ['small claims', 'taking someone to small claims court', 'filing a claim against'], keywords: ['claims', 'dispute'] }),
  E({ id: 'traffic-ticket', name: 'I got a traffic ticket', emoji: '🎫', category: 'important', pack: legal('the ticket'),
    phrases: ['got a traffic ticket', 'speeding ticket', 'parking ticket', 'contesting a ticket'], keywords: ['ticket', 'fine', 'violation', 'speeding'] }),
  E({ id: 'will-creation', name: "I'm making a will", emoji: '📜', category: 'important', pack: legal('your will'),
    phrases: ['making a will', 'writing my will', 'need a will', 'estate planning'], keywords: ['will', 'testament', 'estate', 'heirs'] }),
  E({ id: 'power-of-attorney', name: "I'm setting up power of attorney", emoji: '🖋️', category: 'important', pack: legal('the power of attorney'),
    phrases: ['power of attorney', 'setting up poa', 'healthcare proxy'], keywords: ['attorney', 'poa', 'proxy'] }),
  E({ id: 'trust-setup', name: "I'm setting up a trust", emoji: '🏛️', category: 'important', pack: legal('the trust'),
    phrases: ['setting up a trust', 'creating a trust', 'living trust'], keywords: ['trust', 'trustee'] }),
  E({ id: 'estate-executor', name: "I've been named an executor", emoji: '🗂️', category: 'important', pack: legal('the executor role'),
    phrases: ['named an executor', 'i am the executor', 'executor of the estate'], keywords: ['executor', 'probate'] }),
  E({ id: 'guardianship', name: "I'm becoming a legal guardian", emoji: '🛡️', category: 'important', pack: legal('the guardianship'),
    phrases: ['becoming a legal guardian', 'guardianship', 'custody of my nephew', 'custody of my grandchild'], keywords: ['guardian', 'custody', 'ward'] }),
  E({ id: 'pregnancy', name: "We're expecting a baby", emoji: '🤰', category: 'important', pack: care('the pregnancy'),
    phrases: ['we are expecting', 'i am pregnant', 'we are pregnant', 'expecting a baby', 'due in'], keywords: ['pregnant', 'pregnancy', 'expecting', 'due', 'prenatal'] }),
  E({ id: 'fertility-treatment', name: "We're starting fertility treatment", emoji: '🧬', category: 'important', pack: medical('the fertility treatment'),
    phrases: ['fertility treatment', 'starting ivf', 'ivf journey'], keywords: ['fertility', 'ivf', 'iui'] }),
  E({ id: 'surgery', name: 'I have surgery scheduled', emoji: '🏥', category: 'important', pack: medical('the surgery'),
    phrases: ['surgery scheduled', 'having surgery', 'getting an operation', 'my operation'], keywords: ['surgery', 'operation', 'procedure', 'hospital'] }),
  E({ id: 'chronic-diagnosis', name: 'I received a chronic diagnosis', emoji: '🩺', category: 'important', pack: care('managing the diagnosis'),
    phrases: ['chronic diagnosis', 'diagnosed with diabetes', 'new diagnosis', 'chronic condition'], keywords: ['diagnosis', 'diagnosed', 'chronic', 'condition'] }),
  E({ id: 'starting-therapy', name: "I'm starting therapy", emoji: '🛋️', category: 'important', pack: care('starting therapy'),
    phrases: ['starting therapy', 'finding a therapist', 'looking for a therapist', 'mental health support'], keywords: ['therapy', 'therapist', 'counseling', 'psychologist'] }),
  E({ id: 'elder-care', name: 'My parent needs care', emoji: '🧓', category: 'important', pack: care('your parent\'s care'),
    phrases: ['my parent needs care', 'caring for my mother', 'caring for my father', 'elderly parent', 'aging parents'],
    keywords: ['eldercare', 'caregiver', 'aging', 'elderly'] }),
  E({ id: 'parent-moving-in', name: 'My parent is moving in with us', emoji: '🏠', category: 'important', pack: care('the multigenerational household'),
    phrases: ['parent is moving in', 'mom is moving in with us', 'dad is moving in with us', 'multigenerational'], keywords: ['in-law', 'granny'] }),
  E({ id: 'assisted-living', name: "We're arranging assisted living", emoji: '🏡', category: 'important', pack: care('the move to assisted living'),
    phrases: ['assisted living', 'nursing home', 'care home', 'memory care'], keywords: ['assisted', 'nursing', 'seniors'] }),
  E({ id: 'funeral-prearrangement', name: "I'm pre-arranging my funeral", emoji: '🕯️', category: 'important', pack: legal('the pre-arrangement'),
    phrases: ['prearranging my funeral', 'funeral planning', 'prepaid funeral', 'end of life planning'], keywords: ['funeral', 'burial', 'cremation'] }),
  E({ id: 'life-insurance', name: "I'm buying life insurance", emoji: '☂️', category: 'important', pack: finance('the life insurance purchase'),
    phrases: ['buying life insurance', 'need life insurance', 'life insurance quotes'], keywords: ['life', 'term', 'beneficiary'] }),
  E({ id: 'ltc-insurance', name: "I'm buying long-term care insurance", emoji: '🛏️', category: 'important', pack: finance('the long-term care coverage'),
    phrases: ['long term care insurance', 'ltc insurance'], keywords: ['ltc'] }),
  E({ id: 'daycare-start', name: 'My child is starting daycare', emoji: '🧸', category: 'important', pack: enrollment('daycare'),
    phrases: ['starting daycare', 'daycare waitlist', 'finding childcare', 'nursery place'], keywords: ['daycare', 'childcare', 'nursery', 'preschool'] }),
  E({ id: 'school-start', name: 'My child is starting school', emoji: '🎒', category: 'important', pack: enrollment('school'),
    phrases: ['starting school', 'starting kindergarten', 'first day of school', 'school enrollment'], keywords: ['kindergarten', 'enrollment'] }),
  E({ id: 'child-to-college', name: 'My child is going to college', emoji: '🏫', category: 'important', pack: enrollment('your child\'s college'),
    phrases: ['my child is going to college', 'son is going to college', 'daughter is going to university', 'kid off to college'],
    keywords: ['tuition', 'dorm'] }),
  E({ id: 'teen-driver', name: 'My teen is learning to drive', emoji: '🚦', category: 'important', pack: application('the learner\'s licence', 'Licensing authority'),
    phrases: ['teen is learning to drive', 'learners permit for my son', 'learners permit for my daughter', 'teenage driver'],
    keywords: ['learner', 'permit', 'teen'] }),
  E({ id: 'child-turns-18', name: 'My child is turning 18', emoji: '🎓', category: 'important', pack: legal('your child\'s transition to adulthood'),
    phrases: ['my child is turning 18', 'son turns 18', 'daughter turns 18'], keywords: ['custody', 'majority'] }),
  E({ id: 'hiring-nanny', name: "We're hiring a nanny", emoji: '👶', category: 'important', pack: legal('becoming a household employer'),
    phrases: ['hiring a nanny', 'nanny contract', 'au pair', 'hiring a babysitter regularly'], keywords: ['nanny', 'babysitter', 'household'] }),
  E({ id: 'disaster-prep', name: "I'm preparing for natural disasters", emoji: '🌪️', category: 'important', pack: homeProject('the emergency preparedness setup', false),
    phrases: ['disaster preparedness', 'emergency kit', 'preparing for hurricane season', 'earthquake preparedness'],
    keywords: ['disaster', 'hurricane', 'earthquake', 'wildfire', 'preparedness'] }),
  E({ id: 'solar-panels', name: "We're installing solar panels", emoji: '☀️', category: 'important', pack: homeProject('the solar installation', true),
    phrases: ['installing solar panels', 'going solar', 'solar installation'], keywords: ['solar', 'panels', 'net-metering'] }),
  E({ id: 'ev-purchase', name: "I'm buying an electric car", emoji: '🔌', category: 'important', pack: purchase('the electric car', { register: true, insure: true }),
    phrases: ['buying an electric car', 'buying an ev', 'switching to electric'], keywords: ['ev', 'electric', 'tesla', 'charger'] }),
  E({ id: 'becoming-landlord', name: "I'm becoming a landlord", emoji: '🔑', category: 'important', pack: legal('the rental setup'),
    phrases: ['becoming a landlord', 'renting out my place', 'renting out my apartment', 'first tenant'],
    keywords: ['landlord', 'tenant', 'rental'] }),
  E({ id: 'airbnb-hosting', name: "I'm starting Airbnb hosting", emoji: '🛏️', category: 'important', pack: application('short-term rental hosting', 'Municipality + platform'),
    phrases: ['starting airbnb', 'airbnb hosting', 'short term rental', 'listing on airbnb'], keywords: ['airbnb', 'host', 'str'] }),
  E({ id: 'investment-property', name: "I'm buying an investment property", emoji: '🏢', category: 'important', pack: purchase('the investment property', { insure: true }),
    phrases: ['buying an investment property', 'investment property', 'rental property purchase'], keywords: ['investment', 'rental', 'duplex'] }),
  E({ id: 'vacation-home', name: "We're buying a vacation home", emoji: '🏖️', category: 'important', pack: purchase('the vacation home', { insure: true }),
    phrases: ['buying a vacation home', 'buying a cottage', 'buying a cabin', 'second home'], keywords: ['cottage', 'cabin', 'lakehouse'] }),
  E({ id: 'boat-purchase', name: "I'm buying a boat", emoji: '⛵', category: 'important', pack: purchase('the boat', { register: true, insure: true }),
    phrases: ['buying a boat', 'bought a boat', 'getting a boat'], keywords: ['boat', 'sailboat', 'yacht', 'marina'] }),
  E({ id: 'motorcycle-purchase', name: "I'm buying a motorcycle", emoji: '🏍️', category: 'important', pack: purchase('the motorcycle', { register: true, insure: true }),
    phrases: ['buying a motorcycle', 'bought a motorcycle', 'getting a bike'], keywords: ['motorcycle', 'motorbike'] }),
  E({ id: 'rv-purchase', name: "We're buying an RV", emoji: '🚐', category: 'important', pack: purchase('the RV', { register: true, insure: true }),
    phrases: ['buying an rv', 'buying a camper', 'buying a motorhome'], keywords: ['rv', 'camper', 'motorhome', 'caravan'] }),
  E({ id: 'running-for-office', name: "I'm running for local office", emoji: '🏛️', category: 'important', pack: application('the candidacy', 'Electoral authority'),
    phrases: ['running for office', 'running for city council', 'running for school board', 'local election candidacy'],
    keywords: ['candidacy', 'campaign', 'council'] }),
];
