import { LifeEventTemplate } from '../types';
import { E, application, birthday, care, career, celebration, enrollment, finance, legal, renting, sport, trip } from './builder';

/** Extended milestone catalog — compact, archetype-based events. */
export const extraMilestones: LifeEventTemplate[] = [
  E({ id: 'got-engaged', name: 'We got engaged', emoji: '💍', category: 'milestone', tasks: celebration('the engagement celebration'),
    phrases: ['we got engaged', 'i got engaged', 'got engaged', 'i proposed', 'she said yes', 'he said yes'],
    keywords: ['engaged', 'engagement', 'proposal', 'fiance', 'fiancee'] }),
  E({ id: 'planning-wedding', name: 'We are planning our wedding', emoji: '👰', category: 'milestone', tasks: celebration('the wedding'),
    phrases: ['planning our wedding', 'planning my wedding', 'planning a wedding', 'wedding planning'],
    keywords: ['wedding', 'bride', 'groom', 'venue', 'marry'] }),
  E({ id: 'turned-21', name: 'I turned 21', emoji: '🥂', category: 'milestone',
    tasks: birthday(21, 'Full legal capacity in most places: contracts, credit and accounts fully in your name — review what should now be yours alone.', 'Baseline check-up and an honest look at habits that compound from here.'),
    phrases: ['i turned 21', 'turning 21', 'my 21st birthday'], keywords: ['21', 'twenty-one'] }),
  E({ id: 'turned-25', name: 'I turned 25', emoji: '🎉', category: 'milestone',
    tasks: birthday(25, 'Car insurance rates typically drop at 25 — requote everything; start retirement contributions if you haven\'t.', 'Establish a primary doctor and dentist as an adult, not just when something hurts.'),
    phrases: ['i turned 25', 'turning 25', 'my 25th birthday'], keywords: ['25', 'twenty-five'] }),
  E({ id: 'turned-30', name: 'I turned 30', emoji: '🎂', category: 'milestone',
    tasks: birthday(30, 'Decade check: emergency fund, retirement rate, insurance coverage, and a will if anyone depends on you.', 'Baseline numbers worth tracking from 30: blood pressure, cholesterol, skin check.'),
    phrases: ['i turned 30', 'turning 30', 'i am turning 30', 'my 30th birthday'], keywords: ['30', 'thirty'] }),
  E({ id: 'turned-40', name: 'I turned 40', emoji: '🎂', category: 'milestone',
    tasks: birthday(40, 'Mid-career money audit: retirement trajectory, life/disability insurance, estate documents, aging-parent planning.', 'Screenings start ramping at 40 — eye pressure, diabetes, heart risk; ask what applies to you.'),
    phrases: ['i turned 40', 'turning 40', 'my 40th birthday'], keywords: ['40', 'forty'] }),
  E({ id: 'turned-50', name: 'I turned 50', emoji: '🎂', category: 'milestone',
    tasks: birthday(50, 'Catch-up retirement contribution limits open at 50; get a real projection of your retirement date and income.', 'Colonoscopy and the full screening panel — 50 is when early detection earns its keep.'),
    phrases: ['i turned 50', 'turning 50', 'my 50th birthday'], keywords: ['50', 'fifty'] }),
  E({ id: 'turned-60', name: 'I turned 60', emoji: '🎂', category: 'milestone',
    tasks: birthday(60, 'Pension statements, claiming-age scenarios, and the retirement countdown plan — decisions in the next five years are mostly irreversible.', 'Annual check-ups become non-optional; review medications and bone density.'),
    phrases: ['i turned 60', 'turning 60', 'my 60th birthday'], keywords: ['60', 'sixty'] }),
  E({ id: 'turned-65', name: 'I turned 65', emoji: '🎂', category: 'milestone',
    tasks: birthday(65, 'Government health coverage enrollment windows (e.g. Medicare) open around 65 with lifelong late penalties — this is the deadline birthday.', 'Enroll in senior health programs and schedule the works: hearing, vision, vaccines.'),
    phrases: ['i turned 65', 'turning 65', 'my 65th birthday'], keywords: ['65', 'sixty-five', 'medicare'] }),
  E({ id: 'started-college', name: "I'm starting college", emoji: '🎒', category: 'milestone', tasks: enrollment('college'),
    phrases: ['starting college', 'starting university', 'going to college', 'off to university', 'i got into college'],
    keywords: ['freshman', 'enrollment', 'campus', 'dorm'] }),
  E({ id: 'finished-high-school', name: 'I finished high school', emoji: '🎓', category: 'milestone', tasks: enrollment('what comes after high school'),
    phrases: ['finished high school', 'graduated high school', 'high school graduation'],
    keywords: ['school', 'graduation'] }),
  E({ id: 'first-job-ever', name: 'I got my first job', emoji: '🧾', category: 'milestone', tasks: career('your first job'),
    phrases: ['my first job', 'got my first job', 'first job ever', 'starting my first job'],
    keywords: ['first', 'paycheck', 'payslip'] }),
  E({ id: 'first-apartment', name: "I'm moving into my first apartment", emoji: '🔑', category: 'milestone', tasks: renting('your first apartment'),
    phrases: ['my first apartment', 'first apartment', 'moving out of my parents', 'moving out for the first time'],
    keywords: ['renting', 'landlord', 'roommate'] }),
  E({ id: 'became-citizen', name: 'I became a citizen', emoji: '🗽', category: 'milestone', tasks: application('citizenship', 'Citizenship authority'),
    phrases: ['became a citizen', 'becoming a citizen', 'citizenship ceremony', 'applying for citizenship', 'naturalization'],
    keywords: ['citizen', 'citizenship', 'naturalization', 'oath'] }),
  E({ id: 'got-permanent-residency', name: 'I got permanent residency', emoji: '🛂', category: 'milestone', tasks: application('permanent residency', 'Immigration authority'),
    phrases: ['got permanent residency', 'got my green card', 'became a permanent resident', 'received permanent residence'],
    keywords: ['residency', 'resident'] }),
  E({ id: 'adopted-a-child', name: 'We adopted a child', emoji: '🤱', category: 'milestone', tasks: legal('the adoption'),
    phrases: ['we adopted a child', 'adopting a child', 'we are adopting', 'adoption process'],
    keywords: ['adoption', 'adoptive'] }),
  E({ id: 'fostering-a-child', name: 'We are fostering a child', emoji: '🏡', category: 'milestone', tasks: application('foster care licensing', 'Family services'),
    phrases: ['fostering a child', 'becoming foster parents', 'foster care', 'we are fostering'],
    keywords: ['foster', 'fostering'] }),
  E({ id: 'became-grandparent', name: 'I became a grandparent', emoji: '👵', category: 'milestone', tasks: care('supporting the new family'),
    phrases: ['became a grandparent', 'becoming a grandparent', 'my first grandchild', 'i am a grandmother', 'i am a grandfather'],
    keywords: ['grandchild', 'grandparent', 'grandson', 'granddaughter'] }),
  E({ id: 'empty-nest', name: 'Our last child moved out', emoji: '🕊️', category: 'milestone', tasks: finance('the empty-nest reset'),
    phrases: ['last child moved out', 'empty nest', 'kids moved out', 'children left home'],
    keywords: ['nest', 'downsize', 'downsizing'] }),
  E({ id: 'paid-off-mortgage', name: 'We paid off the mortgage', emoji: '🏠', category: 'milestone', tasks: finance('life after the mortgage'),
    phrases: ['paid off the mortgage', 'paid off our mortgage', 'mortgage free', 'final mortgage payment'],
    keywords: ['payoff', 'lien'] }),
  E({ id: 'paid-off-student-loans', name: 'I paid off my student loans', emoji: '🎓', category: 'milestone', tasks: finance('life after student loans'),
    phrases: ['paid off my student loans', 'student loans paid off', 'loan free', 'made my last loan payment'],
    keywords: ['loans', 'payoff'] }),
  E({ id: 'debt-free', name: 'I became debt-free', emoji: '🎉', category: 'milestone', tasks: finance('staying debt-free'),
    phrases: ['debt free', 'paid off all my debt', 'out of debt'],
    keywords: ['debt'] }),
  E({ id: 'windfall', name: 'I received a windfall', emoji: '💰', category: 'milestone', tasks: finance('managing the windfall'),
    phrases: ['won the lottery', 'received a windfall', 'came into money', 'got a large bonus', 'big inheritance'],
    keywords: ['windfall', 'lottery', 'jackpot', 'bonus'] }),
  E({ id: 'received-inheritance', name: 'I received an inheritance', emoji: '🏛️', category: 'milestone', tasks: legal('the inheritance'),
    phrases: ['received an inheritance', 'i inherited', 'named in a will'],
    keywords: ['inheritance', 'inherited', 'heir', 'bequest'] }),
  E({ id: 'published-a-book', name: 'I published a book', emoji: '📚', category: 'milestone', tasks: career('publishing your book'),
    phrases: ['published a book', 'publishing my book', 'my book is coming out', 'i wrote a book'],
    keywords: ['published', 'publisher', 'author', 'isbn'] }),
  E({ id: 'earned-doctorate', name: 'I earned my doctorate', emoji: '🎓', category: 'milestone', tasks: career('life after the doctorate'),
    phrases: ['earned my doctorate', 'finished my phd', 'defended my thesis', 'got my phd', 'completed my doctorate'],
    keywords: ['phd', 'doctorate', 'thesis', 'dissertation', 'postdoc'] }),
  E({ id: 'military-enlistment', name: "I'm enlisting in the military", emoji: '🎖️', category: 'milestone', tasks: application('enlistment', 'Military recruitment'),
    phrases: ['enlisting in the military', 'joining the military', 'joining the army', 'joining the navy', 'joining the air force'],
    keywords: ['enlist', 'enlisting', 'military', 'army', 'navy', 'recruit'] }),
  E({ id: 'military-discharge', name: "I'm leaving the military", emoji: '🎖️', category: 'milestone', tasks: application('veteran benefits and transition', 'Veterans affairs'),
    phrases: ['leaving the military', 'getting discharged', 'end of my service', 'leaving the army'],
    keywords: ['discharge', 'veteran', 'veterans', 'civilian'] }),
  E({ id: 'became-manager', name: 'I became a manager', emoji: '📈', category: 'milestone', tasks: career('your first management role'),
    phrases: ['became a manager', 'first management role', 'i am now a manager', 'leading a team for the first time'],
    keywords: ['manager', 'management', 'promotion', 'team'] }),
  E({ id: 'started-nonprofit', name: "I'm starting a nonprofit", emoji: '🤝', category: 'milestone', tasks: application('nonprofit registration', 'Registrar + tax authority'),
    phrases: ['starting a nonprofit', 'starting a charity', 'founding a nonprofit', 'registering a charity'],
    keywords: ['nonprofit', 'charity', 'foundation', 'ngo'] }),
  E({ id: 'legal-name-change', name: "I'm changing my legal name", emoji: '✍️', category: 'milestone', tasks: application('the legal name change', 'Civil registry / court'),
    phrases: ['changing my name', 'legal name change', 'change my legal name'],
    keywords: ['name', 'rename'] }),
  E({ id: 'quit-smoking', name: 'I quit smoking', emoji: '🚭', category: 'milestone', tasks: care('your quit plan'),
    phrases: ['quit smoking', 'quitting smoking', 'stopped smoking', 'giving up cigarettes'],
    keywords: ['smoking', 'cigarettes', 'nicotine', 'vaping'] }),
  E({ id: 'first-time-voter', name: "I'm voting for the first time", emoji: '🗳️', category: 'milestone', tasks: application('voter registration and your first ballot', 'Electoral authority'),
    phrases: ['voting for the first time', 'first time voting', 'my first election'],
    keywords: ['vote', 'voting', 'election', 'ballot'] }),
  E({ id: 'child-baptism', name: "We're planning our child's baptism", emoji: '⛪', category: 'milestone', tasks: celebration('the baptism'),
    phrases: ['planning a baptism', "child's baptism", 'christening'],
    keywords: ['baptism', 'christening', 'godparents'] }),
  E({ id: 'first-communion', name: "We're planning a first communion", emoji: '⛪', category: 'milestone', tasks: celebration('the first communion'),
    phrases: ['first communion'], keywords: ['communion'] }),
  E({ id: 'confirmation-ceremony', name: "We're planning a confirmation", emoji: '⛪', category: 'milestone', tasks: celebration('the confirmation'),
    phrases: ['planning a confirmation', 'confirmation ceremony'], keywords: ['confirmation'] }),
  E({ id: 'bar-mitzvah', name: "We're planning a bar/bat mitzvah", emoji: '✡️', category: 'milestone', tasks: celebration('the bar/bat mitzvah'),
    phrases: ['bar mitzvah', 'bat mitzvah'], keywords: ['mitzvah', 'synagogue', 'torah'] }),
  E({ id: 'quinceanera', name: "We're planning a quinceañera", emoji: '👗', category: 'milestone', tasks: celebration('the quinceañera'),
    phrases: ['quinceanera', 'quinceañera', '15th birthday party'], keywords: ['quince', 'fifteen'] }),
  E({ id: 'sweet-sixteen', name: "We're planning a sweet sixteen", emoji: '🎂', category: 'milestone', tasks: celebration('the sweet sixteen'),
    phrases: ['sweet sixteen', 'sweet 16', '16th birthday party'], keywords: ['sixteen', '16'] }),
  E({ id: 'moving-abroad', name: "I'm moving abroad", emoji: '🌍', category: 'milestone', tasks: trip('the move abroad', true),
    phrases: ['moving abroad', 'moving overseas', 'relocating abroad', 'moving to another country', 'emigrating'],
    keywords: ['abroad', 'overseas', 'expat', 'emigrate', 'relocation'] }),
  E({ id: 'returning-from-abroad', name: "I'm moving back home from abroad", emoji: '🏠', category: 'milestone', tasks: trip('the move back home', true),
    phrases: ['moving back home', 'returning from abroad', 'repatriating', 'coming back home after living abroad'],
    keywords: ['repatriation', 'returning', 'homecoming'] }),
  E({ id: 'gap-year', name: "I'm taking a gap year", emoji: '🌏', category: 'milestone', tasks: trip('the gap year', true),
    phrases: ['taking a gap year', 'gap year', 'year off to travel'],
    keywords: ['gap', 'backpacking', 'sabbatical'] }),
  E({ id: 'semester-abroad', name: "I'm doing a semester abroad", emoji: '✈️', category: 'milestone', tasks: enrollment('the semester abroad'),
    phrases: ['semester abroad', 'studying abroad', 'exchange semester', 'study exchange'],
    keywords: ['exchange', 'erasmus', 'studying'] }),
  E({ id: 'first-marathon', name: "I'm running my first marathon", emoji: '🏃', category: 'milestone', tasks: sport('your first marathon'),
    phrases: ['my first marathon', 'first marathon', 'running a marathon for the first time'],
    keywords: ['marathon', '26.2', '42k'] }),
];
