import { LifeEventTemplate } from '../types';
import { E, celebration, digital, hobby, homeProject, kidParty, licence, purchase, sport, trip } from './builder';

/** Extended leisure & lifestyle catalog — compact, archetype-based events. */
export const extraLeisure: LifeEventTemplate[] = [
  E({ id: 'kids-birthday-party', name: "I'm planning my kid's birthday party", emoji: '🎈', category: 'leisure', pack: kidParty("the birthday party"),
    summary: 'Venue, invitations, RSVPs, allergies, cake and activities — a kid\'s party is a small event production with a hard deadline.',
    phrases: ["son's birthday", "daughter's birthday", "kid's birthday", 'birthday party', "my child's birthday", '5th birthday', 'first birthday'],
    keywords: ['birthday', 'party', 'son', 'daughter', 'kid', 'kids', 'child', 'turning'] }),
  E({ id: 'adult-birthday-party', name: "I'm planning a birthday party", emoji: '🎂', category: 'leisure', pack: celebration('the birthday party'),
    phrases: ['my birthday party', 'birthday party', 'planning a birthday', 'birthday dinner'],
    keywords: ['birthday', 'party'] }),
  E({ id: 'surprise-party', name: "I'm planning a surprise party", emoji: '🤫', category: 'leisure', pack: celebration('the surprise party'),
    phrases: ['surprise party', 'planning a surprise'], keywords: ['surprise', 'party'] }),
  E({ id: 'graduation-party', name: "We're planning a graduation party", emoji: '🎓', category: 'leisure', pack: celebration('the graduation party'),
    phrases: ['graduation party', 'grad party'], keywords: ['graduation', 'party'] }),
  E({ id: 'baby-shower', name: "We're planning a baby shower", emoji: '🍼', category: 'leisure', pack: celebration('the baby shower'),
    phrases: ['baby shower', 'planning a shower for'], keywords: ['shower', 'registry'] }),
  E({ id: 'gender-reveal', name: "We're planning a gender reveal", emoji: '🎀', category: 'leisure', pack: celebration('the gender reveal'),
    phrases: ['gender reveal'], keywords: ['reveal'] }),
  E({ id: 'bridal-shower', name: "We're planning a bridal shower", emoji: '💐', category: 'leisure', pack: celebration('the bridal shower'),
    phrases: ['bridal shower', 'hen party', 'hen do'], keywords: ['bridal', 'hen'] }),
  E({ id: 'bachelor-party', name: "I'm planning a bachelor party", emoji: '🍻', category: 'leisure', pack: celebration('the bachelor party'),
    phrases: ['bachelor party', 'stag party', 'stag do'], keywords: ['bachelor', 'stag', 'groomsmen'] }),
  E({ id: 'bachelorette-party', name: "I'm planning a bachelorette party", emoji: '🥳', category: 'leisure', pack: celebration('the bachelorette party'),
    phrases: ['bachelorette party', 'bachelorette weekend'], keywords: ['bachelorette', 'bridesmaids'] }),
  E({ id: 'retirement-party', name: "We're planning a retirement party", emoji: '🎊', category: 'leisure', pack: celebration('the retirement party'),
    phrases: ['retirement party', 'retirement send-off'], keywords: ['send-off'] }),
  E({ id: 'housewarming', name: "We're planning a housewarming", emoji: '🏡', category: 'leisure', pack: celebration('the housewarming'),
    phrases: ['housewarming', 'house warming party'], keywords: ['housewarming'] }),
  E({ id: 'engagement-party', name: "We're planning an engagement party", emoji: '🥂', category: 'leisure', pack: celebration('the engagement party'),
    phrases: ['engagement party'], keywords: ['toast'] }),
  E({ id: 'family-reunion', name: "I'm organizing a family reunion", emoji: '👨‍👩‍👧‍👦', category: 'leisure', pack: celebration('the family reunion'),
    phrases: ['family reunion', 'organizing a reunion', 'family get together'], keywords: ['reunion', 'relatives', 'family'] }),
  E({ id: 'holiday-hosting', name: "I'm hosting the holidays", emoji: '🦃', category: 'leisure', pack: celebration('the holiday dinner'),
    phrases: ['hosting thanksgiving', 'hosting christmas', 'hosting the holidays', 'holiday dinner at ours'],
    keywords: ['thanksgiving', 'christmas', 'hanukkah', 'hosting', 'holidays'] }),
  E({ id: 'dinner-party', name: "I'm hosting a dinner party", emoji: '🍽️', category: 'leisure', pack: celebration('the dinner party'),
    phrases: ['dinner party', 'hosting a dinner'], keywords: ['dinner', 'guests', 'menu'] }),
  E({ id: 'backyard-bbq', name: "I'm hosting a barbecue", emoji: '🍔', category: 'leisure', pack: celebration('the barbecue'),
    phrases: ['hosting a barbecue', 'backyard bbq', 'cookout'], keywords: ['bbq', 'barbecue', 'grill', 'cookout'] }),
  E({ id: 'road-trip', name: "We're planning a road trip", emoji: '🛣️', category: 'leisure', pack: trip('the road trip', false),
    phrases: ['road trip', 'driving across', 'cross country drive'], keywords: ['roadtrip', 'drive', 'route'] }),
  E({ id: 'camping-trip', name: "We're going camping", emoji: '🏕️', category: 'leisure', pack: trip('the camping trip', false),
    phrases: ['going camping', 'camping trip', 'booking a campsite'], keywords: ['camping', 'campsite', 'tent', 'hiking'] }),
  E({ id: 'national-parks-trip', name: "We're visiting national parks", emoji: '🏞️', category: 'leisure', pack: trip('the national parks trip', false),
    phrases: ['national park trip', 'visiting yellowstone', 'national parks tour'], keywords: ['park', 'parks', 'yellowstone', 'yosemite', 'banff'] }),
  E({ id: 'ski-trip', name: "We're planning a ski trip", emoji: '⛷️', category: 'leisure', pack: trip('the ski trip', false),
    phrases: ['ski trip', 'ski vacation', 'going skiing', 'snowboarding trip'], keywords: ['ski', 'skiing', 'snowboard', 'slopes', 'resort'] }),
  E({ id: 'beach-vacation', name: "We're planning a beach vacation", emoji: '🏖️', category: 'leisure', pack: trip('the beach vacation', false),
    phrases: ['beach vacation', 'beach trip', 'week at the beach'], keywords: ['beach', 'seaside', 'resort'] }),
  E({ id: 'cruise', name: "We're going on a cruise", emoji: '🛳️', category: 'leisure', pack: trip('the cruise', true),
    phrases: ['going on a cruise', 'booked a cruise', 'cruise vacation'], keywords: ['cruise', 'cabin', 'port'] }),
  E({ id: 'theme-park-trip', name: "We're planning a theme park trip", emoji: '🎢', category: 'leisure', pack: trip('the theme park trip', false),
    phrases: ['theme park trip', 'taking the kids to disney', 'disney trip', 'universal studios trip'],
    keywords: ['disney', 'disneyland', 'universal', 'rides'] }),
  E({ id: 'backpacking-trip', name: "I'm going backpacking", emoji: '🎒', category: 'leisure', pack: trip('the backpacking trip', true),
    phrases: ['going backpacking', 'backpacking through', 'backpacking trip'], keywords: ['backpacking', 'hostels', 'interrail'] }),
  E({ id: 'honeymoon', name: "We're planning our honeymoon", emoji: '🌙', category: 'leisure', pack: trip('the honeymoon', true),
    phrases: ['planning our honeymoon', 'honeymoon'], keywords: ['honeymoon', 'newlyweds'] }),
  E({ id: 'babymoon', name: "We're planning a babymoon", emoji: '🤰', category: 'leisure', pack: trip('the babymoon', false),
    phrases: ['babymoon'], keywords: ['babymoon'] }),
  E({ id: 'safari', name: "We're planning a safari", emoji: '🦁', category: 'leisure', pack: trip('the safari', true),
    phrases: ['planning a safari', 'safari trip', 'going on safari'], keywords: ['safari', 'kenya', 'tanzania'] }),
  E({ id: 'music-festival', name: "I'm going to a music festival", emoji: '🎪', category: 'leisure', pack: trip('the festival weekend', false),
    phrases: ['music festival', 'festival tickets', 'going to coachella', 'going to glastonbury'],
    keywords: ['festival', 'coachella', 'glastonbury', 'tickets', 'camping'] }),
  E({ id: 'big-game-trip', name: "I'm traveling to a big game", emoji: '🏟️', category: 'leisure', pack: trip('the game weekend', false),
    phrases: ['going to the super bowl', 'tickets to the final', 'away game trip', 'world cup trip'],
    keywords: ['tickets', 'stadium', 'playoffs', 'finals'] }),
  E({ id: 'visiting-family-overseas', name: "We're visiting family overseas", emoji: '👪', category: 'leisure', pack: trip('the family visit', true),
    phrases: ['visiting family overseas', 'visiting family abroad', 'seeing family back home'],
    keywords: ['grandparents', 'homeland'] }),
  E({ id: 'hosting-overseas-guests', name: "We're hosting guests from abroad", emoji: '🛬', category: 'leisure', pack: celebration('the visit'),
    phrases: ['hosting guests from abroad', 'family visiting from overseas', 'in-laws visiting'],
    keywords: ['guests', 'visitors', 'invitation letter'] }),
  E({ id: 'exchange-student', name: "We're hosting an exchange student", emoji: '🌐', category: 'leisure', pack: celebration('hosting the exchange student'),
    phrases: ['hosting an exchange student', 'host family'], keywords: ['exchange', 'host', 'student'] }),
  E({ id: 'summer-camp', name: "I'm arranging summer camp for the kids", emoji: '⛺', category: 'leisure', pack: hobby('summer camp'),
    phrases: ['summer camp', 'camp registration', 'day camp for the kids'], keywords: ['camp', 'summer', 'counselor'] }),
  E({ id: 'kids-sports-season', name: "My kid's sports season is starting", emoji: '⚽', category: 'leisure', pack: hobby("the kids' sports season"),
    phrases: ['sports season is starting', 'signing up for soccer', 'little league', 'hockey season'],
    keywords: ['soccer', 'hockey', 'league', 'practice', 'season'] }),
  E({ id: 'marathon-training', name: "I'm training for a marathon", emoji: '🏃', category: 'leisure', pack: sport('the marathon'),
    phrases: ['training for a marathon', 'marathon training', 'signed up for a marathon', 'half marathon'],
    keywords: ['marathon', 'running', 'race', 'training'] }),
  E({ id: 'triathlon', name: "I'm training for a triathlon", emoji: '🏊', category: 'leisure', pack: sport('the triathlon'),
    phrases: ['training for a triathlon', 'doing a triathlon', 'ironman'], keywords: ['triathlon', 'ironman', 'swim'] }),
  E({ id: 'cycling-event', name: "I'm training for a cycling event", emoji: '🚴', category: 'leisure', pack: sport('the cycling event'),
    phrases: ['cycling event', 'century ride', 'gran fondo', 'bike race'], keywords: ['cycling', 'fondo', 'peloton'] }),
  E({ id: 'joining-gym', name: "I'm starting a fitness routine", emoji: '💪', category: 'leisure', pack: hobby('the fitness routine'),
    phrases: ['joining a gym', 'starting a fitness routine', 'getting in shape', 'new gym membership', 'personal trainer'],
    keywords: ['gym', 'fitness', 'workout', 'trainer', 'crossfit'] }),
  E({ id: 'learning-to-drive', name: "I'm learning to drive", emoji: '🚗', category: 'leisure', pack: licence('your driving licence', 'Licensing authority'),
    phrases: ['learning to drive', 'driving lessons', 'getting my licence', 'getting my license', 'driving test'],
    keywords: ['driving', 'lessons', 'licence', 'license', 'instructor'] }),
  E({ id: 'learning-instrument', name: "I'm learning an instrument", emoji: '🎸', category: 'leisure', pack: hobby('the instrument'),
    phrases: ['learning an instrument', 'learning guitar', 'learning piano', 'music lessons'],
    keywords: ['guitar', 'piano', 'violin', 'instrument', 'lessons'] }),
  E({ id: 'learning-language', name: "I'm learning a language", emoji: '🗣️', category: 'leisure', pack: hobby('the language'),
    phrases: ['learning a language', 'learning spanish', 'learning french', 'language classes'],
    keywords: ['language', 'spanish', 'french', 'duolingo', 'fluent'] }),
  E({ id: 'cooking-classes', name: "I'm taking cooking classes", emoji: '👨‍🍳', category: 'leisure', pack: hobby('the cooking course'),
    phrases: ['cooking classes', 'learning to cook', 'culinary course'], keywords: ['cooking', 'culinary', 'baking'] }),
  E({ id: 'art-classes', name: "I'm taking art classes", emoji: '🎨', category: 'leisure', pack: hobby('the art classes'),
    phrases: ['art classes', 'painting classes', 'pottery class', 'drawing lessons'],
    keywords: ['art', 'painting', 'pottery', 'drawing', 'sculpture'] }),
  E({ id: 'dance-classes', name: "We're taking dance classes", emoji: '💃', category: 'leisure', pack: hobby('the dance classes'),
    phrases: ['dance classes', 'learning to dance', 'salsa lessons', 'ballroom dancing'],
    keywords: ['dance', 'dancing', 'salsa', 'ballroom'] }),
  E({ id: 'book-club', name: "I'm starting a book club", emoji: '📖', category: 'leisure', pack: hobby('the book club'),
    phrases: ['starting a book club', 'book club'], keywords: ['book', 'reading', 'club'] }),
  E({ id: 'starting-podcast', name: "I'm starting a podcast", emoji: '🎙️', category: 'leisure', pack: digital('the podcast'),
    phrases: ['starting a podcast', 'launching a podcast'], keywords: ['podcast', 'episodes', 'microphone'] }),
  E({ id: 'starting-youtube', name: "I'm starting a YouTube channel", emoji: '📹', category: 'leisure', pack: digital('the channel'),
    phrases: ['starting a youtube channel', 'becoming a youtuber', 'making videos'], keywords: ['youtube', 'channel', 'videos', 'vlog'] }),
  E({ id: 'starting-blog', name: "I'm starting a blog / newsletter", emoji: '📝', category: 'leisure', pack: digital('the blog'),
    phrases: ['starting a blog', 'starting a newsletter', 'launching a substack'], keywords: ['blog', 'newsletter', 'substack', 'writing'] }),
  E({ id: 'writing-novel', name: "I'm writing a novel", emoji: '✍️', category: 'leisure', pack: hobby('the novel'),
    phrases: ['writing a novel', 'writing a book', 'nanowrimo'], keywords: ['novel', 'manuscript', 'chapters'] }),
  E({ id: 'volunteering', name: "I'm starting to volunteer", emoji: '🤲', category: 'leisure', pack: hobby('the volunteering'),
    phrases: ['starting to volunteer', 'volunteering at', 'volunteer work'], keywords: ['volunteer', 'volunteering', 'shelter'] }),
  E({ id: 'charity-fundraiser', name: "I'm organizing a fundraiser", emoji: '🎗️', category: 'leisure', pack: celebration('the fundraiser'),
    phrases: ['organizing a fundraiser', 'charity event', 'fundraising drive'], keywords: ['fundraiser', 'charity', 'donations'] }),
  E({ id: 'community-garden', name: "I'm joining a community garden", emoji: '🌱', category: 'leisure', pack: hobby('the community garden plot'),
    phrases: ['community garden', 'allotment'], keywords: ['garden', 'allotment', 'plot'] }),
  E({ id: 'garden-overhaul', name: "We're redoing the garden", emoji: '🌳', category: 'leisure', pack: homeProject('the garden overhaul', false),
    phrases: ['redoing the garden', 'landscaping the yard', 'garden makeover', 'new lawn'],
    keywords: ['landscaping', 'garden', 'yard', 'lawn', 'patio'] }),
  E({ id: 'building-deck', name: "We're building a deck", emoji: '🪵', category: 'leisure', pack: homeProject('the deck build', true),
    phrases: ['building a deck', 'new deck', 'building a patio'], keywords: ['deck', 'pergola'] }),
  E({ id: 'pool-install', name: "We're installing a pool", emoji: '🏊', category: 'leisure', pack: homeProject('the pool installation', true),
    phrases: ['installing a pool', 'putting in a pool', 'swimming pool install'], keywords: ['pool', 'hot tub', 'jacuzzi'] }),
  E({ id: 'home-theater', name: "I'm building a home theater", emoji: '🎬', category: 'leisure', pack: purchase('the home theater setup', {}),
    phrases: ['home theater', 'home cinema', 'media room'], keywords: ['theater', 'projector', 'surround'] }),
  E({ id: 'smart-home', name: "I'm setting up a smart home", emoji: '🏠', category: 'leisure', pack: digital('the smart home'),
    phrases: ['smart home setup', 'home automation', 'smart lights and locks'], keywords: ['smart', 'automation', 'alexa', 'homekit'] }),
  E({ id: 'aquarium', name: "I'm setting up an aquarium", emoji: '🐠', category: 'leisure', pack: purchase('the aquarium', {}),
    phrases: ['setting up an aquarium', 'fish tank', 'getting fish'], keywords: ['aquarium', 'fish', 'tank', 'reef'] }),
  E({ id: 'backyard-chickens', name: "We're getting backyard chickens", emoji: '🐔', category: 'leisure', pack: licence('keeping backyard chickens', 'Municipality'),
    phrases: ['backyard chickens', 'getting chickens', 'chicken coop'], keywords: ['chickens', 'coop', 'hens'] }),
  E({ id: 'beekeeping', name: "I'm starting beekeeping", emoji: '🐝', category: 'leisure', pack: licence('beekeeping', 'Agricultural authority'),
    phrases: ['starting beekeeping', 'getting bees', 'beehive'], keywords: ['bees', 'beekeeping', 'hive', 'honey'] }),
  E({ id: 'drone', name: 'I got a drone', emoji: '🛸', category: 'leisure', pack: licence('flying the drone', 'Aviation authority'),
    phrases: ['got a drone', 'buying a drone', 'drone registration'], keywords: ['drone', 'faa', 'quadcopter'] }),
  E({ id: 'ham-radio', name: "I'm getting a ham radio licence", emoji: '📻', category: 'leisure', pack: licence('the amateur radio licence', 'Radio authority'),
    phrases: ['ham radio licence', 'ham radio license', 'amateur radio'], keywords: ['ham', 'radio', 'callsign'] }),
  E({ id: 'scuba', name: "I'm getting scuba certified", emoji: '🤿', category: 'leisure', pack: licence('the scuba certification', 'PADI / SSI'),
    phrases: ['scuba certification', 'getting scuba certified', 'learning to dive', 'padi course'],
    keywords: ['scuba', 'diving', 'padi', 'openwater'] }),
  E({ id: 'pilot-license', name: "I'm getting a pilot licence", emoji: '🛩️', category: 'leisure', pack: licence('the private pilot licence', 'Aviation authority'),
    phrases: ['pilot licence', 'pilot license', 'learning to fly', 'flight school'], keywords: ['pilot', 'flying', 'aviation', 'cessna'] }),
  E({ id: 'motorcycle-license', name: "I'm getting a motorcycle licence", emoji: '🏍️', category: 'leisure', pack: licence('the motorcycle licence', 'Licensing authority'),
    phrases: ['motorcycle licence', 'motorcycle license', 'learning to ride'], keywords: ['rider', 'endorsement'] }),
  E({ id: 'sailing-course', name: "I'm learning to sail", emoji: '⛵', category: 'leisure', pack: licence('the sailing qualification', 'Sailing association'),
    phrases: ['learning to sail', 'sailing course', 'sailing lessons'], keywords: ['sailing', 'sail', 'skipper'] }),
  E({ id: 'hunting-license', name: "I'm getting a hunting licence", emoji: '🦌', category: 'leisure', pack: licence('the hunting licence', 'Wildlife authority'),
    phrases: ['hunting licence', 'hunting license', 'hunter safety course'], keywords: ['hunting', 'hunter', 'season'] }),
  E({ id: 'fishing-license', name: "I'm getting a fishing licence", emoji: '🎣', category: 'leisure', pack: licence('the fishing licence', 'Wildlife authority'),
    phrases: ['fishing licence', 'fishing license', 'getting into fishing'], keywords: ['fishing', 'angling', 'flyfishing'] }),
  E({ id: 'boating-license', name: "I'm getting a boating licence", emoji: '🚤', category: 'leisure', pack: licence('the boating licence', 'Maritime authority'),
    phrases: ['boating licence', 'boating license', 'boater safety course'], keywords: ['boating', 'boater'] }),
  E({ id: 'planning-proposal', name: "I'm planning a proposal", emoji: '💍', category: 'leisure', pack: celebration('the proposal'),
    phrases: ['planning a proposal', 'planning to propose', 'going to propose', 'buying an engagement ring'],
    keywords: ['propose', 'ring'] }),
  E({ id: 'gaming-pc', name: "I'm building a gaming PC", emoji: '🖥️', category: 'leisure', pack: purchase('the gaming PC', {}),
    phrases: ['building a gaming pc', 'building a pc', 'new gaming rig'], keywords: ['pc', 'gpu', 'gaming', 'rig'] }),
  E({ id: 'photography', name: "I'm getting into photography", emoji: '📷', category: 'leisure', pack: hobby('photography'),
    phrases: ['getting into photography', 'buying a camera', 'photography course'], keywords: ['photography', 'camera', 'lens'] }),
  E({ id: 'golf-membership', name: "I'm joining a golf club", emoji: '⛳', category: 'leisure', pack: hobby('golf'),
    phrases: ['joining a golf club', 'golf membership', 'taking up golf'], keywords: ['golf', 'clubs', 'course'] }),
  E({ id: 'new-bicycle', name: "I'm buying a bicycle", emoji: '🚲', category: 'leisure', pack: purchase('the bicycle', { insure: true }),
    phrases: ['buying a bike', 'buying a bicycle', 'new bike'], keywords: ['bicycle', 'bike', 'ebike'] }),
];
