import { LifeEventTemplate } from '../types';

export const gotMarried: LifeEventTemplate = {
  id: 'got-married',
  name: 'I got married',
  emoji: '💍',
  category: 'milestone',
  summary:
    'Marriage changes your tax filing status, insurance, beneficiaries and possibly your legal name — each with its own institution.',
  triggerPhrases: ['i got married', 'we got married', 'getting married', 'just married', 'i am married now'],
  keywords: ['married', 'marriage', 'wedding', 'spouse', 'wife', 'husband'],
  questions: [
    { id: 'marriage_date', prompt: 'When is (was) the wedding?', kind: 'date' },
    {
      id: 'name_change',
      prompt: 'Is anyone changing their legal name?',
      kind: 'boolean',
      gatesTasks: ['mar.name_id', 'mar.name_everywhere'],
    },
  ],
  tasks: [
    {
      id: 'mar.certificate',
      title: 'Obtain certified marriage certificates',
      description: 'Order several certified copies — almost every downstream change requires one.',
      domain: 'government',
      priority: 'critical',
      authority: 'Vital records office',
      startOffsetDays: 0,
      dueOffsetDays: 21,
    },
    {
      id: 'mar.tax_status',
      title: 'Update tax filing status',
      description: 'Notify the tax authority and review withholding — marriage changes brackets and credits.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax authority',
      startOffsetDays: 0,
      dueOffsetDays: 60,
      dependsOn: ['mar.certificate'],
    },
    {
      id: 'mar.insurance',
      title: 'Merge or update insurance policies',
      description: 'Add spouse to health coverage (there is usually a 30–60 day enrollment window), and review auto/home bundles.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Insurers / employer benefits',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      dependsOn: ['mar.certificate'],
    },
    {
      id: 'mar.beneficiaries',
      title: 'Update beneficiaries and emergency contacts',
      description: 'Pension, life insurance, retirement accounts and wills — beneficiary designations override wills in many places.',
      domain: 'finance',
      priority: 'high',
      authority: 'Banks / pension / insurer',
      startOffsetDays: 0,
      dueOffsetDays: 60,
    },
    {
      id: 'mar.name_id',
      title: 'Update legal name on core ID',
      description: 'Passport, driver’s licence and social security / national ID, in that order of dependency.',
      domain: 'government',
      priority: 'high',
      authority: 'ID authorities',
      startOffsetDays: 21,
      dueOffsetDays: 90,
      documents: ['Marriage certificate'],
      dependsOn: ['mar.certificate'],
    },
    {
      id: 'mar.name_everywhere',
      title: 'Propagate the new name everywhere else',
      description: 'Banks, employer, insurers, subscriptions — after core ID is updated.',
      domain: 'finance',
      priority: 'medium',
      authority: 'Various',
      startOffsetDays: 90,
      dueOffsetDays: 150,
      dependsOn: ['mar.name_id'],
    },
  ],
};
