import { LifeEventTemplate } from '../types';

/**
 * "I want to immigrate to Canada." — the plan runs from eligibility analysis
 * through document collection, application package, and post-submission
 * status monitoring. Offsets are relative to the target submission date.
 */
export const immigrateCanada: LifeEventTemplate = {
  id: 'immigrate-canada',
  name: 'I want to immigrate to Canada',
  emoji: '🍁',
  category: 'milestone',
  summary:
    'A structured path from eligibility analysis to a submitted application: document checklist, language tests, credential assessment, proof of funds, timeline and status monitoring.',
  triggerPhrases: [
    'i want to immigrate to canada',
    'immigrate to canada',
    'move to canada',
    'moving to canada',
    'canadian permanent residence',
    'express entry',
    'apply for canada pr',
  ],
  keywords: [
    'immigrate',
    'immigration',
    'canada',
    'canadian',
    'visa',
    'permanent',
    'residence',
    'express',
    'entry',
    'pr',
    'ircc',
  ],
  questions: [
    { id: 'target_date', prompt: 'Target date to submit the application?', kind: 'date' },
    {
      id: 'pathway',
      prompt: 'Which pathway are you considering?',
      kind: 'choice',
      choices: [
        'Express Entry (skilled worker)',
        'Provincial Nominee Program',
        'Family sponsorship',
        'Study permit first',
        'Not sure yet',
      ],
    },
    {
      id: 'has_spouse',
      prompt: 'Is a spouse or partner included in the application?',
      kind: 'boolean',
      gatesTasks: ['imm.spouse_docs', 'imm.spouse_language'],
    },
    {
      id: 'has_degree',
      prompt: 'Do you have a post-secondary degree from outside Canada?',
      kind: 'boolean',
      gatesTasks: ['imm.eca'],
    },
  ],
  tasks: [
    {
      id: 'imm.eligibility',
      title: 'Run the eligibility analysis',
      description:
        'Score yourself against the pathway criteria (age, education, language, work experience, funds). This decides the pathway and whether the rest of the plan is worth starting.',
      domain: 'immigration',
      priority: 'critical',
      authority: 'IRCC criteria',
      startOffsetDays: -270,
      dueOffsetDays: -240,
    },
    {
      id: 'imm.language_test',
      title: 'Book and take a language test (IELTS / CELPIP / TEF)',
      description:
        'Language scores drive skilled-worker points and expire after 2 years. Test seats book out weeks ahead; results take ~2 weeks.',
      domain: 'immigration',
      priority: 'critical',
      authority: 'Approved test centre',
      startOffsetDays: -240,
      dueOffsetDays: -150,
      documents: ['Passport'],
      dependsOn: ['imm.eligibility'],
    },
    {
      id: 'imm.eca',
      title: 'Get an Educational Credential Assessment (ECA)',
      description:
        'Foreign degrees must be assessed by a designated organization (e.g. WES). Processing takes 1–3 months — start early.',
      domain: 'education',
      priority: 'critical',
      authority: 'WES / designated org',
      startOffsetDays: -240,
      dueOffsetDays: -120,
      documents: ['Degree certificates', 'Transcripts sent directly by institution'],
      dependsOn: ['imm.eligibility'],
    },
    {
      id: 'imm.passport',
      title: 'Ensure passports are valid',
      description:
        'Every applicant needs a passport valid well beyond the target landing date. Renew now if it expires within 2 years.',
      domain: 'government',
      priority: 'high',
      authority: 'Passport office',
      startOffsetDays: -240,
      dueOffsetDays: -180,
    },
    {
      id: 'imm.work_history',
      title: 'Compile the work history evidence',
      description:
        'Reference letters on company letterhead stating title, duties, dates, hours and salary — matched to the official occupation classification (NOC). The most commonly refused document.',
      domain: 'employment',
      priority: 'critical',
      authority: 'Current & past employers',
      startOffsetDays: -210,
      dueOffsetDays: -90,
      documents: ['Reference letters', 'Employment contracts', 'Pay slips'],
      dependsOn: ['imm.eligibility'],
    },
    {
      id: 'imm.police_certs',
      title: 'Obtain police certificates',
      description:
        'One from every country you lived in for 6+ months since age 18. Some countries take months — order in parallel, early.',
      domain: 'legal',
      priority: 'high',
      authority: 'Police authorities per country',
      startOffsetDays: -180,
      dueOffsetDays: -60,
      documents: ['ID documents', 'Address history'],
    },
    {
      id: 'imm.proof_of_funds',
      title: 'Prepare proof of settlement funds',
      description:
        'Official bank letters showing the required amount, held for 6+ months. Large recent deposits need documented explanations.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Your banks',
      startOffsetDays: -180,
      dueOffsetDays: -30,
      documents: ['Bank letters', '6-month statements'],
    },
    {
      id: 'imm.spouse_language',
      title: 'Spouse language test (optional points)',
      description: 'A spouse language test adds points; weigh cost vs. benefit for your score.',
      domain: 'immigration',
      priority: 'medium',
      authority: 'Approved test centre',
      startOffsetDays: -210,
      dueOffsetDays: -120,
    },
    {
      id: 'imm.spouse_docs',
      title: 'Compile spouse/partner documents',
      description: 'Marriage certificate or proof of common-law relationship, plus spouse ID, ECA and police certificates.',
      domain: 'legal',
      priority: 'high',
      authority: 'Various',
      startOffsetDays: -180,
      dueOffsetDays: -60,
      documents: ['Marriage / relationship proof', 'Spouse passport'],
    },
    {
      id: 'imm.profile',
      title: 'Create the online profile / enter the pool',
      description:
        'Submit the Express Entry profile (or PNP registration). Scores from the language test and ECA are entered here — accuracy matters, misrepresentation bans you for 5 years.',
      domain: 'immigration',
      priority: 'critical',
      authority: 'IRCC',
      startOffsetDays: -120,
      dueOffsetDays: -90,
      dependsOn: ['imm.language_test', 'imm.eca', 'imm.work_history'],
    },
    {
      id: 'imm.medical',
      title: 'Immigration medical exam',
      description:
        'Book with an IRCC-approved panel physician. Usually done after the invitation to apply; results are valid 12 months.',
      domain: 'health',
      priority: 'high',
      authority: 'Panel physician',
      startOffsetDays: -60,
      dueOffsetDays: -21,
      documents: ['Passport', 'Medical history'],
      dependsOn: ['imm.profile'],
    },
    {
      id: 'imm.application',
      title: 'Assemble and submit the application package',
      description:
        'Compile every document against the personalized checklist, complete the forms, pay the fees, and submit before the invitation deadline (typically 60 days).',
      domain: 'immigration',
      priority: 'critical',
      authority: 'IRCC',
      startOffsetDays: -30,
      dueOffsetDays: 0,
      documents: ['All collected documents', 'Fee payment'],
      dependsOn: ['imm.profile', 'imm.police_certs', 'imm.proof_of_funds', 'imm.medical'],
    },
    {
      id: 'imm.monitor',
      title: 'Monitor application status & respond to requests',
      description:
        'Track the application account for biometrics requests, additional document requests and the final decision. Requests usually have 30-day response windows.',
      domain: 'immigration',
      priority: 'high',
      authority: 'IRCC',
      startOffsetDays: 0,
      dueOffsetDays: 180,
      dependsOn: ['imm.application'],
    },
  ],
};
