import { LifeEventTemplate } from '../types';

/** Important events: high-stakes administration that isn't a lifelong milestone. */

export const newJob: LifeEventTemplate = {
  id: 'new-job',
  name: 'I got a new job',
  emoji: '💼',
  category: 'important',
  featured: true,
  summary:
    'The first month at a new employer is full of one-shot windows: benefits enrollment, retirement matching, and moving money and coverage over from the old job.',
  triggerPhrases: [
    'i got a new job',
    'starting a new job',
    'new job',
    'i was hired',
    'got hired',
    'accepted an offer',
    'changing jobs',
    'switching jobs',
  ],
  keywords: ['job', 'hired', 'offer', 'employer', 'work', 'career', 'salary'],
  questions: [
    { id: 'start_date', prompt: 'When is (was) the first day?', kind: 'date' },
    {
      id: 'had_previous_job',
      prompt: 'Are you coming from another employer?',
      kind: 'boolean',
      gatesTasks: ['job.old_retirement', 'job.coverage_bridge'],
    },
  ],
  tasks: [
    {
      id: 'job.contract',
      title: 'Review and sign the contract; gather onboarding documents',
      description: 'Read restrictive covenants before signing, and have ID, work authorization and banking details ready for day one.',
      domain: 'employment',
      priority: 'critical',
      authority: 'New employer',
      startOffsetDays: -21,
      dueOffsetDays: -7,
      documents: ['ID / work authorization', 'Banking details', 'Signed contract'],
    },
    {
      id: 'job.tax_forms',
      title: 'Complete tax withholding forms',
      description: 'Set withholding correctly at the start — mid-year job changes are a classic cause of under-withholding.',
      domain: 'tax',
      priority: 'high',
      authority: 'Employer payroll',
      startOffsetDays: 0,
      dueOffsetDays: 7,
    },
    {
      id: 'job.benefits_enrollment',
      title: 'Enroll in benefits within the new-hire window',
      description: 'Health, dental, life and disability elections usually must be made within 30 days of starting; miss it and you wait for open enrollment.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Employer benefits',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
    {
      id: 'job.retirement_enroll',
      title: 'Enroll in the retirement plan and capture the match',
      description: 'Contribute at least to the full employer match from the first eligible paycheck — the match is salary you otherwise decline.',
      domain: 'finance',
      priority: 'high',
      authority: 'Plan administrator',
      startOffsetDays: 0,
      dueOffsetDays: 45,
    },
    {
      id: 'job.old_retirement',
      title: "Decide on the old employer's retirement account",
      description: 'Roll it into the new plan or an IRA, or leave it — but decide; orphaned accounts with forgotten fees are endemic.',
      domain: 'finance',
      priority: 'medium',
      authority: 'Old plan administrator',
      startOffsetDays: 30,
      dueOffsetDays: 120,
    },
    {
      id: 'job.coverage_bridge',
      title: 'Bridge health coverage between jobs',
      description: 'Check exactly when old coverage ends and new begins; a gap of even days is an uninsured risk you can close with continuation coverage.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Old + new insurers',
      startOffsetDays: -14,
      dueOffsetDays: 14,
    },
    {
      id: 'job.payroll_check',
      title: 'Verify the first paycheck',
      description: 'Check gross pay, withholding, and that retirement and benefit deductions actually started.',
      domain: 'finance',
      priority: 'medium',
      authority: 'Employer payroll',
      startOffsetDays: 14,
      dueOffsetDays: 45,
      dependsOn: ['job.tax_forms'],
    },
  ],
};

export const lostJob: LifeEventTemplate = {
  id: 'lost-job',
  name: 'I lost my job',
  emoji: '📉',
  category: 'important',
  featured: true,
  summary:
    'The week after a job ends is deadline-dense: unemployment claims, health coverage continuation and severance review all have short windows.',
  triggerPhrases: [
    'i lost my job',
    'i was laid off',
    'got laid off',
    'i was fired',
    'got fired',
    'i am unemployed',
    'lost my job',
    'being made redundant',
    'laid off',
  ],
  keywords: ['unemployed', 'unemployment', 'layoff', 'fired', 'redundant', 'severance', 'jobless'],
  questions: [
    { id: 'last_day', prompt: 'When is (was) the last day of employment?', kind: 'date' },
    {
      id: 'has_severance',
      prompt: 'Were you offered a severance agreement?',
      kind: 'boolean',
      gatesTasks: ['loss.severance_review'],
    },
  ],
  tasks: [
    {
      id: 'loss.unemployment_claim',
      title: 'File the unemployment claim immediately',
      description: 'Benefits typically start from the filing date, not the layoff date — every day unfiled is money gone.',
      domain: 'government',
      priority: 'critical',
      authority: 'Unemployment agency',
      startOffsetDays: 0,
      dueOffsetDays: 7,
      documents: ['ID', 'Employment history', 'Termination letter'],
    },
    {
      id: 'loss.severance_review',
      title: 'Review the severance agreement before signing',
      description: 'You are usually trading legal claims for the payment; have the numbers and the release checked — the offer deadline is negotiable more often than people think.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Employment lawyer',
      startOffsetDays: 0,
      dueOffsetDays: 14,
    },
    {
      id: 'loss.health_continuation',
      title: 'Secure health coverage continuation',
      description: 'Election windows for continuation coverage (e.g. COBRA: 60 days) are strict; compare with marketplace plans triggered by the job-loss enrollment period.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Insurer / marketplace',
      startOffsetDays: 0,
      dueOffsetDays: 45,
    },
    {
      id: 'loss.budget_triage',
      title: 'Triage the budget',
      description: 'Cut or pause non-essentials, list fixed obligations, and compute the runway — decisions get better when the number is known.',
      domain: 'finance',
      priority: 'high',
      authority: '—',
      startOffsetDays: 0,
      dueOffsetDays: 14,
    },
    {
      id: 'loss.retirement_protect',
      title: 'Protect the retirement account',
      description: 'Do not cash out under stress — the tax and penalty haircut is severe. Decide between leaving it and rolling it over.',
      domain: 'finance',
      priority: 'high',
      authority: 'Plan administrator',
      startOffsetDays: 14,
      dueOffsetDays: 90,
    },
    {
      id: 'loss.employer_records',
      title: 'Collect records and references from the employer',
      description: 'Termination letter, service record, pay history and named references — much easier to get now than months later.',
      domain: 'employment',
      priority: 'medium',
      authority: 'Former employer HR',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
  ],
};

export const boughtCar: LifeEventTemplate = {
  id: 'bought-car',
  name: 'I bought a car',
  emoji: '🚗',
  category: 'important',
  featured: true,
  summary:
    'A car is only legally yours to drive once insurance, title and registration line up — each with its own office and deadline.',
  triggerPhrases: [
    'i bought a car',
    'buying a car',
    'bought a new car',
    'bought a used car',
    'got a car',
    'new car',
  ],
  keywords: ['car', 'vehicle', 'auto', 'automobile', 'truck', 'motorcycle'],
  questions: [
    { id: 'purchase_date', prompt: 'When is (was) the purchase?', kind: 'date' },
    {
      id: 'is_used',
      prompt: 'Is it a used vehicle?',
      kind: 'boolean',
      gatesTasks: ['car.inspection'],
    },
    {
      id: 'is_financed',
      prompt: 'Is it financed with a loan or lease?',
      kind: 'boolean',
      gatesTasks: ['car.loan_setup'],
    },
  ],
  tasks: [
    {
      id: 'car.insurance',
      title: 'Insure the car before driving it',
      description: 'Coverage must be effective from the moment you take possession — driving home uninsured is the classic day-one mistake.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Auto insurer',
      startOffsetDays: -7,
      dueOffsetDays: 0,
      documents: ['VIN', 'Purchase agreement'],
    },
    {
      id: 'car.title_registration',
      title: 'Transfer title and register the vehicle',
      description: 'Title transfer and registration deadlines are typically 10–30 days from purchase, with late fees after.',
      domain: 'government',
      priority: 'critical',
      authority: 'Vehicle registry',
      startOffsetDays: 0,
      dueOffsetDays: 14,
      documents: ['Title / bill of sale', 'Proof of insurance', 'ID'],
      dependsOn: ['car.insurance'],
    },
    {
      id: 'car.inspection',
      title: 'Pass safety / emissions inspection',
      description: 'Many jurisdictions require an inspection before a used vehicle can be registered in your name.',
      domain: 'government',
      priority: 'high',
      authority: 'Inspection station',
      startOffsetDays: 0,
      dueOffsetDays: 14,
    },
    {
      id: 'car.loan_setup',
      title: 'Set up loan/lease payments and check the lien',
      description: 'Autopay the payment, and confirm the lender is correctly recorded on the title so payoff later is clean.',
      domain: 'finance',
      priority: 'high',
      authority: 'Lender',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
    {
      id: 'car.sales_tax',
      title: 'Pay vehicle sales tax / transfer duty',
      description: 'Usually collected at registration for private sales — bring payment; the registry will not register without it.',
      domain: 'tax',
      priority: 'high',
      authority: 'Vehicle registry / tax authority',
      startOffsetDays: 0,
      dueOffsetDays: 14,
    },
  ],
};

export const lovedOnePassed: LifeEventTemplate = {
  id: 'loved-one-passed',
  name: 'A loved one passed away',
  emoji: '🕊️',
  category: 'important',
  featured: true,
  summary:
    'Grief comes with a case file no one warns you about. This plan sequences the administration — certificates, agencies, accounts, estate — so nothing urgent is missed.',
  triggerPhrases: [
    'passed away',
    'my father died',
    'my mother died',
    'a death in the family',
    'my parent died',
    'someone died',
    'handling an estate',
    'my spouse died',
  ],
  keywords: ['died', 'death', 'funeral', 'estate', 'probate', 'inheritance', 'deceased', 'widow', 'widower'],
  questions: [
    { id: 'date_of_death', prompt: 'Date of passing?', kind: 'date' },
    {
      id: 'is_executor',
      prompt: 'Are you the executor / administrator of the estate?',
      kind: 'boolean',
      gatesTasks: ['est.will_probate', 'est.estate_account', 'est.final_taxes'],
    },
  ],
  tasks: [
    {
      id: 'est.death_certificates',
      title: 'Obtain multiple certified death certificates',
      description: 'Nearly every institution below requires an original certified copy — order 8–10 up front; reordering later takes weeks.',
      domain: 'government',
      priority: 'critical',
      authority: 'Vital records office',
      startOffsetDays: 0,
      dueOffsetDays: 14,
    },
    {
      id: 'est.notify_agencies',
      title: 'Notify government agencies',
      description: 'Social security / pension agency, tax authority, electoral roll and licence registry — stops payments that would need repaying and prevents identity misuse.',
      domain: 'government',
      priority: 'critical',
      authority: 'Multiple agencies',
      startOffsetDays: 7,
      dueOffsetDays: 30,
      dependsOn: ['est.death_certificates'],
    },
    {
      id: 'est.will_probate',
      title: 'Locate the will and open probate',
      description: 'File with the probate court to be formally appointed — most institutions will not release assets until you hold letters of administration.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Probate court',
      startOffsetDays: 7,
      dueOffsetDays: 60,
      documents: ['Will', 'Death certificate', 'Asset inventory'],
      dependsOn: ['est.death_certificates'],
    },
    {
      id: 'est.banks_freeze',
      title: 'Notify banks and secure accounts',
      description: 'Freeze sole accounts, stop autopayments that will bounce, and keep records — joint accounts usually pass to the survivor directly.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Banks',
      startOffsetDays: 7,
      dueOffsetDays: 30,
      dependsOn: ['est.death_certificates'],
    },
    {
      id: 'est.estate_account',
      title: 'Open an estate account',
      description: 'One account through which everything estate-related flows — it keeps the accounting clean and the executor protected.',
      domain: 'finance',
      priority: 'high',
      authority: 'Bank',
      startOffsetDays: 30,
      dueOffsetDays: 90,
      dependsOn: ['est.will_probate'],
    },
    {
      id: 'est.insurance_claims',
      title: 'File life insurance and benefit claims',
      description: 'Life policies, employer death benefits, and survivor pensions — each claim needs a certificate and its own forms.',
      domain: 'insurance',
      priority: 'high',
      authority: 'Insurers / employers',
      startOffsetDays: 14,
      dueOffsetDays: 90,
      dependsOn: ['est.death_certificates'],
    },
    {
      id: 'est.subscriptions',
      title: 'Close accounts and subscriptions',
      description: 'Phone, utilities in their name, digital accounts and subscriptions — work from bank statements to find them all.',
      domain: 'utilities',
      priority: 'medium',
      authority: 'Various providers',
      startOffsetDays: 30,
      dueOffsetDays: 180,
    },
    {
      id: 'est.final_taxes',
      title: 'File the final tax return',
      description: 'The deceased’s final return (and possibly an estate return) is the executor’s legal responsibility, on the normal filing calendar.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax authority',
      startOffsetDays: 60,
      dueOffsetDays: 365,
      dependsOn: ['est.will_probate'],
    },
  ],
};
