import { LifeEventTemplate } from '../types';

/** Leisure & lifestyle: chosen projects that still carry real administration. */

export const tripAbroad: LifeEventTemplate = {
  id: 'trip-abroad',
  name: 'I planned a trip abroad',
  emoji: '✈️',
  category: 'leisure',
  featured: true,
  summary:
    'International travel has an admin critical path — passports, visas, insurance, money and the house you leave behind — and most of it has lead times.',
  triggerPhrases: [
    'trip to europe',
    'family trip',
    'planning a trip',
    'planned a trip',
    'traveling abroad',
    'travelling abroad',
    'going abroad',
    'vacation abroad',
    'international trip',
    'going on vacation',
  ],
  keywords: ['trip', 'travel', 'vacation', 'holiday', 'abroad', 'europe', 'flight', 'flights', 'passport', 'overseas'],
  questions: [
    { id: 'departure_date', prompt: 'When do you leave?', kind: 'date' },
    {
      id: 'with_minors',
      prompt: 'Are children traveling?',
      kind: 'boolean',
      gatesTasks: ['trip.minor_docs'],
    },
    {
      id: 'has_pets_home',
      prompt: 'Do you have pets or a home that needs looking after?',
      kind: 'boolean',
      gatesTasks: ['trip.house_sitting'],
    },
    {
      id: 'renting_car',
      prompt: 'Will you rent a car there?',
      kind: 'boolean',
      gatesTasks: ['trip.car_rental'],
    },
    {
      id: 'work_handover',
      prompt: 'Do you need to hand over work before leaving?',
      kind: 'boolean',
      gatesTasks: ['trip.work_prep'],
    },
  ],
  tasks: [
    {
      id: 'trip.passports',
      title: 'Check every passport: 6+ months validity',
      description: 'Many countries refuse entry with under six months left. Renewals can take 6–10 weeks — this is the task that sinks trips.',
      domain: 'government',
      priority: 'critical',
      authority: 'Passport office',
      startOffsetDays: -90,
      dueOffsetDays: -45,
    },
    {
      id: 'trip.visas',
      title: 'Sort visas and travel authorizations',
      description: 'Check each destination and transit country: visas, e-authorizations (ETIAS/ESTA-style) and entry rules for every traveler and passport.',
      domain: 'government',
      priority: 'critical',
      authority: 'Consulates / online systems',
      startOffsetDays: -60,
      dueOffsetDays: -21,
      documents: ['Passports', 'Photos', 'Itinerary'],
      dependsOn: ['trip.passports'],
    },
    {
      id: 'trip.minor_docs',
      title: 'Prepare documents for traveling children',
      description: 'Children need their own passports; a child traveling without both parents often needs a notarized consent letter at the border.',
      domain: 'government',
      priority: 'critical',
      authority: 'Passport office / notary',
      startOffsetDays: -90,
      dueOffsetDays: -30,
      documents: ['Child passports', 'Consent letter', 'Birth certificates'],
    },
    {
      id: 'trip.insurance',
      title: 'Get travel and medical insurance',
      description: 'Your domestic health coverage probably stops at the border; cover medical, cancellation and baggage for all travelers.',
      domain: 'insurance',
      priority: 'high',
      authority: 'Insurer',
      startOffsetDays: -45,
      dueOffsetDays: -14,
    },
    {
      id: 'trip.bookings',
      title: 'Lock in flights, stays and transport',
      description: 'Book with the names exactly as printed in passports — mismatched names are a denied-boarding classic.',
      domain: 'travel',
      priority: 'high',
      authority: 'Airlines / hotels',
      startOffsetDays: -60,
      dueOffsetDays: -21,
      dependsOn: ['trip.passports'],
    },
    {
      id: 'trip.health_prep',
      title: 'Check vaccinations and pack medications',
      description: 'Destination-specific vaccinations need lead time; prescriptions should travel in original packaging with copies of the scripts.',
      domain: 'health',
      priority: 'medium',
      authority: 'Travel clinic',
      startOffsetDays: -45,
      dueOffsetDays: -14,
    },
    {
      id: 'trip.money',
      title: 'Sort cards, currency and roaming',
      description: 'Tell your bank the travel dates, check card fees abroad, carry a backup card, and set up a roaming or eSIM plan.',
      domain: 'finance',
      priority: 'medium',
      authority: 'Bank / carrier',
      startOffsetDays: -14,
      dueOffsetDays: -3,
    },
    {
      id: 'trip.car_rental',
      title: 'Arrange the rental car',
      description:
        'Book ahead for better rates, get an International Driving Permit where required, and know what the rental insurance actually covers before declining or accepting it.',
      domain: 'travel',
      priority: 'medium',
      authority: 'Rental company / automobile club',
      startOffsetDays: -30,
      dueOffsetDays: -7,
      documents: ["Driver's licence", 'International Driving Permit'],
      dependsOn: ['trip.passports'],
    },
    {
      id: 'trip.work_prep',
      title: 'Hand over work and set your out-of-office',
      description:
        'Brief whoever covers for you, close what can be closed, and set expectations for what waits until you return.',
      domain: 'employment',
      priority: 'medium',
      authority: 'Employer',
      startOffsetDays: -7,
      dueOffsetDays: -1,
    },
    {
      id: 'trip.house_sitting',
      title: 'Arrange pet / house care and hold the mail',
      description: 'Book the sitter or boarding, share keys and vet contacts, pause deliveries and hold the mail for the dates away.',
      domain: 'housing',
      priority: 'high',
      authority: 'Sitter / postal service',
      startOffsetDays: -30,
      dueOffsetDays: -7,
    },
  ],
};

export const newPet: LifeEventTemplate = {
  id: 'new-pet',
  name: 'We got a pet',
  emoji: '🐶',
  category: 'leisure',
  featured: true,
  summary:
    'A new pet comes with a small legal identity of its own: registration, vaccinations, insurance and a vet relationship.',
  triggerPhrases: [
    'we got a dog',
    'we got a cat',
    'we got a pet',
    'i got a dog',
    'i got a cat',
    'adopted a dog',
    'adopted a cat',
    'adopting a pet',
    'getting a puppy',
    'got a puppy',
    'got a kitten',
  ],
  keywords: ['pet', 'dog', 'cat', 'puppy', 'kitten', 'adopted', 'adoption', 'vet'],
  questions: [
    { id: 'adoption_date', prompt: 'When does (did) the pet come home?', kind: 'date' },
    {
      id: 'needs_licence',
      prompt: 'Does your municipality require pet licensing (common for dogs)?',
      kind: 'boolean',
      gatesTasks: ['pet.licence'],
    },
    {
      id: 'first_pet',
      prompt: 'Is this your first pet?',
      kind: 'boolean',
      gatesTasks: ['pet.training'],
    },
    {
      id: 'travel_often',
      prompt: 'Do you travel away from home regularly?',
      kind: 'boolean',
      gatesTasks: ['pet.care_plan'],
    },
  ],
  tasks: [
    {
      id: 'pet.vet_registration',
      title: 'Register with a vet; first check-up and vaccinations',
      description: 'Establish the vet relationship in week one: health check, vaccination schedule and deworming/flea plan.',
      domain: 'health',
      priority: 'critical',
      authority: 'Veterinarian',
      startOffsetDays: 0,
      dueOffsetDays: 14,
      documents: ['Adoption / breeder papers', 'Vaccination record'],
    },
    {
      id: 'pet.microchip',
      title: 'Microchip and register your contact details',
      description: 'The chip only works if the registry has your current phone and address — register it and keep it updated.',
      domain: 'government',
      priority: 'high',
      authority: 'Vet / chip registry',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      dependsOn: ['pet.vet_registration'],
    },
    {
      id: 'pet.licence',
      title: 'Get the municipal pet licence',
      description: 'Dog licences are legally required in many municipalities, usually with proof of rabies vaccination.',
      domain: 'government',
      priority: 'high',
      authority: 'Municipality',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      documents: ['Vaccination certificate'],
      dependsOn: ['pet.vet_registration'],
    },
    {
      id: 'pet.insurance',
      title: 'Decide on pet insurance',
      description: 'Premiums are lowest and coverage broadest when the pet is young and pre-existing-condition-free — decide early, not after the first big bill.',
      domain: 'insurance',
      priority: 'medium',
      authority: 'Pet insurer',
      startOffsetDays: 0,
      dueOffsetDays: 45,
    },
    {
      id: 'pet.training',
      title: 'Set up training and the daily routine',
      description:
        'First-time owners underestimate the first months: basic training or classes, a consistent daily routine, and one set of house rules everyone follows.',
      domain: 'education',
      priority: 'high',
      authority: 'Trainer / classes',
      startOffsetDays: 0,
      dueOffsetDays: 45,
      dependsOn: ['pet.vet_registration'],
    },
    {
      id: 'pet.care_plan',
      title: 'Line up the away-from-home care plan',
      description:
        'Vet the sitters and boarding options before you need them, agree a backup carer, and write the care instructions once.',
      domain: 'housing',
      priority: 'medium',
      authority: 'Sitters / boarding',
      startOffsetDays: 14,
      dueOffsetDays: 90,
    },
    {
      id: 'pet.household',
      title: 'Check lease / building rules and pet-proof the home',
      description: 'Confirm the lease or condo bylaws allow the pet (and any deposits), and secure hazards before the pet finds them.',
      domain: 'housing',
      priority: 'medium',
      authority: 'Landlord / HOA',
      startOffsetDays: -7,
      dueOffsetDays: 7,
    },
  ],
};

export const homeRenovation: LifeEventTemplate = {
  id: 'home-renovation',
  name: "I'm renovating my home",
  emoji: '🔨',
  category: 'leisure',
  featured: true,
  summary:
    'Renovation is a construction project with your name on the permits: scope, contractors, municipal approval and insurance all before the first wall opens.',
  triggerPhrases: [
    'renovating my home',
    'renovating my house',
    'home renovation',
    'renovating the kitchen',
    'remodeling',
    'remodelling',
    'renovate my',
    'planning a renovation',
  ],
  keywords: ['renovation', 'renovating', 'remodel', 'remodeling', 'contractor', 'kitchen', 'bathroom', 'construction'],
  questions: [
    { id: 'start_date', prompt: 'When should work start?', kind: 'date' },
    {
      id: 'is_structural',
      prompt: 'Does it involve structural, electrical or plumbing changes?',
      kind: 'boolean',
      gatesTasks: ['reno.permits', 'reno.inspections'],
    },
    {
      id: 'hiring_contractor',
      prompt: 'Are you hiring a contractor?',
      kind: 'boolean',
      gatesTasks: ['reno.contractor'],
    },
    {
      id: 'moving_out_during',
      prompt: 'Will you move out during the work?',
      kind: 'boolean',
      gatesTasks: ['reno.temp_housing'],
    },
  ],
  tasks: [
    {
      id: 'reno.scope_budget',
      title: 'Fix the scope and budget (plus contingency)',
      description: 'Write down exactly what is and is not included, and add 15–20% contingency — every later document points back at this.',
      domain: 'finance',
      priority: 'critical',
      authority: '—',
      startOffsetDays: -60,
      dueOffsetDays: -45,
    },
    {
      id: 'reno.permits',
      title: 'Obtain building permits',
      description: 'Structural, electrical and plumbing work almost always needs municipal permits; unpermitted work resurfaces at sale time as your problem.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Municipality',
      startOffsetDays: -45,
      dueOffsetDays: -7,
      documents: ['Plans / drawings', 'Property documents'],
      dependsOn: ['reno.scope_budget'],
    },
    {
      id: 'reno.contractor',
      title: 'Contract a licensed, insured contractor',
      description: 'Verify licence and liability insurance, get the payment schedule tied to milestones in writing, and never pay large sums up front.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Contractor',
      startOffsetDays: -45,
      dueOffsetDays: -14,
      documents: ['Written contract', 'Licence + insurance certificates'],
      dependsOn: ['reno.scope_budget'],
    },
    {
      id: 'reno.insurance_notify',
      title: 'Notify your home insurer',
      description: 'Major work can void coverage if undisclosed; you may need a renovation rider, and the rebuilt value changes the policy after.',
      domain: 'insurance',
      priority: 'high',
      authority: 'Home insurer',
      startOffsetDays: -30,
      dueOffsetDays: -7,
    },
    {
      id: 'reno.financing',
      title: 'Arrange financing',
      description: 'Line of credit, renovation loan or savings — have the money confirmed before signing the contractor payment schedule.',
      domain: 'finance',
      priority: 'high',
      authority: 'Bank',
      startOffsetDays: -45,
      dueOffsetDays: -14,
      dependsOn: ['reno.scope_budget'],
    },
    {
      id: 'reno.temp_housing',
      title: 'Arrange temporary housing during the work',
      description:
        'Book housing matched to the (realistic, padded) schedule, and put the cost into the project budget where it belongs.',
      domain: 'housing',
      priority: 'high',
      authority: 'Short-term rentals',
      startOffsetDays: -21,
      dueOffsetDays: 0,
      dependsOn: ['reno.scope_budget'],
    },
    {
      id: 'reno.inspections',
      title: 'Schedule the required inspections',
      description: 'Permitted work is signed off in stages (rough-in, final); missing an inspection can mean opening finished walls.',
      domain: 'government',
      priority: 'high',
      authority: 'Municipal inspectors',
      startOffsetDays: 0,
      dueOffsetDays: 90,
      dependsOn: ['reno.permits'],
    },
  ],
};
