import { LifeEventTemplate } from '../types';

/** Milestone events: the big, usually once-per-life transitions. */

export const turned18: LifeEventTemplate = {
  id: 'turned-18',
  name: 'I turned 18',
  emoji: '🎂',
  category: 'milestone',
  featured: true,
  summary:
    'Legal adulthood switches you from "dependent" to "person the system deals with directly": voting, ID, banking, health privacy and your own credit file.',
  triggerPhrases: ['i turned 18', 'i just turned 18', 'turning 18', 'i am 18 now', 'became an adult', 'i turn 18'],
  keywords: ['18', 'eighteen', 'adulthood'],
  questions: [
    { id: 'birthday', prompt: 'When is (was) the 18th birthday?', kind: 'date' },
    {
      id: 'service_registration',
      prompt: 'Does your country require military / selective service registration?',
      kind: 'boolean',
      gatesTasks: ['a18.selective_service'],
    },
    {
      id: 'wants_licence',
      prompt: 'Do you drive, or plan to learn soon?',
      kind: 'boolean',
      gatesTasks: ['a18.drivers_licence'],
    },
    {
      id: 'heading_to_college',
      prompt: 'Are you heading to college / university?',
      kind: 'boolean',
      gatesTasks: ['a18.student_aid'],
    },
  ],
  tasks: [
    {
      id: 'a18.register_vote',
      title: 'Register to vote',
      description: 'You are now eligible — register so you are on the rolls before the next election deadline.',
      domain: 'government',
      priority: 'high',
      authority: 'Electoral authority',
      startOffsetDays: 0,
      dueOffsetDays: 60,
      documents: ['Proof of identity', 'Proof of address'],
    },
    {
      id: 'a18.adult_id',
      title: 'Get adult ID / passport in your own name',
      description: 'An adult photo ID (and ideally a passport) is the key that opens every other door on this list.',
      domain: 'government',
      priority: 'critical',
      authority: 'ID / passport office',
      startOffsetDays: 0,
      dueOffsetDays: 90,
      documents: ['Birth certificate', 'Proof of address'],
    },
    {
      id: 'a18.selective_service',
      title: 'Complete mandatory service registration',
      description: 'Where required (e.g. US Selective Service), registration deadlines are short and non-registration blocks student aid and government jobs.',
      domain: 'government',
      priority: 'critical',
      authority: 'Service registration agency',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
    {
      id: 'a18.own_bank',
      title: 'Convert to (or open) your own bank account',
      description: 'Move custodial/joint accounts into your own name and set up online banking you alone control.',
      domain: 'finance',
      priority: 'high',
      authority: 'Bank',
      startOffsetDays: 0,
      dueOffsetDays: 60,
      documents: ['Adult ID'],
      dependsOn: ['a18.adult_id'],
    },
    {
      id: 'a18.credit_start',
      title: 'Start building a credit history',
      description: 'A starter credit card or becoming an authorized user, paid in full monthly — future landlords and lenders read this file.',
      domain: 'finance',
      priority: 'medium',
      authority: 'Bank / card issuer',
      startOffsetDays: 30,
      dueOffsetDays: 180,
      dependsOn: ['a18.own_bank'],
    },
    {
      id: 'a18.drivers_licence',
      title: "Progress your driver's licence",
      description:
        'At 18 most graduated-licensing restrictions lift — check what changes, pass the theory test if you haven\'t, and book lessons.',
      domain: 'government',
      priority: 'medium',
      authority: 'Licensing authority',
      startOffsetDays: 0,
      dueOffsetDays: 180,
      dependsOn: ['a18.adult_id'],
    },
    {
      id: 'a18.student_aid',
      title: 'Prepare student aid applications',
      description:
        'Financial aid forms (FAFSA-style) are filed in your own name from 18, with deadlines that arrive earlier than admission decisions.',
      domain: 'education',
      priority: 'high',
      authority: 'Aid office',
      startOffsetDays: 0,
      dueOffsetDays: 120,
    },
    {
      id: 'a18.health_admin',
      title: 'Take over your health administration',
      description: 'At 18 parents lose automatic access to your records. Register with a doctor as an adult, know your insurance status, and consider a healthcare proxy.',
      domain: 'health',
      priority: 'medium',
      authority: 'Clinic / insurer',
      startOffsetDays: 0,
      dueOffsetDays: 120,
    },
  ],
};

export const graduatedCollege: LifeEventTemplate = {
  id: 'graduated-college',
  name: 'I graduated college',
  emoji: '🎓',
  category: 'milestone',
  featured: true,
  summary:
    'Graduation quietly starts several clocks: student loan grace periods, health coverage age-outs, and the move off university systems.',
  triggerPhrases: [
    'i graduated college',
    'i graduated',
    'graduating college',
    'graduating university',
    'finished university',
    'finished college',
    'got my degree',
    'i am graduating',
  ],
  keywords: ['graduated', 'graduation', 'college', 'university', 'degree', 'diploma', 'grad', 'graduate'],
  questions: [
    { id: 'grad_date', prompt: 'When is (was) graduation?', kind: 'date' },
    {
      id: 'has_loans',
      prompt: 'Do you have student loans?',
      kind: 'boolean',
      gatesTasks: ['grad.loan_inventory', 'grad.repayment_plan'],
    },
    {
      id: 'on_family_or_student_plan',
      prompt: 'Is your health coverage through the university or a parent?',
      kind: 'boolean',
      gatesTasks: ['grad.health_transition'],
    },
    {
      id: 'job_hunting',
      prompt: 'Are you job hunting now?',
      kind: 'boolean',
      gatesTasks: ['grad.career_setup'],
    },
    {
      id: 'moving_out',
      prompt: 'Are you moving out of student housing?',
      kind: 'boolean',
      gatesTasks: ['grad.move_out'],
    },
  ],
  tasks: [
    {
      id: 'grad.documents',
      title: 'Order official transcripts and diploma copies',
      description: 'Employers and grad schools will ask for them; ordering later as an alum is slower and pricier.',
      domain: 'education',
      priority: 'high',
      authority: 'Registrar',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
    {
      id: 'grad.loan_inventory',
      title: 'Inventory every student loan',
      description: 'List each loan, servicer, balance, rate, and exactly when its grace period ends — that date is the cliff this plan works back from.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Loan servicers',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
    {
      id: 'grad.repayment_plan',
      title: 'Choose a repayment plan before grace ends',
      description: 'Pick standard / income-driven / refinance before the grace period (typically 6 months) ends and the default plan picks you.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Loan servicers',
      startOffsetDays: 60,
      dueOffsetDays: 150,
      dependsOn: ['grad.loan_inventory'],
    },
    {
      id: 'grad.health_transition',
      title: 'Line up post-graduation health coverage',
      description: 'Student plans end with enrollment and parental plans age out — know your end date and have employer or marketplace coverage ready.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Insurer / marketplace',
      startOffsetDays: 0,
      dueOffsetDays: 60,
    },
    {
      id: 'grad.digital_migration',
      title: 'Migrate off university accounts',
      description: 'University email and cloud storage get deleted — move files, update logins that use the .edu address, and set forwarding while it lasts.',
      domain: 'education',
      priority: 'medium',
      authority: 'University IT',
      startOffsetDays: 0,
      dueOffsetDays: 90,
    },
    {
      id: 'grad.career_setup',
      title: 'Update résumé, profiles and references',
      description: 'Add the degree everywhere it counts and lock in references from professors while relationships are fresh.',
      domain: 'employment',
      priority: 'medium',
      authority: '—',
      startOffsetDays: 0,
      dueOffsetDays: 60,
    },
    {
      id: 'grad.move_out',
      title: 'Move out of student housing',
      description:
        'End-of-lease dates around graduation are hard deadlines — plan the move, arrange the next address, and recover deposits.',
      domain: 'housing',
      priority: 'high',
      authority: 'Housing office / landlord',
      startOffsetDays: -14,
      dueOffsetDays: 30,
    },
    {
      id: 'grad.tax_status',
      title: 'Check your tax situation changes',
      description: 'Dependency status, education credits for the final year, and student loan interest deductions all shift at graduation.',
      domain: 'tax',
      priority: 'medium',
      authority: 'Tax authority',
      startOffsetDays: 30,
      dueOffsetDays: 180,
    },
  ],
};

export const boughtHouse: LifeEventTemplate = {
  id: 'bought-house',
  name: 'I bought a house',
  emoji: '🏠',
  category: 'milestone',
  featured: true,
  summary:
    'Closing day is the middle, not the end: insurance, title, property tax, utilities and your estate documents all need to catch up with the deed.',
  triggerPhrases: [
    'i bought a house',
    'we bought a house',
    'buying a house',
    'bought a home',
    'buying a home',
    'closing on a house',
    'i am a homeowner',
    'bought an apartment',
    'bought a condo',
  ],
  keywords: ['bought', 'house', 'home', 'mortgage', 'closing', 'homeowner', 'condo', 'property'],
  questions: [
    { id: 'closing_date', prompt: 'When is (was) the closing date?', kind: 'date' },
    {
      id: 'first_home',
      prompt: 'Is this your first home?',
      kind: 'boolean',
      gatesTasks: ['house.first_time_benefits'],
    },
    {
      id: 'has_mortgage',
      prompt: 'Is there a mortgage?',
      kind: 'boolean',
      gatesTasks: ['house.mortgage_autopay', 'house.escrow_check'],
    },
    {
      id: 'leaving_previous_home',
      prompt: 'Are you leaving a rental or selling a previous home?',
      kind: 'boolean',
      gatesTasks: ['house.old_home'],
    },
    {
      id: 'renovating_first',
      prompt: 'Are you renovating before moving in?',
      kind: 'boolean',
      gatesTasks: ['house.reno_before'],
    },
  ],
  tasks: [
    {
      id: 'house.insurance',
      title: "Have homeowner's insurance active at closing",
      description: 'Lenders require proof of insurance before funding; coverage must start the day you own the risk.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Insurer',
      startOffsetDays: -21,
      dueOffsetDays: 0,
      documents: ['Purchase agreement', 'Property details'],
    },
    {
      id: 'house.title_deed',
      title: 'Confirm deed and title registration',
      description: 'Verify the deed was recorded with the land registry and store the title insurance policy with your key documents.',
      domain: 'legal',
      priority: 'high',
      authority: 'Land registry / title company',
      startOffsetDays: 0,
      dueOffsetDays: 45,
      documents: ['Closing documents'],
    },
    {
      id: 'house.property_tax',
      title: 'Set up the property tax account',
      description: 'Make sure the tax bill comes to you (or your escrow), and file any homestead/primary-residence exemption — deadlines for these are strict.',
      domain: 'tax',
      priority: 'high',
      authority: 'Municipality',
      startOffsetDays: 0,
      dueOffsetDays: 60,
    },
    {
      id: 'house.utilities',
      title: 'Transfer utilities into your name',
      description: 'Electricity, gas, water, waste and internet, effective on closing day.',
      domain: 'utilities',
      priority: 'critical',
      authority: 'Utility providers',
      startOffsetDays: -14,
      dueOffsetDays: 0,
    },
    {
      id: 'house.mortgage_autopay',
      title: 'Set up mortgage payments',
      description: 'Autopay from the account your salary lands in — a missed first payment is an expensive administrative accident.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Mortgage lender',
      startOffsetDays: 0,
      dueOffsetDays: 21,
    },
    {
      id: 'house.escrow_check',
      title: 'Verify escrow covers tax and insurance',
      description: 'Confirm what the lender escrows vs. what you pay directly, so nothing falls between the two.',
      domain: 'finance',
      priority: 'medium',
      authority: 'Mortgage lender',
      startOffsetDays: 21,
      dueOffsetDays: 90,
      dependsOn: ['house.mortgage_autopay'],
    },
    {
      id: 'house.first_time_benefits',
      title: 'Claim first-time buyer benefits',
      description: 'Many jurisdictions offer first-time buyer tax credits, land-transfer rebates or savings-account withdrawals — most must be claimed, not automatic.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax authority',
      startOffsetDays: 0,
      dueOffsetDays: 120,
    },
    {
      id: 'house.old_home',
      title: 'Wind down the previous home',
      description:
        'Give proper notice or coordinate the sale, plan the overlap period, and get deposits back or proceeds settled.',
      domain: 'housing',
      priority: 'high',
      authority: 'Landlord / agent',
      startOffsetDays: -30,
      dueOffsetDays: 30,
    },
    {
      id: 'house.reno_before',
      title: 'Renovate before moving in',
      description:
        'Work is far easier in an empty house — scope, quote and schedule it into the window between closing and move-in.',
      domain: 'housing',
      priority: 'medium',
      authority: 'Contractors',
      startOffsetDays: -14,
      dueOffsetDays: 60,
      dependsOn: ['house.insurance'],
    },
    {
      id: 'house.estate_update',
      title: 'Update your will and beneficiaries',
      description: 'A house is usually your largest asset the moment you own it — your estate documents should say what happens to it.',
      domain: 'legal',
      priority: 'medium',
      authority: 'Lawyer / notary',
      startOffsetDays: 30,
      dueOffsetDays: 180,
    },
  ],
};

export const gotDivorced: LifeEventTemplate = {
  id: 'got-divorced',
  name: 'I got divorced',
  emoji: '📄',
  category: 'milestone',
  featured: true,
  summary:
    'After the decree, every system that once knew you as a couple needs to be told individually: accounts, insurance, beneficiaries, taxes and names.',
  triggerPhrases: [
    'i got divorced',
    'we got divorced',
    'getting divorced',
    'getting a divorce',
    'my divorce',
    'we separated',
    'i am separated',
  ],
  keywords: ['divorce', 'divorced', 'separation', 'separated', 'ex'],
  questions: [
    { id: 'decree_date', prompt: 'When is (was) the divorce final?', kind: 'date' },
    {
      id: 'name_change',
      prompt: 'Are you changing your name back?',
      kind: 'boolean',
      gatesTasks: ['div.name_change'],
    },
    {
      id: 'has_children',
      prompt: 'Are children involved?',
      kind: 'boolean',
      gatesTasks: ['div.custody_support'],
    },
    {
      id: 'shared_home',
      prompt: 'Do you own a home together?',
      kind: 'boolean',
      gatesTasks: ['div.home_division'],
    },
  ],
  tasks: [
    {
      id: 'div.decree_copies',
      title: 'Obtain certified copies of the decree',
      description: 'Banks, registries and insurers each want to see a certified copy — order several.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Court',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
    {
      id: 'div.finances_split',
      title: 'Separate accounts, cards and debts',
      description: 'Close or retitle joint accounts, remove each other as authorized users, and split debts per the decree — joint debt hurts both credit files until it is formally moved.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Banks / lenders',
      startOffsetDays: 0,
      dueOffsetDays: 60,
      dependsOn: ['div.decree_copies'],
    },
    {
      id: 'div.beneficiaries',
      title: 'Update beneficiaries and emergency contacts',
      description: 'Life insurance, pensions and retirement accounts pay whoever the form says — in many places an ex-spouse designation survives divorce unless changed.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Insurers / pension / banks',
      startOffsetDays: 0,
      dueOffsetDays: 60,
    },
    {
      id: 'div.health_insurance',
      title: 'Sort health coverage for both households',
      description: 'Coverage through an ex-spouse usually ends with the decree; continuation windows (e.g. COBRA) are short.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Insurer / employer benefits',
      startOffsetDays: 0,
      dueOffsetDays: 60,
    },
    {
      id: 'div.tax_status',
      title: 'Update tax status and withholding',
      description: 'Filing status, dependents, and support payments all change; your withholding should change with them.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax authority / employer',
      startOffsetDays: 0,
      dueOffsetDays: 90,
    },
    {
      id: 'div.custody_support',
      title: 'File custody and support arrangements',
      description: 'Register the parenting plan and support orders with the relevant agencies so schools, doctors and payroll all follow the same document.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Court / support agency',
      startOffsetDays: 0,
      dueOffsetDays: 60,
      dependsOn: ['div.decree_copies'],
    },
    {
      id: 'div.name_change',
      title: 'Restore your previous name',
      description: 'The decree usually authorizes it: update core ID first (passport, licence, social/tax number), then banks and employer.',
      domain: 'government',
      priority: 'high',
      authority: 'ID authorities',
      startOffsetDays: 30,
      dueOffsetDays: 120,
      documents: ['Certified decree'],
      dependsOn: ['div.decree_copies'],
    },
    {
      id: 'div.home_division',
      title: 'Divide the shared home',
      description:
        'Valuation, then buyout or sale per the decree — and the title and mortgage must actually be retitled, or both of you stay liable.',
      domain: 'housing',
      priority: 'critical',
      authority: 'Lender / land registry',
      startOffsetDays: 0,
      dueOffsetDays: 120,
      documents: ['Decree', 'Property valuation', 'Mortgage statement'],
      dependsOn: ['div.decree_copies'],
    },
    {
      id: 'div.estate_docs',
      title: 'Rewrite will and powers of attorney',
      description: 'Old documents likely name your ex as heir, executor and medical proxy — replace them.',
      domain: 'legal',
      priority: 'high',
      authority: 'Lawyer / notary',
      startOffsetDays: 0,
      dueOffsetDays: 120,
    },
  ],
};

export const planningMarriage: LifeEventTemplate = {
  id: 'planning-wedding',
  name: "I'm planning my marriage",
  emoji: '👰',
  category: 'milestone',
  featured: true,
  summary:
    'A wedding is a legal act wrapped in an event production: the licence and officiant make it real, while venue, vendors and guests make it a day — each on its own timeline.',
  triggerPhrases: [
    'planning my marriage',
    'planning our marriage',
    'i am planning my marriage',
    'planning my wedding',
    'planning our wedding',
    'planning a wedding',
    'wedding planning',
    'i am getting married',
    'we are getting married',
  ],
  keywords: ['wedding', 'marriage', 'bride', 'groom', 'venue', 'fiance', 'fiancee', 'marry'],
  questions: [
    { id: 'wedding_date', prompt: 'When is the wedding?', kind: 'date' },
    {
      id: 'guest_size',
      prompt: 'Roughly how many guests?',
      kind: 'choice',
      choices: ['Under 30', '30–80', '80–150', '150+'],
    },
    {
      id: 'destination',
      prompt: 'Is it a destination wedding (guests travel)?',
      kind: 'boolean',
      gatesTasks: ['wed.destination'],
    },
    {
      id: 'considering_prenup',
      prompt: 'Are you considering a prenuptial agreement?',
      kind: 'boolean',
      gatesTasks: ['wed.prenup'],
    },
    {
      id: 'planning_honeymoon',
      prompt: 'Are you planning a honeymoon right after?',
      kind: 'boolean',
      gatesTasks: ['wed.honeymoon'],
    },
  ],
  tasks: [
    {
      id: 'wed.budget',
      title: 'Set the wedding budget and who pays',
      description:
        'The total, the contributions, and a tracker — every vendor conversation goes better when the number is already agreed.',
      domain: 'finance',
      priority: 'critical',
      authority: '—',
      startOffsetDays: -300,
      dueOffsetDays: -270,
      steps: ['Total budget agreed', 'Contributions agreed', 'Tracker set up'],
    },
    {
      id: 'wed.guest_list',
      title: 'Draft the guest list',
      description:
        'Headcount drives venue, catering and budget — draft it early and expect to defend it often.',
      domain: 'social',
      priority: 'critical',
      authority: '—',
      startOffsetDays: -300,
      dueOffsetDays: -260,
      steps: ['Both sides drafted', 'Headcount range fixed', 'Addresses collected'],
    },
    {
      id: 'wed.venue',
      title: 'Book the venue and lock the date',
      description:
        'Popular venues book 9–18 months out. Read the contract: deposit, cancellation, vendor restrictions, and what happens if it rains.',
      domain: 'social',
      priority: 'critical',
      authority: 'Venue',
      startOffsetDays: -280,
      dueOffsetDays: -220,
      documents: ['Venue contract'],
      dependsOn: ['wed.budget', 'wed.guest_list'],
      steps: ['Venues shortlisted & visited', 'Date confirmed', 'Contract signed', 'Deposit paid'],
    },
    {
      id: 'wed.officiant',
      title: 'Book the officiant and plan the ceremony',
      description:
        'Civil, religious or celebrant — each has its own requirements, and some require pre-marriage sessions or notice periods.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Officiant / registry',
      startOffsetDays: -240,
      dueOffsetDays: -180,
      dependsOn: ['wed.venue'],
      steps: ['Officiant booked', 'Ceremony requirements confirmed', 'Ceremony content agreed'],
    },
    {
      id: 'wed.licence',
      title: 'Get the marriage licence',
      description:
        'The legal core of the whole event. Licences have waiting periods and expiry windows (often 30–90 days), so this is timed, not early.',
      domain: 'government',
      priority: 'critical',
      authority: 'Civil registry / county clerk',
      startOffsetDays: -60,
      dueOffsetDays: -14,
      documents: ['IDs / birth certificates', 'Proof of any previous marriage ending'],
      dependsOn: ['wed.officiant'],
      steps: ['Requirements & validity window checked', 'Appointment booked', 'Licence obtained'],
    },
    {
      id: 'wed.vendors',
      title: 'Book photographer, catering, music and flowers',
      description:
        'The good ones are booked in order of scarcity: photographer first, then catering, music, flowers.',
      domain: 'social',
      priority: 'high',
      authority: 'Vendors',
      startOffsetDays: -240,
      dueOffsetDays: -120,
      dependsOn: ['wed.venue'],
      steps: ['Photographer booked', 'Catering booked', 'Music booked', 'Flowers ordered'],
    },
    {
      id: 'wed.attire',
      title: 'Sort attire and rings',
      description:
        'Made-to-measure attire needs months and multiple fittings; rings need sizing and engraving time.',
      domain: 'social',
      priority: 'high',
      authority: 'Retailers / tailors',
      startOffsetDays: -180,
      dueOffsetDays: -45,
      steps: ['Outfits chosen & ordered', 'Fittings booked', 'Rings bought'],
    },
    {
      id: 'wed.invitations',
      title: 'Send invitations and track RSVPs',
      description:
        'Send 8–12 weeks out (earlier for destination weddings); track RSVPs, dietary needs and plus-ones in one list.',
      domain: 'social',
      priority: 'high',
      authority: '—',
      startOffsetDays: -120,
      dueOffsetDays: -60,
      dependsOn: ['wed.guest_list', 'wed.venue'],
      steps: ['Invitations sent', 'RSVP tracker running', 'Dietary needs collected'],
    },
    {
      id: 'wed.destination',
      title: 'Arrange the destination logistics',
      description:
        'Local marriage rules (some countries require residency days or extra documents), guest travel info, and a room block near the venue.',
      domain: 'travel',
      priority: 'critical',
      authority: 'Local registry / hotels',
      startOffsetDays: -240,
      dueOffsetDays: -90,
      dependsOn: ['wed.venue'],
      steps: ['Local legal requirements confirmed', 'Room block arranged', 'Travel info sent to guests'],
    },
    {
      id: 'wed.prenup',
      title: 'Put the prenuptial agreement in place',
      description:
        'Each partner needs independent legal advice, and courts dislike agreements signed at the last minute — finish well before the wedding.',
      domain: 'legal',
      priority: 'high',
      authority: 'Lawyers (one each)',
      startOffsetDays: -150,
      dueOffsetDays: -45,
      steps: ['Both lawyers engaged', 'Disclosure exchanged', 'Agreement signed early'],
    },
    {
      id: 'wed.honeymoon',
      title: 'Plan the honeymoon and book time off',
      description:
        'Book leave with both employers, then flights and stays; check passports now if going abroad.',
      domain: 'travel',
      priority: 'medium',
      authority: 'Employers / airlines',
      startOffsetDays: -150,
      dueOffsetDays: -30,
      steps: ['Leave approved for both', 'Passports checked', 'Flights & stay booked'],
    },
    {
      id: 'wed.runsheet',
      title: 'Final confirmations and the day-of run sheet',
      description:
        'Reconfirm every vendor, finalize headcount with catering, and write the one-page timeline with contacts so the day runs without you managing it.',
      domain: 'social',
      priority: 'high',
      authority: '—',
      startOffsetDays: -21,
      dueOffsetDays: -3,
      dependsOn: ['wed.invitations', 'wed.vendors'],
      steps: ['All vendors reconfirmed', 'Final headcount given', 'Run sheet written & shared'],
    },
  ],
};

export const retired: LifeEventTemplate = {
  id: 'retired',
  name: 'I retired',
  emoji: '🌅',
  category: 'milestone',
  featured: true,
  summary:
    'Retirement swaps one paycheck for several income streams — pension, government benefits, savings — each with its own application, timing rules and tax treatment.',
  triggerPhrases: [
    'i retired',
    'i am retiring',
    "i'm retiring",
    'retiring next',
    'i want to retire',
    'planning my retirement',
  ],
  keywords: ['retire', 'retired', 'retirement', 'pension'],
  questions: [
    { id: 'retire_date', prompt: 'When is (was) the last working day?', kind: 'date' },
    {
      id: 'employer_plan',
      prompt: 'Do you have an employer retirement plan (401k / workplace pension)?',
      kind: 'boolean',
      gatesTasks: ['ret.employer_plan'],
    },
    {
      id: 'gov_health_eligible',
      prompt: 'Are you at the age for government health coverage (e.g. Medicare at 65)?',
      kind: 'boolean',
      gatesTasks: ['ret.gov_health'],
    },
    {
      id: 'working_parttime',
      prompt: 'Will you work part-time in retirement?',
      kind: 'boolean',
      gatesTasks: ['ret.parttime_tax'],
    },
  ],
  tasks: [
    {
      id: 'ret.employer_notice',
      title: 'Give notice and capture employer benefits',
      description: 'Agree the final date, unused leave payout, and what happens to workplace insurance — some benefits can convert to personal policies only within 30 days.',
      domain: 'employment',
      priority: 'critical',
      authority: 'Employer HR',
      startOffsetDays: -90,
      dueOffsetDays: -30,
    },
    {
      id: 'ret.gov_pension',
      title: 'Apply for state pension / social security',
      description: 'Applications are accepted months in advance and start dates change the monthly amount for life — decide the claiming age deliberately.',
      domain: 'government',
      priority: 'critical',
      authority: 'Pension / social security agency',
      startOffsetDays: -120,
      dueOffsetDays: -30,
      documents: ['ID', 'Work history / contribution record'],
    },
    {
      id: 'ret.employer_plan',
      title: 'Decide what happens to the employer plan',
      description: 'Leave it, roll it over, or start withdrawals — compare fees and options before the default happens to you.',
      domain: 'finance',
      priority: 'high',
      authority: 'Plan administrator',
      startOffsetDays: -60,
      dueOffsetDays: 60,
    },
    {
      id: 'ret.gov_health',
      title: 'Enroll in government health coverage',
      description: 'Initial enrollment windows (e.g. Medicare: 3 months either side of 65) carry lifelong late penalties if missed.',
      domain: 'health',
      priority: 'critical',
      authority: 'Health agency',
      startOffsetDays: -90,
      dueOffsetDays: 0,
    },
    {
      id: 'ret.income_plan',
      title: 'Build the withdrawal and budget plan',
      description: 'Which account pays for what, in which order, and how much per year — sequencing withdrawals badly is a pure tax loss.',
      domain: 'finance',
      priority: 'high',
      authority: 'Financial adviser (optional)',
      startOffsetDays: -60,
      dueOffsetDays: 30,
      dependsOn: ['ret.gov_pension'],
    },
    {
      id: 'ret.tax_withholding',
      title: 'Set tax withholding on retirement income',
      description: 'Pensions and withdrawals often withhold nothing by default, leaving a surprise bill — set withholding or instalments now.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax authority / payers',
      startOffsetDays: 0,
      dueOffsetDays: 90,
      dependsOn: ['ret.income_plan'],
    },
    {
      id: 'ret.parttime_tax',
      title: 'Check how part-time work affects benefits',
      description:
        'Earnings can claw back pension or benefit payments below certain ages and thresholds — know the limits before accepting work.',
      domain: 'tax',
      priority: 'high',
      authority: 'Pension agency / tax authority',
      startOffsetDays: 0,
      dueOffsetDays: 90,
      dependsOn: ['ret.gov_pension'],
    },
    {
      id: 'ret.estate_refresh',
      title: 'Refresh estate documents',
      description: 'Will, powers of attorney and beneficiary designations, updated for your retirement finances.',
      domain: 'legal',
      priority: 'medium',
      authority: 'Lawyer / notary',
      startOffsetDays: 0,
      dueOffsetDays: 180,
    },
  ],
};
