import { LifeEventTemplate } from '../types';

/**
 * "I moved." — a change of address fans out across a dozen institutions,
 * most of which have legal notification deadlines.
 */
export const moved: LifeEventTemplate = {
  id: 'moved',
  name: 'I moved',
  emoji: '📦',
  category: 'important',
  summary:
    'A change of address touches your licence, insurance, government records, banks, employer, utilities and tax records. This plan coordinates all of them.',
  triggerPhrases: [
    'i moved',
    'we moved',
    'i am moving',
    "i'm moving",
    'moved house',
    'changed address',
    'change of address',
    'new apartment',
    'new house',
    'relocated',
  ],
  keywords: ['move', 'moving', 'moved', 'address', 'relocate', 'relocation', 'apartment', 'house'],
  questions: [
    { id: 'move_date', prompt: 'When is (was) the move?', kind: 'date' },
    { id: 'new_address', prompt: 'What is the new address?', kind: 'text' },
    {
      id: 'crossed_state',
      prompt: 'Did you move to a different state/province?',
      kind: 'boolean',
      gatesTasks: ['moved.new_licence', 'moved.vehicle_reregister', 'moved.voter_reregister'],
    },
    {
      id: 'owns_vehicle',
      prompt: 'Do you own a vehicle?',
      kind: 'boolean',
      gatesTasks: ['moved.vehicle_address', 'moved.vehicle_reregister', 'moved.auto_insurance'],
    },
    {
      id: 'renting',
      prompt: 'Are you renting the new place?',
      kind: 'boolean',
      gatesTasks: ['moved.renters_insurance'],
    },
  ],
  tasks: [
    {
      id: 'moved.mail_forwarding',
      title: 'Set up mail forwarding',
      description:
        'File a change-of-address with the postal service so mail follows you while you update every institution individually. This is the safety net for anything you miss.',
      domain: 'government',
      priority: 'critical',
      authority: 'Postal service',
      startOffsetDays: -14,
      dueOffsetDays: 0,
      documents: ['Photo ID', 'Old and new address'],
    },
    {
      id: 'moved.licence_address',
      title: "Update driver's licence address",
      description:
        "Most jurisdictions legally require the address on your driver's licence to be updated within 10–30 days of moving.",
      domain: 'government',
      priority: 'critical',
      authority: 'DMV / licensing authority',
      startOffsetDays: 0,
      dueOffsetDays: 14,
      documents: ["Driver's licence", 'Proof of new address (lease or utility bill)'],
    },
    {
      id: 'moved.new_licence',
      title: "Get a new state/province driver's licence",
      description:
        'Moving across a state or provincial border usually means exchanging your licence for a local one within a legal deadline.',
      domain: 'government',
      priority: 'critical',
      authority: 'DMV / licensing authority',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      documents: ['Current licence', 'Proof of residence', 'Identity documents'],
      dependsOn: ['moved.mail_forwarding'],
    },
    {
      id: 'moved.voter_reregister',
      title: 'Re-register to vote',
      description: 'Voter registration is tied to your address; re-register in the new jurisdiction.',
      domain: 'government',
      priority: 'medium',
      authority: 'Electoral authority',
      startOffsetDays: 0,
      dueOffsetDays: 45,
      documents: ['Proof of new address'],
    },
    {
      id: 'moved.tax_address',
      title: 'Update address with the tax authority',
      description:
        'The tax authority sends refunds, assessments and legal notices to your registered address. Update it so nothing legally important goes missing.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax authority (IRS / CRA / HMRC…)',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      documents: ['Tax ID / SSN / SIN'],
    },
    {
      id: 'moved.employer',
      title: 'Notify your employer / payroll',
      description:
        'Payroll, tax withholding and benefits mailings depend on your address on file. A state/province change can also change your tax withholding.',
      domain: 'employment',
      priority: 'high',
      authority: 'Employer HR',
      startOffsetDays: -7,
      dueOffsetDays: 7,
    },
    {
      id: 'moved.banks',
      title: 'Update address at banks and card issuers',
      description:
        'Update every bank account, credit card and investment account. Statements and replacement cards go to the address on file.',
      domain: 'finance',
      priority: 'high',
      authority: 'Each bank / issuer',
      startOffsetDays: 0,
      dueOffsetDays: 14,
    },
    {
      id: 'moved.home_insurance',
      title: 'Move or replace home/contents insurance',
      description:
        'Your policy covers a specific address. Transfer or rewrite the policy effective on move day so there is no coverage gap.',
      domain: 'insurance',
      priority: 'critical',
      authority: 'Insurer',
      startOffsetDays: -21,
      dueOffsetDays: 0,
      documents: ['Current policy', 'New address details'],
    },
    {
      id: 'moved.renters_insurance',
      title: "Set up renter's insurance for the new place",
      description: "Many leases require proof of renter's insurance before key handover.",
      domain: 'insurance',
      priority: 'high',
      authority: 'Insurer',
      startOffsetDays: -14,
      dueOffsetDays: 0,
      documents: ['Lease agreement'],
    },
    {
      id: 'moved.auto_insurance',
      title: 'Update auto insurance address',
      description:
        'Premiums and coverage validity depend on where the vehicle is kept. Update the garaging address effective move day.',
      domain: 'insurance',
      priority: 'high',
      authority: 'Auto insurer',
      startOffsetDays: -7,
      dueOffsetDays: 7,
    },
    {
      id: 'moved.vehicle_address',
      title: 'Update vehicle registration address',
      description: 'Vehicle registration records must show your current address.',
      domain: 'government',
      priority: 'high',
      authority: 'Vehicle registry',
      startOffsetDays: 0,
      dueOffsetDays: 14,
      documents: ['Registration certificate'],
    },
    {
      id: 'moved.vehicle_reregister',
      title: 'Re-register vehicle in new state/province',
      description:
        'Crossing a state/provincial border usually requires re-registering the vehicle and may require an inspection.',
      domain: 'government',
      priority: 'high',
      authority: 'Vehicle registry',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      documents: ['Title / registration', 'Proof of insurance', 'Inspection certificate'],
      dependsOn: ['moved.auto_insurance'],
    },
    {
      id: 'moved.utilities_close',
      title: 'Close / transfer utilities at the old address',
      description:
        'Electricity, gas, water, internet: schedule final readings and account closure or transfer for move-out day so you stop paying for the old place.',
      domain: 'utilities',
      priority: 'high',
      authority: 'Each utility provider',
      startOffsetDays: -21,
      dueOffsetDays: 0,
    },
    {
      id: 'moved.utilities_open',
      title: 'Open utilities at the new address',
      description:
        'Arrange electricity, gas, water and internet to be active from day one; some providers need 2–3 weeks of lead time.',
      domain: 'utilities',
      priority: 'critical',
      authority: 'Each utility provider',
      startOffsetDays: -21,
      dueOffsetDays: 0,
    },
    {
      id: 'moved.health_records',
      title: 'Update health insurance and find new providers',
      description:
        'Update your address with your health insurer, and if you changed regions, check network coverage and transfer prescriptions and medical records.',
      domain: 'health',
      priority: 'medium',
      authority: 'Health insurer / clinics',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
    {
      id: 'moved.subscriptions',
      title: 'Update subscriptions and deliveries',
      description: 'Online shopping defaults, meal kits, gym membership, and any recurring deliveries.',
      domain: 'utilities',
      priority: 'low',
      authority: 'Various',
      startOffsetDays: 0,
      dueOffsetDays: 30,
    },
  ],
};
