import { LifeEventTemplate } from '../types';

export const newChild: LifeEventTemplate = {
  id: 'new-child',
  name: 'We had a baby',
  emoji: '👶',
  category: 'milestone',
  featured: true,
  summary:
    'A new child needs to exist administratively: birth registration, ID, health coverage, benefits, and updated taxes and beneficiaries.',
  triggerPhrases: ['we had a baby', 'i had a baby', 'new baby', 'my child was born', 'we are having a baby'],
  keywords: ['baby', 'child', 'born', 'birth', 'newborn', 'parental'],
  questions: [
    { id: 'birth_date', prompt: 'Date of birth (or due date)?', kind: 'date' },
    {
      id: 'taking_leave',
      prompt: 'Is a parent taking parental leave?',
      kind: 'boolean',
      gatesTasks: ['baby.leave'],
    },
  ],
  tasks: [
    {
      id: 'baby.birth_registration',
      title: 'Register the birth',
      description: 'File the birth registration — the legal root document for everything that follows. Deadlines are short (often 30 days).',
      domain: 'government',
      priority: 'critical',
      authority: 'Vital records office',
      startOffsetDays: 0,
      dueOffsetDays: 21,
    },
    {
      id: 'baby.ssn',
      title: 'Get the child a tax/social security number',
      description: 'Required for tax credits, benefits and opening savings accounts.',
      domain: 'government',
      priority: 'high',
      authority: 'Social security / tax authority',
      startOffsetDays: 7,
      dueOffsetDays: 60,
      dependsOn: ['baby.birth_registration'],
    },
    {
      id: 'baby.health_enrollment',
      title: 'Add the child to health coverage',
      description: 'Enrollment windows after birth are typically 30–60 days; missing them means waiting for open enrollment.',
      domain: 'health',
      priority: 'critical',
      authority: 'Health insurer / employer benefits',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      documents: ['Birth certificate'],
      dependsOn: ['baby.birth_registration'],
    },
    {
      id: 'baby.leave',
      title: 'File parental leave and benefits',
      description: 'Employer notification plus the government benefit claim, each with its own forms and timelines.',
      domain: 'employment',
      priority: 'critical',
      authority: 'Employer + benefits agency',
      startOffsetDays: -30,
      dueOffsetDays: 14,
    },
    {
      id: 'baby.child_benefits',
      title: 'Apply for child benefits / tax credits',
      description: 'Most jurisdictions have monthly child benefits that only pay from application date — apply early.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax / benefits authority',
      startOffsetDays: 7,
      dueOffsetDays: 60,
      dependsOn: ['baby.birth_registration'],
    },
    {
      id: 'baby.beneficiaries',
      title: 'Update wills, beneficiaries and guardianship',
      description: 'Name a guardian and update life insurance and pension beneficiaries.',
      domain: 'legal',
      priority: 'high',
      authority: 'Lawyer / insurers',
      startOffsetDays: 0,
      dueOffsetDays: 90,
    },
  ],
};
