import { LifeEventTemplate } from '../types';

/**
 * "I started a business." — registration, tax accounts, insurance, licences,
 * payroll, accounting and ongoing compliance, sequenced in the order the
 * institutions themselves require.
 */
export const startedBusiness: LifeEventTemplate = {
  id: 'started-business',
  name: 'I started a business',
  emoji: '🏢',
  category: 'important',
  summary:
    'Starting a business means satisfying half a dozen authorities in the right order: registration first, then tax accounts, then licences, insurance, payroll and accounting.',
  triggerPhrases: [
    'i started a business',
    'starting a business',
    'start a business',
    'open a company',
    'opened a company',
    'i am self employed now',
    'founded a startup',
    'incorporate',
    'register a business',
  ],
  keywords: [
    'business',
    'company',
    'startup',
    'incorporate',
    'incorporation',
    'llc',
    'freelance',
    'self-employed',
    'entrepreneur',
    'founder',
  ],
  questions: [
    { id: 'start_date', prompt: 'When do (did) you start operating?', kind: 'date' },
    { id: 'business_name', prompt: 'What is the business called?', kind: 'text' },
    {
      id: 'structure',
      prompt: 'What legal structure?',
      kind: 'choice',
      choices: ['Sole proprietorship', 'LLC / Ltd', 'Corporation', 'Partnership', 'Not sure yet'],
    },
    {
      id: 'has_employees',
      prompt: 'Will you hire employees in the first year?',
      kind: 'boolean',
      gatesTasks: ['biz.payroll', 'biz.workers_comp', 'biz.employer_accounts'],
    },
    {
      id: 'has_premises',
      prompt: 'Will you have physical premises (office, shop, workshop)?',
      kind: 'boolean',
      gatesTasks: ['biz.premises_licence', 'biz.premises_insurance'],
    },
  ],
  tasks: [
    {
      id: 'biz.name_check',
      title: 'Check and reserve the business name',
      description:
        'Search the corporate registry and trademark database before anything else — every later registration references this name.',
      domain: 'business',
      priority: 'critical',
      authority: 'Corporate registry',
      startOffsetDays: -30,
      dueOffsetDays: -21,
    },
    {
      id: 'biz.register',
      title: 'Register the business entity',
      description:
        'File the incorporation / registration with the corporate registry. This creates the legal entity every other account hangs off.',
      domain: 'business',
      priority: 'critical',
      authority: 'Corporate registry',
      startOffsetDays: -21,
      dueOffsetDays: -7,
      documents: ['Founder ID', 'Registered address', 'Articles / operating agreement'],
      dependsOn: ['biz.name_check'],
    },
    {
      id: 'biz.tax_id',
      title: 'Get a business tax ID',
      description:
        'Obtain the federal tax identifier (EIN / business number). Banks, payroll and tax filings all require it.',
      domain: 'tax',
      priority: 'critical',
      authority: 'Tax authority',
      startOffsetDays: -14,
      dueOffsetDays: 0,
      documents: ['Registration certificate'],
      dependsOn: ['biz.register'],
    },
    {
      id: 'biz.sales_tax',
      title: 'Register for sales tax / VAT / GST',
      description:
        'If you sell taxable goods or services, register for the applicable consumption tax account before your first sale, or as soon as you cross the threshold.',
      domain: 'tax',
      priority: 'high',
      authority: 'Tax authority',
      startOffsetDays: -14,
      dueOffsetDays: 14,
      dependsOn: ['biz.tax_id'],
    },
    {
      id: 'biz.bank_account',
      title: 'Open a business bank account',
      description:
        'Keep business and personal money separate from day one — commingling breaks liability protection and makes accounting miserable.',
      domain: 'finance',
      priority: 'critical',
      authority: 'Bank',
      startOffsetDays: -7,
      dueOffsetDays: 7,
      documents: ['Registration certificate', 'Tax ID', 'Founder ID'],
      dependsOn: ['biz.tax_id'],
    },
    {
      id: 'biz.licences',
      title: 'Get industry licences and permits',
      description:
        'Check federal, state/provincial and municipal requirements for your industry — food handling, trades, professional services and transport are all licensed.',
      domain: 'legal',
      priority: 'critical',
      authority: 'Licensing authorities',
      startOffsetDays: -30,
      dueOffsetDays: 0,
      dependsOn: ['biz.register'],
    },
    {
      id: 'biz.premises_licence',
      title: 'Get premises permits (zoning, occupancy, signage)',
      description: 'Physical premises need zoning clearance, an occupancy permit and often a signage permit.',
      domain: 'legal',
      priority: 'high',
      authority: 'Municipality',
      startOffsetDays: -30,
      dueOffsetDays: 0,
    },
    {
      id: 'biz.liability_insurance',
      title: 'Get general liability insurance',
      description:
        'Clients and landlords routinely require proof of liability coverage; get quotes early because underwriting can take weeks.',
      domain: 'insurance',
      priority: 'high',
      authority: 'Insurer / broker',
      startOffsetDays: -14,
      dueOffsetDays: 7,
    },
    {
      id: 'biz.premises_insurance',
      title: 'Insure the premises and contents',
      description: 'Property, contents and business-interruption coverage for the physical location.',
      domain: 'insurance',
      priority: 'high',
      authority: 'Insurer / broker',
      startOffsetDays: -14,
      dueOffsetDays: 0,
    },
    {
      id: 'biz.employer_accounts',
      title: 'Register as an employer',
      description:
        'Before the first hire: employer tax withholding account, unemployment insurance account, and any mandatory pension scheme registration.',
      domain: 'employment',
      priority: 'critical',
      authority: 'Tax & labour authorities',
      startOffsetDays: 0,
      dueOffsetDays: 30,
      dependsOn: ['biz.tax_id'],
    },
    {
      id: 'biz.payroll',
      title: 'Set up payroll',
      description:
        'Choose a payroll system, set pay schedules, and configure withholding and remittance so the first payday is compliant.',
      domain: 'employment',
      priority: 'high',
      authority: 'Payroll provider',
      startOffsetDays: 7,
      dueOffsetDays: 45,
      dependsOn: ['biz.employer_accounts', 'biz.bank_account'],
    },
    {
      id: 'biz.workers_comp',
      title: "Get workers' compensation coverage",
      description: "Mandatory in most jurisdictions from the first employee's first day.",
      domain: 'insurance',
      priority: 'critical',
      authority: "Workers' comp board / insurer",
      startOffsetDays: 0,
      dueOffsetDays: 30,
      dependsOn: ['biz.employer_accounts'],
    },
    {
      id: 'biz.accounting',
      title: 'Set up accounting and bookkeeping',
      description:
        'Pick accounting software or an accountant, set the chart of accounts, and connect the business bank account. Do this before transactions pile up.',
      domain: 'finance',
      priority: 'high',
      authority: 'Accountant / software',
      startOffsetDays: 0,
      dueOffsetDays: 21,
      dependsOn: ['biz.bank_account'],
    },
    {
      id: 'biz.compliance_calendar',
      title: 'Build the compliance calendar',
      description:
        'Map every recurring obligation — tax instalments, annual returns, licence renewals, payroll remittances — into a calendar with reminders. Missed filings are the #1 cause of penalties for new businesses.',
      domain: 'legal',
      priority: 'high',
      authority: 'Multiple',
      startOffsetDays: 14,
      dueOffsetDays: 45,
      dependsOn: ['biz.register', 'biz.tax_id'],
    },
  ],
};
