/*
 * Emission factors, in kg CO2-equivalent per unit of activity.
 *
 * Every activity has up to two components:
 *   - OPERATION  (`usePer` kg CO2e per unit, or `useKwh` kWh per unit which is
 *                 multiplied by the grid intensity setting) — the energy/fuel
 *                 consumed while doing the activity. For food this is zero:
 *                 cooking energy is logged separately (LPG stove, etc.).
 *   - EMBODIED   (`embPer` kg CO2e per unit) — manufacturing & supply chain,
 *                 amortised over the equipment's typical lifetime, or for food
 *                 the full farm-to-retail production footprint.
 *
 * `srcUse` / `srcEmb` reference SOURCES. `estUse` / `estEmb` mark values that
 * are derived estimates rather than published factors — the Data tab shows
 * this distinction to the user. Full assumptions live in SOURCES.md.
 *
 * `split` / `embSplit` are approximate shares of the CO2e by gas (GWP-100).
 */

const SOURCES = {
  owid_travel: {
    short: 'OWID / UK DEFRA',
    label: 'Our World in Data — “Carbon footprint of travel per kilometer” (UK DEFRA 2022 conversion factors)',
    url: 'https://ourworldindata.org/travel-carbon-footprint',
  },
  poore2018: {
    short: 'Poore & Nemecek 2018',
    label: 'Poore & Nemecek (2018), Science 360 — GHG emissions per kg of food, global averages via Our World in Data',
    url: 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  },
  ember: {
    short: 'Ember (via OWID)',
    label: 'Ember — carbon intensity of electricity generation, 2025 data via Our World in Data',
    url: 'https://ourworldindata.org/grapher/carbon-intensity-electricity',
  },
  icct_ivl: {
    short: 'ICCT / IVL',
    label: 'ICCT (Hall & Lutsey 2018) and IVL (2019) battery study, via Carbon Brief — vehicle & battery manufacturing',
    url: 'https://www.carbonbrief.org/factcheck-how-electric-vehicles-help-to-tackle-climate-change/',
  },
  iea_stream: {
    short: 'IEA 2020',
    label: 'IEA (Kamiya, 2020) — “The carbon footprint of streaming video”, network + data-centre per viewing hour',
    url: 'https://www.iea.org/commentaries/the-carbon-footprint-of-streaming-video-fact-checking-the-headlines',
  },
  defra_fuel: {
    short: 'UK DEFRA',
    label: 'UK DEFRA/DESNZ GHG conversion factors — fuels and waste disposal',
    url: 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
  },
  lca_est: {
    short: 'LCA estimate',
    label: 'Derived estimate from manufacturer environmental reports & LCA literature — assumptions in SOURCES.md',
    url: 'SOURCES.md',
  },
  derived: {
    short: 'derived',
    label: 'Derived from the cited per-kg data using the stated serving size',
    url: 'SOURCES.md',
  },
};

const GAS_SPLITS = {
  electricity: { co2: 0.985, ch4: 0.005, n2o: 0.010 },
  fuel:        { co2: 0.960, ch4: 0.010, n2o: 0.030 },
  lpg:         { co2: 0.990, ch4: 0.005, n2o: 0.005 },
  industry:    { co2: 0.900, ch4: 0.070, n2o: 0.030 },
  ruminant:    { co2: 0.300, ch4: 0.550, n2o: 0.150 },
  pork:        { co2: 0.500, ch4: 0.250, n2o: 0.250 },
  poultry:     { co2: 0.600, ch4: 0.150, n2o: 0.250 },
  plant:       { co2: 0.550, ch4: 0.200, n2o: 0.250 },
  rice:        { co2: 0.250, ch4: 0.700, n2o: 0.050 },
  dairy:       { co2: 0.350, ch4: 0.500, n2o: 0.150 },
  waste:       { co2: 0.100, ch4: 0.850, n2o: 0.050 },
};

/* Categorical palette: validated slot order (see dashboard charts). */
const CATEGORIES = [
  { id: 'transport', label: 'Transport',        icon: '🚗', colorLight: '#2a78d6', colorDark: '#3987e5' },
  { id: 'food',      label: 'Food & drink',     icon: '🍛', colorLight: '#1baf7a', colorDark: '#199e70' },
  { id: 'home',      label: 'Home appliances',  icon: '🔌', colorLight: '#eda100', colorDark: '#c98500' },
  { id: 'water',     label: 'Cooking & water',  icon: '🚿', colorLight: '#008300', colorDark: '#008300' },
  { id: 'other',     label: 'Other',            icon: '📦', colorLight: '#4a3aa7', colorDark: '#9085e9' },
];

const ACTIVITIES = [
  /* ---------- Transport (per passenger-km) ---------- */
  { id: 'car_petrol', cat: 'transport', label: 'Car — petrol', unit: 'km',
    usePer: 0.170, srcUse: 'owid_travel',
    embPer: 0.030, srcEmb: 'icct_ivl', estEmb: true,
    embNote: '≈6 t CO₂e to build a mid-size car ÷ 200,000 km lifetime',
    split: 'fuel' },
  { id: 'car_diesel', cat: 'transport', label: 'Car — diesel', unit: 'km',
    usePer: 0.171, srcUse: 'owid_travel',
    embPer: 0.030, srcEmb: 'icct_ivl', estEmb: true,
    embNote: '≈6 t CO₂e to build a mid-size car ÷ 200,000 km lifetime',
    split: 'fuel' },
  { id: 'car_ev', cat: 'transport', label: 'Car — electric', unit: 'km',
    useKwh: 0.17, srcUse: 'lca_est', estUse: true,
    embPer: 0.050, srcEmb: 'icct_ivl', estEmb: true,
    embNote: '≈6 t car + ≈4 t battery (50 kWh × ~85 kg/kWh, IVL 2019) ÷ 200,000 km',
    split: 'electricity' },
  { id: 'motorbike', cat: 'transport', label: 'Motorbike / scooter', unit: 'km',
    usePer: 0.114, srcUse: 'owid_travel',
    embPer: 0.012, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈1.2 t CO₂e to build ÷ 100,000 km lifetime',
    split: 'fuel' },
  { id: 'auto', cat: 'transport', label: 'Auto-rickshaw / tuk-tuk', unit: 'km',
    usePer: 0.065, srcUse: 'lca_est', estUse: true,
    embPer: 0.008, srcEmb: 'lca_est', estEmb: true,
    embNote: 'small vehicle amortised over high lifetime km, shared by passengers',
    split: 'fuel' },
  { id: 'bus', cat: 'transport', label: 'City bus', unit: 'km',
    usePer: 0.097, srcUse: 'owid_travel',
    embPer: 0.006, srcEmb: 'lca_est', estEmb: true,
    embNote: 'vehicle manufacturing spread over ~1 M km and all passengers',
    split: 'fuel' },
  { id: 'metro', cat: 'transport', label: 'Metro / local train', unit: 'km',
    usePer: 0.028, srcUse: 'owid_travel',
    embPer: 0.004, srcEmb: 'lca_est', estEmb: true,
    embNote: 'rolling-stock manufacturing per passenger-km (excl. infrastructure)',
    split: 'electricity' },
  { id: 'train', cat: 'transport', label: 'Intercity train', unit: 'km',
    usePer: 0.035, srcUse: 'owid_travel',
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: 'rolling-stock manufacturing per passenger-km (excl. infrastructure)',
    split: 'fuel' },
  { id: 'flight_dom', cat: 'transport', label: 'Flight — domestic', unit: 'km',
    usePer: 0.246, srcUse: 'owid_travel',
    embPer: 0.002, srcEmb: 'lca_est', estEmb: true,
    embNote: 'aircraft manufacturing is small per passenger-km over ~25-year service',
    split: 'fuel' },
  { id: 'flight_int', cat: 'transport', label: 'Flight — long haul', unit: 'km',
    usePer: 0.148, srcUse: 'owid_travel',
    embPer: 0.002, srcEmb: 'lca_est', estEmb: true,
    embNote: 'aircraft manufacturing is small per passenger-km over ~25-year service',
    split: 'fuel' },
  { id: 'cycle', cat: 'transport', label: 'Bicycle', unit: 'km',
    usePer: 0, srcUse: 'owid_travel',
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈150 kg CO₂e to build a bicycle ÷ ~30,000 km lifetime',
    split: 'fuel' },
  { id: 'walk', cat: 'transport', label: 'Walking', unit: 'km',
    usePer: 0, srcUse: 'owid_travel', split: 'fuel' },

  /* ---------- Food & drink (production = embodied; cooking logged separately) ---------- */
  { id: 'meal_beef', cat: 'food', label: 'Meal with beef', unit: 'meals',
    embPer: 12.44, srcEmb: 'poore2018',
    embNote: '125 g beef (beef herd, global avg 99.5 kg CO₂e/kg incl. land use)',
    split: 'ruminant' },
  { id: 'meal_lamb', cat: 'food', label: 'Meal with lamb / mutton', unit: 'meals',
    embPer: 4.97, srcEmb: 'poore2018',
    embNote: '125 g lamb/mutton (39.7 kg CO₂e/kg)',
    split: 'ruminant' },
  { id: 'meal_pork', cat: 'food', label: 'Meal with pork', unit: 'meals',
    embPer: 1.54, srcEmb: 'poore2018',
    embNote: '125 g pig meat (12.3 kg CO₂e/kg)',
    split: 'pork' },
  { id: 'meal_chicken', cat: 'food', label: 'Meal with chicken', unit: 'meals',
    embPer: 1.23, srcEmb: 'poore2018',
    embNote: '125 g poultry (9.9 kg CO₂e/kg)',
    split: 'poultry' },
  { id: 'meal_fish', cat: 'food', label: 'Meal with fish (farmed)', unit: 'meals',
    embPer: 1.70, srcEmb: 'poore2018',
    embNote: '125 g farmed fish (13.6 kg CO₂e/kg)',
    split: 'poultry' },
  { id: 'meal_egg', cat: 'food', label: 'Egg dish (2 eggs)', unit: 'servings',
    embPer: 0.56, srcEmb: 'poore2018',
    embNote: '120 g eggs (4.7 kg CO₂e/kg)',
    split: 'poultry' },
  { id: 'meal_veg', cat: 'food', label: 'Vegetarian meal', unit: 'meals',
    embPer: 1.0, srcEmb: 'derived', estEmb: true,
    embNote: 'composite: grains + pulses + vegetables + some dairy (see SOURCES.md)',
    split: 'plant' },
  { id: 'meal_vegan', cat: 'food', label: 'Vegan meal', unit: 'meals',
    embPer: 0.7, srcEmb: 'derived', estEmb: true,
    embNote: 'composite: grains + pulses + vegetables (see SOURCES.md)',
    split: 'plant' },
  { id: 'rice', cat: 'food', label: 'Rice (1 serving)', unit: 'servings',
    embPer: 0.33, srcEmb: 'poore2018',
    embNote: '75 g dry rice (4.45 kg CO₂e/kg) — methane from flooded paddies',
    split: 'rice' },
  { id: 'milk', cat: 'food', label: 'Milk (1 glass, 250 ml)', unit: 'glasses',
    embPer: 0.79, srcEmb: 'poore2018',
    embNote: '250 ml dairy milk (3.15 kg CO₂e/kg)',
    split: 'dairy' },
  { id: 'cheese', cat: 'food', label: 'Cheese / paneer (30 g)', unit: 'servings',
    embPer: 0.72, srcEmb: 'poore2018',
    embNote: '30 g cheese (23.9 kg CO₂e/kg)',
    split: 'dairy' },
  { id: 'tofu', cat: 'food', label: 'Tofu (100 g)', unit: 'servings',
    embPer: 0.32, srcEmb: 'poore2018',
    embNote: '100 g tofu (3.16 kg CO₂e/kg)',
    split: 'plant' },
  { id: 'coffee', cat: 'food', label: 'Coffee (1 cup)', unit: 'cups',
    embPer: 0.34, srcEmb: 'poore2018',
    embNote: '12 g beans (28.5 kg CO₂e/kg), black — add milk separately',
    split: 'plant' },
  { id: 'tea', cat: 'food', label: 'Tea (1 cup)', unit: 'cups',
    embPer: 0.03, srcEmb: 'derived', estEmb: true,
    embNote: '2 g leaves — small; milk logged separately',
    split: 'plant' },
  { id: 'chocolate', cat: 'food', label: 'Dark chocolate (20 g)', unit: 'servings',
    embPer: 0.93, srcEmb: 'poore2018',
    embNote: '20 g dark chocolate (46.7 kg CO₂e/kg incl. land use)',
    split: 'plant' },

  /* ---------- Home appliances (operation = kWh × grid; embodied = mfg amortised) ---------- */
  { id: 'ac', cat: 'home', label: 'Air conditioner (1.5 T split)', unit: 'hours',
    useKwh: 1.50, srcUse: 'lca_est', estUse: true,
    embPer: 0.033, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈500 kg CO₂e to make ÷ 15,000 lifetime hours (excl. refrigerant leaks)',
    split: 'electricity' },
  { id: 'fan', cat: 'home', label: 'Ceiling fan', unit: 'hours',
    useKwh: 0.075, srcUse: 'lca_est', estUse: true,
    embPer: 0.001, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈35 kg CO₂e to make ÷ ~37,000 lifetime hours',
    split: 'electricity' },
  { id: 'heater', cat: 'home', label: 'Space heater', unit: 'hours',
    useKwh: 1.80, srcUse: 'lca_est', estUse: true,
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈50 kg CO₂e to make ÷ ~10,000 lifetime hours',
    split: 'electricity' },
  { id: 'fridge', cat: 'home', label: 'Refrigerator', unit: 'hours',
    useKwh: 0.06, srcUse: 'lca_est', estUse: true,
    embPer: 0.004, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈400 kg CO₂e to make ÷ 12 years always-on (~105,000 h)',
    split: 'electricity' },
  { id: 'tv', cat: 'home', label: 'Television (43″ LED)', unit: 'hours',
    useKwh: 0.10, srcUse: 'lca_est', estUse: true,
    embPer: 0.024, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈300 kg CO₂e to make ÷ ~12,500 viewing hours (7 yr)',
    split: 'electricity' },
  { id: 'desktop', cat: 'home', label: 'Desktop computer', unit: 'hours',
    useKwh: 0.15, srcUse: 'lca_est', estUse: true,
    embPer: 0.030, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈400 kg CO₂e (PC + monitor) ÷ ~13,000 hours (6 yr)',
    split: 'electricity' },
  { id: 'laptop', cat: 'home', label: 'Laptop / tablet', unit: 'hours',
    useKwh: 0.05, srcUse: 'lca_est', estUse: true,
    embPer: 0.020, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈200 kg CO₂e to make (manufacturer PCF) ÷ ~10,000 hours (5 yr)',
    split: 'electricity' },
  { id: 'lights', cat: 'home', label: 'Room lighting (4 LED bulbs)', unit: 'hours',
    useKwh: 0.04, srcUse: 'lca_est', estUse: true,
    embPer: 0.001, srcEmb: 'lca_est', estEmb: true,
    embNote: 'LED bulb manufacturing is small per lumen-hour',
    split: 'electricity' },
  { id: 'washer', cat: 'home', label: 'Washing machine', unit: 'loads',
    useKwh: 0.80, srcUse: 'lca_est', estUse: true,
    embPer: 0.16, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈350 kg CO₂e to make ÷ ~2,200 lifetime loads (10 yr)',
    split: 'electricity' },
  { id: 'iron', cat: 'home', label: 'Clothes iron', unit: 'hours',
    useKwh: 1.10, srcUse: 'lca_est', estUse: true,
    embPer: 0.020, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈20 kg CO₂e to make ÷ ~1,000 lifetime hours',
    split: 'electricity' },
  { id: 'microwave', cat: 'home', label: 'Microwave oven', unit: 'hours',
    useKwh: 1.20, srcUse: 'lca_est', estUse: true,
    embPer: 0.050, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈100 kg CO₂e to make ÷ ~2,000 lifetime hours',
    split: 'electricity' },
  { id: 'kettle', cat: 'home', label: 'Electric kettle', unit: 'boils',
    useKwh: 0.11, srcUse: 'lca_est', estUse: true,
    embPer: 0.008, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈15 kg CO₂e to make ÷ ~2,000 boils',
    split: 'electricity' },
  { id: 'phone', cat: 'home', label: 'Phone charging', unit: 'charges',
    useKwh: 0.015, srcUse: 'lca_est', estUse: true,
    embPer: 0.050, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈55 kg CO₂e to make a phone (manufacturer PCF) ÷ ~1,100 charges (3 yr)',
    split: 'electricity' },

  /* ---------- Cooking & water ---------- */
  { id: 'lpg', cat: 'water', label: 'LPG stove cooking', unit: 'hours',
    usePer: 0.50, srcUse: 'defra_fuel', estUse: true,
    embPer: 0.010, srcEmb: 'lca_est', estEmb: true,
    embNote: 'stove + cylinder manufacturing amortised',
    split: 'lpg' },
  { id: 'geyser', cat: 'water', label: 'Electric water heater (geyser)', unit: 'hours',
    useKwh: 2.0, srcUse: 'lca_est', estUse: true,
    embPer: 0.010, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈100 kg CO₂e to make ÷ ~10,000 lifetime hours',
    split: 'electricity' },
  { id: 'shower_hot', cat: 'water', label: 'Hot shower (10 min)', unit: 'showers',
    useKwh: 0.5, srcUse: 'lca_est', estUse: true,
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: 'water-heater share per shower',
    split: 'electricity' },
  { id: 'shower_cold', cat: 'water', label: 'Cold shower', unit: 'showers',
    usePer: 0.005, srcUse: 'lca_est', estUse: true,
    embPer: 0.002, srcEmb: 'lca_est', estEmb: true,
    embNote: 'water pumping & treatment only',
    split: 'electricity' },

  /* ---------- Other ---------- */
  { id: 'stream', cat: 'other', label: 'Video streaming (network only)', unit: 'hours',
    usePer: 0.036, srcUse: 'iea_stream',
    embNote: 'data centres + network transmission; log your TV/laptop hours separately for the device',
    split: 'electricity' },
  { id: 'waste', cat: 'other', label: 'Mixed waste to landfill', unit: 'kg',
    usePer: 0.50, srcUse: 'defra_fuel', estUse: true,
    embNote: 'methane from decomposing organic waste in landfill',
    split: 'waste' },
  { id: 'shopping', cat: 'other', label: 'Online order delivered', unit: 'parcels',
    usePer: 0.50, srcUse: 'lca_est', estUse: true,
    embNote: 'last-mile delivery + packaging; the product itself is not included',
    split: 'fuel' },
];

/* Grid carbon intensity, kg CO2 per kWh (Ember via OWID, 2025; world: Ember GER 2025 for 2024). */
const GRID_PRESETS = [
  { id: 'india',  label: 'India (0.67)',           value: 0.67 },
  { id: 'world',  label: 'World average (0.47)',   value: 0.47 },
  { id: 'us',     label: 'United States (0.38)',   value: 0.38 },
  { id: 'uk',     label: 'United Kingdom (0.22)',  value: 0.22 },
  { id: 'eu',     label: 'European Union (0.21)',  value: 0.21 },
  { id: 'renew',  label: 'Mostly renewables (0.05)', value: 0.05 },
  { id: 'custom', label: 'Custom…',                value: null },
];

/* Daily benchmarks in kg CO2e per person per day. */
const BENCHMARKS = {
  sustainable: 5.5,   // ~2 t CO2e/yr — widely used Paris-aligned personal target
  worldAvg:    12.9,  // ~4.7 t fossil CO2 per capita (Global Carbon Budget) / 365
};

/* Comfortable-but-frugal daily baselines for the minimal-usage guide.
 * qty = suggested units/day; note = the habit that gets you there. */
const MINIMAL_BASELINES = {
  ac:        { qty: 4,    note: 'Run it at 26 °C for the hottest hours only; a fan covers the rest.' },
  heater:    { qty: 2,    note: 'Heat the room you are in, layer up, and switch off overnight.' },
  fan:       { qty: 10,   note: 'Fans are cheap to run — prefer them over AC whenever bearable.' },
  geyser:    { qty: 0.25, note: '15 minutes heats enough water for one person’s bath.' },
  tv:        { qty: 2,    note: 'Switch off at the wall — standby still draws power.' },
  desktop:   { qty: 8,    note: 'Enable sleep mode; a laptop uses about a third of the power.' },
  lights:    { qty: 5,    note: 'Daylight first; switch rooms off as you leave them.' },
  iron:      { qty: 0.25, note: 'Iron clothes in one weekly batch instead of daily.' },
  microwave: { qty: 0.3,  note: 'Fine as-is — microwaving is usually the efficient choice.' },
  stream:    { qty: 2,    note: 'Stream over Wi-Fi at 720p on small screens; download repeats.' },
  shower_hot:{ qty: 1,    note: 'One hot shower a day; shorter and cooler both help.' },
};
