/*
 * Emission factors, in kg CO2-equivalent per unit of activity.
 *
 * Every activity has up to two components:
 *   - OPERATION  (`usePer` kg CO2e per unit, or `useKwh` kWh per unit which is
 *                 multiplied by the grid intensity setting) — the energy/fuel
 *                 consumed while doing the activity. For food this is zero:
 *                 cooking energy is logged separately (LPG stove, etc.).
 *   - EMBODIED   (`embPer` kg CO2e per unit) — manufacturing & supply chain,
 *                 amortised over the equipment's typical lifetime, or for food
 *                 the full farm-to-retail production footprint.
 *
 * `srcUse` / `srcEmb` reference SOURCES. `estUse` / `estEmb` mark values that
 * are derived estimates rather than published factors — the Data tab shows
 * this distinction to the user. Full assumptions live in SOURCES.md.
 *
 * `split` / `embSplit` are approximate shares of the CO2e by gas (GWP-100).
 */

const SOURCES = {
  owid_travel: {
    short: 'OWID / UK DEFRA',
    label: 'Our World in Data — “Carbon footprint of travel per kilometer” (UK DEFRA 2022 conversion factors)',
    url: 'https://ourworldindata.org/travel-carbon-footprint',
  },
  poore2018: {
    short: 'Poore & Nemecek 2018',
    label: 'Poore & Nemecek (2018), Science 360 — GHG emissions per kg of food, global averages via Our World in Data',
    url: 'https://ourworldindata.org/grapher/ghg-per-kg-poore',
  },
  ember: {
    short: 'Ember (via OWID)',
    label: 'Ember — carbon intensity of electricity generation, 2025 data via Our World in Data',
    url: 'https://ourworldindata.org/grapher/carbon-intensity-electricity',
  },
  icct_ivl: {
    short: 'ICCT / IVL',
    label: 'ICCT (Hall & Lutsey 2018) and IVL (2019) battery study, via Carbon Brief — vehicle & battery manufacturing',
    url: 'https://www.carbonbrief.org/factcheck-how-electric-vehicles-help-to-tackle-climate-change/',
  },
  iea_stream: {
    short: 'IEA 2020',
    label: 'IEA (Kamiya, 2020) — “The carbon footprint of streaming video”, network + data-centre per viewing hour',
    url: 'https://www.iea.org/commentaries/the-carbon-footprint-of-streaming-video-fact-checking-the-headlines',
  },
  defra_fuel: {
    short: 'UK DEFRA',
    label: 'UK DEFRA/DESNZ GHG conversion factors — fuels and waste disposal',
    url: 'https://www.gov.uk/government/collections/government-conversion-factors-for-company-reporting',
  },
  eccc_nir: {
    short: 'ECCC NIR (approx.)',
    label: 'Environment and Climate Change Canada, National Inventory Report — provincial electricity intensities (approximate values)',
    url: 'https://www.canada.ca/en/environment-climate-change/services/climate-change/greenhouse-gas-emissions/inventory.html',
  },
  epa_egrid: {
    short: 'EPA eGRID (approx.)',
    label: 'US EPA eGRID 2022 — state electricity intensities (approximate values)',
    url: 'https://www.epa.gov/egrid',
  },
  lca_est: {
    short: 'LCA estimate',
    label: 'Derived estimate from manufacturer environmental reports & LCA literature — assumptions in SOURCES.md',
    url: 'SOURCES.md',
  },
  derived: {
    short: 'derived',
    label: 'Derived from the cited per-kg data using the stated serving size',
    url: 'SOURCES.md',
  },
};

const GAS_SPLITS = {
  electricity: { co2: 0.985, ch4: 0.005, n2o: 0.010 },
  fuel:        { co2: 0.960, ch4: 0.010, n2o: 0.030 },
  lpg:         { co2: 0.990, ch4: 0.005, n2o: 0.005 },
  industry:    { co2: 0.900, ch4: 0.070, n2o: 0.030 },
  ruminant:    { co2: 0.300, ch4: 0.550, n2o: 0.150 },
  pork:        { co2: 0.500, ch4: 0.250, n2o: 0.250 },
  poultry:     { co2: 0.600, ch4: 0.150, n2o: 0.250 },
  plant:       { co2: 0.550, ch4: 0.200, n2o: 0.250 },
  rice:        { co2: 0.250, ch4: 0.700, n2o: 0.050 },
  dairy:       { co2: 0.350, ch4: 0.500, n2o: 0.150 },
  waste:       { co2: 0.100, ch4: 0.850, n2o: 0.050 },
};

/* Categorical palette: validated slot order (see dashboard charts). */
const CATEGORIES = [
  { id: 'transport', label: 'Transport',        icon: '🚗', colorLight: '#2a78d6', colorDark: '#3987e5' },
  { id: 'food',      label: 'Food & drink',     icon: '🍛', colorLight: '#1baf7a', colorDark: '#199e70' },
  { id: 'home',      label: 'Home appliances',  icon: '🔌', colorLight: '#eda100', colorDark: '#c98500' },
  { id: 'water',     label: 'Cooking, water & heating', icon: '🚿', colorLight: '#008300', colorDark: '#008300' },
  { id: 'other',     label: 'Other',            icon: '📦', colorLight: '#4a3aa7', colorDark: '#9085e9' },
];

const ACTIVITIES = [
  /* ---------- Transport (per passenger-km) ---------- */
  { id: 'car_petrol', cat: 'transport', label: 'Car — petrol', unit: 'km',
    usePer: 0.170, srcUse: 'owid_travel',
    embPer: 0.030, srcEmb: 'icct_ivl', estEmb: true,
    embNote: '≈6 t CO₂e to build a mid-size car ÷ 200,000 km lifetime',
    split: 'fuel' },
  { id: 'car_diesel', cat: 'transport', label: 'Car — diesel', unit: 'km',
    usePer: 0.171, srcUse: 'owid_travel',
    embPer: 0.030, srcEmb: 'icct_ivl', estEmb: true,
    embNote: '≈6 t CO₂e to build a mid-size car ÷ 200,000 km lifetime',
    split: 'fuel' },
  { id: 'car_ev', cat: 'transport', label: 'Car — electric', unit: 'km',
    useKwh: 0.17, srcUse: 'lca_est', estUse: true,
    embPer: 0.050, srcEmb: 'icct_ivl', estEmb: true,
    embNote: '≈6 t car + ≈4 t battery (50 kWh × ~85 kg/kWh, IVL 2019) ÷ 200,000 km',
    split: 'electricity' },
  { id: 'motorbike', cat: 'transport', label: 'Motorbike / scooter', unit: 'km',
    usePer: 0.114, srcUse: 'owid_travel',
    embPer: 0.012, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈1.2 t CO₂e to build ÷ 100,000 km lifetime',
    split: 'fuel' },
  { id: 'bus', cat: 'transport', label: 'City bus', unit: 'km',
    usePer: 0.097, srcUse: 'owid_travel',
    embPer: 0.006, srcEmb: 'lca_est', estEmb: true,
    embNote: 'vehicle manufacturing spread over ~1 M km and all passengers',
    split: 'fuel' },
  { id: 'metro', cat: 'transport', label: 'Metro / local train', unit: 'km',
    usePer: 0.028, srcUse: 'owid_travel',
    embPer: 0.004, srcEmb: 'lca_est', estEmb: true,
    embNote: 'rolling-stock manufacturing per passenger-km (excl. infrastructure)',
    split: 'electricity' },
  { id: 'train', cat: 'transport', label: 'Intercity train', unit: 'km',
    usePer: 0.035, srcUse: 'owid_travel',
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: 'rolling-stock manufacturing per passenger-km (excl. infrastructure)',
    split: 'fuel' },
  { id: 'flight_dom', cat: 'transport', label: 'Flight — domestic', unit: 'km',
    usePer: 0.246, srcUse: 'owid_travel',
    embPer: 0.002, srcEmb: 'lca_est', estEmb: true,
    embNote: 'aircraft manufacturing is small per passenger-km over ~25-year service',
    split: 'fuel' },
  { id: 'flight_int', cat: 'transport', label: 'Flight — long haul', unit: 'km',
    usePer: 0.148, srcUse: 'owid_travel',
    embPer: 0.002, srcEmb: 'lca_est', estEmb: true,
    embNote: 'aircraft manufacturing is small per passenger-km over ~25-year service',
    split: 'fuel' },
  { id: 'cycle', cat: 'transport', label: 'Bicycle', unit: 'km',
    usePer: 0, srcUse: 'owid_travel',
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈150 kg CO₂e to build a bicycle ÷ ~30,000 km lifetime',
    split: 'fuel' },
  { id: 'walk', cat: 'transport', label: 'Walking', unit: 'km',
    usePer: 0, srcUse: 'owid_travel', split: 'fuel' },

  /* ---------- Food & drink (production = embodied; cooking logged separately) ---------- */
  { id: 'meal_beef', cat: 'food', label: 'Meal with beef', unit: 'meals',
    embPer: 12.44, srcEmb: 'poore2018',
    embNote: '125 g beef (beef herd, global avg 99.5 kg CO₂e/kg incl. land use)',
    split: 'ruminant' },
  { id: 'meal_lamb', cat: 'food', label: 'Meal with lamb / mutton', unit: 'meals',
    embPer: 4.97, srcEmb: 'poore2018',
    embNote: '125 g lamb/mutton (39.7 kg CO₂e/kg)',
    split: 'ruminant' },
  { id: 'meal_pork', cat: 'food', label: 'Meal with pork', unit: 'meals',
    embPer: 1.54, srcEmb: 'poore2018',
    embNote: '125 g pig meat (12.3 kg CO₂e/kg)',
    split: 'pork' },
  { id: 'meal_chicken', cat: 'food', label: 'Meal with chicken', unit: 'meals',
    embPer: 1.23, srcEmb: 'poore2018',
    embNote: '125 g poultry (9.9 kg CO₂e/kg)',
    split: 'poultry' },
  { id: 'meal_fish', cat: 'food', label: 'Meal with fish (farmed)', unit: 'meals',
    embPer: 1.70, srcEmb: 'poore2018',
    embNote: '125 g farmed fish (13.6 kg CO₂e/kg)',
    split: 'poultry' },
  { id: 'meal_egg', cat: 'food', label: 'Egg dish (2 eggs)', unit: 'servings',
    embPer: 0.56, srcEmb: 'poore2018',
    embNote: '120 g eggs (4.7 kg CO₂e/kg)',
    split: 'poultry' },
  { id: 'meal_veg', cat: 'food', label: 'Vegetarian meal', unit: 'meals',
    embPer: 1.0, srcEmb: 'derived', estEmb: true,
    embNote: 'composite: grains + pulses + vegetables + some dairy (see SOURCES.md)',
    split: 'plant' },
  { id: 'meal_vegan', cat: 'food', label: 'Vegan meal', unit: 'meals',
    embPer: 0.7, srcEmb: 'derived', estEmb: true,
    embNote: 'composite: grains + pulses + vegetables (see SOURCES.md)',
    split: 'plant' },
  { id: 'rice', cat: 'food', label: 'Rice (1 serving)', unit: 'servings',
    embPer: 0.33, srcEmb: 'poore2018',
    embNote: '75 g dry rice (4.45 kg CO₂e/kg) — methane from flooded paddies',
    split: 'rice' },
  { id: 'milk', cat: 'food', label: 'Milk (1 glass, 250 ml)', unit: 'glasses',
    embPer: 0.79, srcEmb: 'poore2018',
    embNote: '250 ml dairy milk (3.15 kg CO₂e/kg)',
    split: 'dairy' },
  { id: 'cheese', cat: 'food', label: 'Cheese (30 g)', unit: 'servings',
    embPer: 0.72, srcEmb: 'poore2018',
    embNote: '30 g cheese (23.9 kg CO₂e/kg)',
    split: 'dairy' },
  { id: 'tofu', cat: 'food', label: 'Tofu (100 g)', unit: 'servings',
    embPer: 0.32, srcEmb: 'poore2018',
    embNote: '100 g tofu (3.16 kg CO₂e/kg)',
    split: 'plant' },
  { id: 'coffee', cat: 'food', label: 'Coffee (1 cup)', unit: 'cups',
    embPer: 0.34, srcEmb: 'poore2018',
    embNote: '12 g beans (28.5 kg CO₂e/kg), black — add milk separately',
    split: 'plant' },
  { id: 'tea', cat: 'food', label: 'Tea (1 cup)', unit: 'cups',
    embPer: 0.03, srcEmb: 'derived', estEmb: true,
    embNote: '2 g leaves — small; milk logged separately',
    split: 'plant' },
  { id: 'chocolate', cat: 'food', label: 'Dark chocolate (20 g)', unit: 'servings',
    embPer: 0.93, srcEmb: 'poore2018',
    embNote: '20 g dark chocolate (46.7 kg CO₂e/kg incl. land use)',
    split: 'plant' },

  /* ---------- Home appliances (operation = kWh × grid; embodied = mfg amortised) ---------- */
  { id: 'ac', cat: 'home', label: 'Air conditioner (1.5 kW)', unit: 'hours',
    useKwh: 1.50, srcUse: 'lca_est', estUse: true,
    embPer: 0.033, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈500 kg CO₂e to make ÷ 15,000 lifetime hours (excl. refrigerant leaks)',
    split: 'electricity' },
  { id: 'fan', cat: 'home', label: 'Ceiling fan', unit: 'hours',
    useKwh: 0.075, srcUse: 'lca_est', estUse: true,
    embPer: 0.001, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈35 kg CO₂e to make ÷ ~37,000 lifetime hours',
    split: 'electricity' },
  { id: 'heater', cat: 'home', label: 'Space heater', unit: 'hours',
    useKwh: 1.80, srcUse: 'lca_est', estUse: true,
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈50 kg CO₂e to make ÷ ~10,000 lifetime hours',
    split: 'electricity' },
  { id: 'fridge', cat: 'home', label: 'Refrigerator', unit: 'hours',
    useKwh: 0.06, srcUse: 'lca_est', estUse: true,
    embPer: 0.004, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈400 kg CO₂e to make ÷ 12 years always-on (~105,000 h)',
    split: 'electricity' },
  { id: 'tv', cat: 'home', label: 'Television (43″ LED)', unit: 'hours',
    useKwh: 0.10, srcUse: 'lca_est', estUse: true,
    embPer: 0.024, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈300 kg CO₂e to make ÷ ~12,500 viewing hours (7 yr)',
    split: 'electricity' },
  { id: 'desktop', cat: 'home', label: 'Desktop computer', unit: 'hours',
    useKwh: 0.15, srcUse: 'lca_est', estUse: true,
    embPer: 0.030, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈400 kg CO₂e (PC + monitor) ÷ ~13,000 hours (6 yr)',
    split: 'electricity' },
  { id: 'laptop', cat: 'home', label: 'Laptop / tablet', unit: 'hours',
    useKwh: 0.05, srcUse: 'lca_est', estUse: true,
    embPer: 0.020, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈200 kg CO₂e to make (manufacturer PCF) ÷ ~10,000 hours (5 yr)',
    split: 'electricity' },
  { id: 'lights', cat: 'home', label: 'Room lighting (4 LED bulbs)', unit: 'hours',
    useKwh: 0.04, srcUse: 'lca_est', estUse: true,
    embPer: 0.001, srcEmb: 'lca_est', estEmb: true,
    embNote: 'LED bulb manufacturing is small per lumen-hour',
    split: 'electricity' },
  { id: 'washer', cat: 'home', label: 'Washing machine', unit: 'loads',
    useKwh: 0.80, srcUse: 'lca_est', estUse: true,
    embPer: 0.16, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈350 kg CO₂e to make ÷ ~2,200 lifetime loads (10 yr)',
    split: 'electricity' },
  { id: 'iron', cat: 'home', label: 'Clothes iron', unit: 'hours',
    useKwh: 1.10, srcUse: 'lca_est', estUse: true,
    embPer: 0.020, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈20 kg CO₂e to make ÷ ~1,000 lifetime hours',
    split: 'electricity' },
  { id: 'microwave', cat: 'home', label: 'Microwave oven', unit: 'hours',
    useKwh: 1.20, srcUse: 'lca_est', estUse: true,
    embPer: 0.050, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈100 kg CO₂e to make ÷ ~2,000 lifetime hours',
    split: 'electricity' },
  { id: 'kettle', cat: 'home', label: 'Electric kettle', unit: 'boils',
    useKwh: 0.11, srcUse: 'lca_est', estUse: true,
    embPer: 0.008, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈15 kg CO₂e to make ÷ ~2,000 boils',
    split: 'electricity' },
  { id: 'phone', cat: 'home', label: 'Phone charging', unit: 'charges',
    useKwh: 0.015, srcUse: 'lca_est', estUse: true,
    embPer: 0.050, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈55 kg CO₂e to make a phone (manufacturer PCF) ÷ ~1,100 charges (3 yr)',
    split: 'electricity' },

  /* ---------- Cooking, water & heating ---------- */
  { id: 'lpg', cat: 'water', label: 'Gas stove cooking (propane/natural gas)', unit: 'hours',
    usePer: 0.50, srcUse: 'defra_fuel', estUse: true,
    embPer: 0.010, srcEmb: 'lca_est', estEmb: true,
    embNote: 'stove manufacturing amortised',
    split: 'lpg' },
  { id: 'gas_furnace', cat: 'water', label: 'Home heating — gas furnace', unit: 'hours',
    usePer: 3.2, srcUse: 'defra_fuel', estUse: true,
    embPer: 0.020, srcEmb: 'lca_est', estEmb: true,
    embNote: '60,000 BTU-input furnace ≈ 17.6 kWh × 0.18 kg CO₂e/kWh natural gas (DEFRA); log burner runtime, not thermostat-on time',
    split: 'lpg' },
  { id: 'geyser', cat: 'water', label: 'Electric water heater', unit: 'hours',
    useKwh: 2.0, srcUse: 'lca_est', estUse: true,
    embPer: 0.010, srcEmb: 'lca_est', estEmb: true,
    embNote: '≈100 kg CO₂e to make ÷ ~10,000 lifetime hours',
    split: 'electricity' },
  { id: 'shower_hot', cat: 'water', label: 'Hot shower (10 min)', unit: 'showers',
    useKwh: 0.5, srcUse: 'lca_est', estUse: true,
    embPer: 0.005, srcEmb: 'lca_est', estEmb: true,
    embNote: 'water-heater share per shower',
    split: 'electricity' },
  { id: 'shower_cold', cat: 'water', label: 'Cold shower', unit: 'showers',
    usePer: 0.005, srcUse: 'lca_est', estUse: true,
    embPer: 0.002, srcEmb: 'lca_est', estEmb: true,
    embNote: 'water pumping & treatment only',
    split: 'electricity' },

  /* ---------- Other ---------- */
  { id: 'stream', cat: 'other', label: 'Video streaming (network only)', unit: 'hours',
    usePer: 0.036, srcUse: 'iea_stream',
    embNote: 'data centres + network transmission; log your TV/laptop hours separately for the device',
    split: 'electricity' },
  { id: 'waste', cat: 'other', label: 'Mixed waste to landfill', unit: 'kg',
    usePer: 0.50, srcUse: 'defra_fuel', estUse: true,
    embNote: 'methane from decomposing organic waste in landfill',
    split: 'waste' },
  { id: 'shopping', cat: 'other', label: 'Online order delivered', unit: 'parcels',
    usePer: 0.50, srcUse: 'lca_est', estUse: true,
    embNote: 'last-mile delivery + packaging; the product itself is not included',
    split: 'fuel' },
];

/* National grid intensities, kg CO2 per kWh (Ember 2024/2025 data via Our
 * World in Data, rounded to 3 decimals). Canada and the US also have
 * provincial/state values below. */
const GRID_COUNTRIES = [
  { id: 'CA', label: 'Canada', value: 0.191 },
  { id: 'US', label: 'United States', value: 0.384 },
  { id: 'AFGHANISTAN', label: 'Afghanistan', value: 0.131 },
  { id: 'ALBANIA', label: 'Albania', value: 0.025 },
  { id: 'ALGERIA', label: 'Algeria', value: 0.633 },
  { id: 'ANGOLA', label: 'Angola', value: 0.185 },
  { id: 'ANTIGUA_AND_BARBUDA', label: 'Antigua and Barbuda', value: 0.595 },
  { id: 'ARGENTINA', label: 'Argentina', value: 0.346 },
  { id: 'ARMENIA', label: 'Armenia', value: 0.212 },
  { id: 'AUSTRALIA', label: 'Australia', value: 0.525 },
  { id: 'AUSTRIA', label: 'Austria', value: 0.117 },
  { id: 'AZERBAIJAN', label: 'Azerbaijan', value: 0.632 },
  { id: 'BAHAMAS', label: 'Bahamas', value: 0.653 },
  { id: 'BAHRAIN', label: 'Bahrain', value: 0.902 },
  { id: 'BANGLADESH', label: 'Bangladesh', value: 0.696 },
  { id: 'BARBADOS', label: 'Barbados', value: 0.595 },
  { id: 'BELARUS', label: 'Belarus', value: 0.309 },
  { id: 'BELGIUM', label: 'Belgium', value: 0.15 },
  { id: 'BELIZE', label: 'Belize', value: 0.17 },
  { id: 'BENIN', label: 'Benin', value: 0.584 },
  { id: 'BHUTAN', label: 'Bhutan', value: 0.024 },
  { id: 'BOLIVIA', label: 'Bolivia', value: 0.481 },
  { id: 'BOSNIA_AND_HERZEGOVINA', label: 'Bosnia and Herzegovina', value: 0.571 },
  { id: 'BOTSWANA', label: 'Botswana', value: 0.851 },
  { id: 'BRAZIL', label: 'Brazil', value: 0.11 },
  { id: 'BRUNEI', label: 'Brunei', value: 0.892 },
  { id: 'BULGARIA', label: 'Bulgaria', value: 0.276 },
  { id: 'BURKINA_FASO', label: 'Burkina Faso', value: 0.562 },
  { id: 'BURUNDI', label: 'Burundi', value: 0.184 },
  { id: 'CAMBODIA', label: 'Cambodia', value: 0.499 },
  { id: 'CAMEROON', label: 'Cameroon', value: 0.226 },
  { id: 'CAPE_VERDE', label: 'Cape Verde', value: 0.462 },
  { id: 'CHAD', label: 'Chad', value: 0.622 },
  { id: 'CHILE', label: 'Chile', value: 0.289 },
  { id: 'CHINA', label: 'China', value: 0.525 },
  { id: 'COLOMBIA', label: 'Colombia', value: 0.187 },
  { id: 'COMOROS', label: 'Comoros', value: 0.643 },
  { id: 'CONGO', label: 'Congo', value: 0.716 },
  { id: 'COSTA_RICA', label: 'Costa Rica', value: 0.024 },
  { id: 'COTE_DIVOIRE', label: "Cote d'Ivoire", value: 0.405 },
  { id: 'CROATIA', label: 'Croatia', value: 0.159 },
  { id: 'CUBA', label: 'Cuba', value: 0.643 },
  { id: 'CYPRUS', label: 'Cyprus', value: 0.489 },
  { id: 'CZECHIA', label: 'Czechia', value: 0.401 },
  { id: 'DEMOCRATIC_REPUBLIC_OF_CONGO', label: 'Democratic Republic of Congo', value: 0.028 },
  { id: 'DENMARK', label: 'Denmark', value: 0.114 },
  { id: 'DJIBOUTI', label: 'Djibouti', value: 0.45 },
  { id: 'DOMINICA', label: 'Dominica', value: 0.6 },
  { id: 'DOMINICAN_REPUBLIC', label: 'Dominican Republic', value: 0.537 },
  { id: 'EAST_TIMOR', label: 'East Timor', value: 0.667 },
  { id: 'ECUADOR', label: 'Ecuador', value: 0.159 },
  { id: 'EGYPT', label: 'Egypt', value: 0.563 },
  { id: 'EL_SALVADOR', label: 'El Salvador', value: 0.139 },
  { id: 'EQUATORIAL_GUINEA', label: 'Equatorial Guinea', value: 0.644 },
  { id: 'ERITREA', label: 'Eritrea', value: 0.578 },
  { id: 'ESTONIA', label: 'Estonia', value: 0.319 },
  { id: 'ESWATINI', label: 'Eswatini', value: 0.131 },
  { id: 'ETHIOPIA', label: 'Ethiopia', value: 0.023 },
  { id: 'FIJI', label: 'Fiji', value: 0.278 },
  { id: 'FINLAND', label: 'Finland', value: 0.057 },
  { id: 'FRANCE', label: 'France', value: 0.041 },
  { id: 'GABON', label: 'Gabon', value: 0.523 },
  { id: 'GAMBIA', label: 'Gambia', value: 0.667 },
  { id: 'GEORGIA', label: 'Georgia', value: 0.146 },
  { id: 'GERMANY', label: 'Germany', value: 0.33 },
  { id: 'GHANA', label: 'Ghana', value: 0.469 },
  { id: 'GREECE', label: 'Greece', value: 0.315 },
  { id: 'GREENLAND', label: 'Greenland', value: 0.15 },
  { id: 'GRENADA', label: 'Grenada', value: 0.667 },
  { id: 'GUATEMALA', label: 'Guatemala', value: 0.301 },
  { id: 'GUINEA', label: 'Guinea', value: 0.181 },
  { id: 'GUINEA_BISSAU', label: 'Guinea-Bissau', value: 0.625 },
  { id: 'GUYANA', label: 'Guyana', value: 0.645 },
  { id: 'HAITI', label: 'Haiti', value: 0.535 },
  { id: 'HONDURAS', label: 'Honduras', value: 0.322 },
  { id: 'HUNGARY', label: 'Hungary', value: 0.163 },
  { id: 'ICELAND', label: 'Iceland', value: 0.028 },
  { id: 'INDIA', label: 'India', value: 0.67 },
  { id: 'INDONESIA', label: 'Indonesia', value: 0.68 },
  { id: 'IRAN', label: 'Iran', value: 0.66 },
  { id: 'IRAQ', label: 'Iraq', value: 0.683 },
  { id: 'IRELAND', label: 'Ireland', value: 0.257 },
  { id: 'ISRAEL', label: 'Israel', value: 0.493 },
  { id: 'ITALY', label: 'Italy', value: 0.285 },
  { id: 'JAMAICA', label: 'Jamaica', value: 0.563 },
  { id: 'JAPAN', label: 'Japan', value: 0.477 },
  { id: 'JORDAN', label: 'Jordan', value: 0.53 },
  { id: 'KAZAKHSTAN', label: 'Kazakhstan', value: 0.805 },
  { id: 'KENYA', label: 'Kenya', value: 0.095 },
  { id: 'KIRIBATI', label: 'Kiribati', value: 0.5 },
  { id: 'KOSOVO', label: 'Kosovo', value: 0.901 },
  { id: 'KUWAIT', label: 'Kuwait', value: 0.635 },
  { id: 'KYRGYZSTAN', label: 'Kyrgyzstan', value: 0.153 },
  { id: 'LAOS', label: 'Laos', value: 0.232 },
  { id: 'LATVIA', label: 'Latvia', value: 0.139 },
  { id: 'LEBANON', label: 'Lebanon', value: 0.39 },
  { id: 'LESOTHO', label: 'Lesotho', value: 0.021 },
  { id: 'LIBERIA', label: 'Liberia', value: 0.316 },
  { id: 'LIBYA', label: 'Libya', value: 0.827 },
  { id: 'LITHUANIA', label: 'Lithuania', value: 0.138 },
  { id: 'LUXEMBOURG', label: 'Luxembourg', value: 0.123 },
  { id: 'MADAGASCAR', label: 'Madagascar', value: 0.432 },
  { id: 'MALAWI', label: 'Malawi', value: 0.055 },
  { id: 'MALAYSIA', label: 'Malaysia', value: 0.602 },
  { id: 'MALDIVES', label: 'Maldives', value: 0.612 },
  { id: 'MALI', label: 'Mali', value: 0.539 },
  { id: 'MALTA', label: 'Malta', value: 0.484 },
  { id: 'MAURITANIA', label: 'Mauritania', value: 0.512 },
  { id: 'MAURITIUS', label: 'Mauritius', value: 0.642 },
  { id: 'MEXICO', label: 'Mexico', value: 0.474 },
  { id: 'MOLDOVA', label: 'Moldova', value: 0.633 },
  { id: 'MONGOLIA', label: 'Mongolia', value: 0.816 },
  { id: 'MONTENEGRO', label: 'Montenegro', value: 0.264 },
  { id: 'MOROCCO', label: 'Morocco', value: 0.596 },
  { id: 'MOZAMBIQUE', label: 'Mozambique', value: 0.129 },
  { id: 'MYANMAR', label: 'Myanmar', value: 0.503 },
  { id: 'NAMIBIA', label: 'Namibia', value: 0.049 },
  { id: 'NEPAL', label: 'Nepal', value: 0.024 },
  { id: 'NETHERLANDS', label: 'Netherlands', value: 0.254 },
  { id: 'NEW_ZEALAND', label: 'New Zealand', value: 0.093 },
  { id: 'NICARAGUA', label: 'Nicaragua', value: 0.301 },
  { id: 'NIGER', label: 'Niger', value: 0.674 },
  { id: 'NIGERIA', label: 'Nigeria', value: 0.456 },
  { id: 'NORTH_KOREA', label: 'North Korea', value: 0.341 },
  { id: 'NORTH_MACEDONIA', label: 'North Macedonia', value: 0.441 },
  { id: 'NORWAY', label: 'Norway', value: 0.028 },
  { id: 'OMAN', label: 'Oman', value: 0.544 },
  { id: 'PAKISTAN', label: 'Pakistan', value: 0.347 },
  { id: 'PALESTINE', label: 'Palestine', value: 0.414 },
  { id: 'PANAMA', label: 'Panama', value: 0.221 },
  { id: 'PAPUA_NEW_GUINEA', label: 'Papua New Guinea', value: 0.514 },
  { id: 'PARAGUAY', label: 'Paraguay', value: 0.025 },
  { id: 'PERU', label: 'Peru', value: 0.238 },
  { id: 'PHILIPPINES', label: 'Philippines', value: 0.588 },
  { id: 'POLAND', label: 'Poland', value: 0.589 },
  { id: 'PORTUGAL', label: 'Portugal', value: 0.128 },
  { id: 'PUERTO_RICO', label: 'Puerto Rico', value: 0.655 },
  { id: 'QATAR', label: 'Qatar', value: 0.582 },
  { id: 'ROMANIA', label: 'Romania', value: 0.251 },
  { id: 'RUSSIA', label: 'Russia', value: 0.45 },
  { id: 'RWANDA', label: 'Rwanda', value: 0.354 },
  { id: 'SAMOA', label: 'Samoa', value: 0.375 },
  { id: 'SAUDI_ARABIA', label: 'Saudi Arabia', value: 0.692 },
  { id: 'SENEGAL', label: 'Senegal', value: 0.54 },
  { id: 'SERBIA', label: 'Serbia', value: 0.696 },
  { id: 'SEYCHELLES', label: 'Seychelles', value: 0.556 },
  { id: 'SIERRA_LEONE', label: 'Sierra Leone', value: 0.048 },
  { id: 'SINGAPORE', label: 'Singapore', value: 0.497 },
  { id: 'SLOVAKIA', label: 'Slovakia', value: 0.095 },
  { id: 'SLOVENIA', label: 'Slovenia', value: 0.183 },
  { id: 'SOLOMON_ISLANDS', label: 'Solomon Islands', value: 0.636 },
  { id: 'SOMALIA', label: 'Somalia', value: 0.512 },
  { id: 'SOUTH_AFRICA', label: 'South Africa', value: 0.699 },
  { id: 'SOUTH_KOREA', label: 'South Korea', value: 0.417 },
  { id: 'SOUTH_SUDAN', label: 'South Sudan', value: 0.643 },
  { id: 'SPAIN', label: 'Spain', value: 0.154 },
  { id: 'SRI_LANKA', label: 'Sri Lanka', value: 0.329 },
  { id: 'SUDAN', label: 'Sudan', value: 0.154 },
  { id: 'SURINAME', label: 'Suriname', value: 0.322 },
  { id: 'SWEDEN', label: 'Sweden', value: 0.035 },
  { id: 'SWITZERLAND', label: 'Switzerland', value: 0.039 },
  { id: 'SYRIA', label: 'Syria', value: 0.706 },
  { id: 'TAIWAN', label: 'Taiwan', value: 0.633 },
  { id: 'TAJIKISTAN', label: 'Tajikistan', value: 0.073 },
  { id: 'TANZANIA', label: 'Tanzania', value: 0.345 },
  { id: 'THAILAND', label: 'Thailand', value: 0.546 },
  { id: 'TOGO', label: 'Togo', value: 0.423 },
  { id: 'TONGA', label: 'Tonga', value: 0.571 },
  { id: 'TRINIDAD_AND_TOBAGO', label: 'Trinidad and Tobago', value: 0.682 },
  { id: 'TUNISIA', label: 'Tunisia', value: 0.56 },
  { id: 'TURKEY', label: 'Turkey', value: 0.475 },
  { id: 'TURKMENISTAN', label: 'Turkmenistan', value: 1.306 },
  { id: 'UGANDA', label: 'Uganda', value: 0.059 },
  { id: 'UKRAINE', label: 'Ukraine', value: 0.25 },
  { id: 'UNITED_ARAB_EMIRATES', label: 'United Arab Emirates', value: 0.468 },
  { id: 'UNITED_KINGDOM', label: 'United Kingdom', value: 0.217 },
  { id: 'URUGUAY', label: 'Uruguay', value: 0.08 },
  { id: 'UZBEKISTAN', label: 'Uzbekistan', value: 1.0 },
  { id: 'VENEZUELA', label: 'Venezuela', value: 0.086 },
  { id: 'VIETNAM', label: 'Vietnam', value: 0.461 },
  { id: 'YEMEN', label: 'Yemen', value: 0.592 },
  { id: 'ZAMBIA', label: 'Zambia', value: 0.12 },
  { id: 'ZIMBABWE', label: 'Zimbabwe', value: 0.384 },
  { id: 'OTHER', label: 'Other / not listed (world avg)', value: 0.47 },
];

/* Provincial / state grid intensities, kg CO2/kWh.
 * Canada: ECCC National Inventory Report (approximate, ~2022 data).
 * US: EPA eGRID (approximate, 2022 data).
 * '' (empty subdivision) means the national average is used. */
const GRID_SUBDIVISIONS = {
  CA: [
    { id: 'AB', label: 'Alberta', value: 0.54 },
    { id: 'BC', label: 'British Columbia', value: 0.014 },
    { id: 'MB', label: 'Manitoba', value: 0.002 },
    { id: 'NB', label: 'New Brunswick', value: 0.27 },
    { id: 'NL', label: 'Newfoundland and Labrador', value: 0.03 },
    { id: 'NS', label: 'Nova Scotia', value: 0.66 },
    { id: 'NT', label: 'Northwest Territories', value: 0.18 },
    { id: 'NU', label: 'Nunavut', value: 0.9 },
    { id: 'ON', label: 'Ontario', value: 0.03 },
    { id: 'PE', label: 'Prince Edward Island', value: 0.01 },
    { id: 'QC', label: 'Quebec', value: 0.002 },
    { id: 'SK', label: 'Saskatchewan', value: 0.69 },
    { id: 'YT', label: 'Yukon', value: 0.08 },
  ],
  US: [
    { id: 'AL', label: 'Alabama', value: 0.35 }, { id: 'AK', label: 'Alaska', value: 0.43 },
    { id: 'AZ', label: 'Arizona', value: 0.31 }, { id: 'AR', label: 'Arkansas', value: 0.47 },
    { id: 'CA', label: 'California', value: 0.22 }, { id: 'CO', label: 'Colorado', value: 0.55 },
    { id: 'CT', label: 'Connecticut', value: 0.24 }, { id: 'DE', label: 'Delaware', value: 0.53 },
    { id: 'DC', label: 'District of Columbia', value: 0.32 }, { id: 'FL', label: 'Florida', value: 0.39 },
    { id: 'GA', label: 'Georgia', value: 0.35 }, { id: 'HI', label: 'Hawaii', value: 0.68 },
    { id: 'ID', label: 'Idaho', value: 0.08 }, { id: 'IL', label: 'Illinois', value: 0.27 },
    { id: 'IN', label: 'Indiana', value: 0.71 }, { id: 'IA', label: 'Iowa', value: 0.34 },
    { id: 'KS', label: 'Kansas', value: 0.36 }, { id: 'KY', label: 'Kentucky', value: 0.78 },
    { id: 'LA', label: 'Louisiana', value: 0.38 }, { id: 'ME', label: 'Maine', value: 0.12 },
    { id: 'MD', label: 'Maryland', value: 0.28 }, { id: 'MA', label: 'Massachusetts', value: 0.32 },
    { id: 'MI', label: 'Michigan', value: 0.44 }, { id: 'MN', label: 'Minnesota', value: 0.33 },
    { id: 'MS', label: 'Mississippi', value: 0.42 }, { id: 'MO', label: 'Missouri', value: 0.73 },
    { id: 'MT', label: 'Montana', value: 0.41 }, { id: 'NE', label: 'Nebraska', value: 0.55 },
    { id: 'NV', label: 'Nevada', value: 0.33 }, { id: 'NH', label: 'New Hampshire', value: 0.11 },
    { id: 'NJ', label: 'New Jersey', value: 0.23 }, { id: 'NM', label: 'New Mexico', value: 0.48 },
    { id: 'NY', label: 'New York', value: 0.19 }, { id: 'NC', label: 'North Carolina', value: 0.31 },
    { id: 'ND', label: 'North Dakota', value: 0.66 }, { id: 'OH', label: 'Ohio', value: 0.53 },
    { id: 'OK', label: 'Oklahoma', value: 0.32 }, { id: 'OR', label: 'Oregon', value: 0.15 },
    { id: 'PA', label: 'Pennsylvania', value: 0.32 }, { id: 'RI', label: 'Rhode Island', value: 0.37 },
    { id: 'SC', label: 'South Carolina', value: 0.23 }, { id: 'SD', label: 'South Dakota', value: 0.17 },
    { id: 'TN', label: 'Tennessee', value: 0.27 }, { id: 'TX', label: 'Texas', value: 0.37 },
    { id: 'UT', label: 'Utah', value: 0.7 }, { id: 'VT', label: 'Vermont', value: 0.01 },
    { id: 'VA', label: 'Virginia', value: 0.28 }, { id: 'WA', label: 'Washington', value: 0.09 },
    { id: 'WV', label: 'West Virginia', value: 0.85 }, { id: 'WI', label: 'Wisconsin', value: 0.51 },
    { id: 'WY', label: 'Wyoming', value: 0.9 },
  ],
};


/* Daily benchmarks in kg CO2e per person per day. */
const BENCHMARKS = {
  sustainable: 5.5,   // ~2 t CO2e/yr — widely used Paris-aligned personal target
  worldAvg:    12.9,  // ~4.7 t fossil CO2 per capita (Global Carbon Budget) / 365
  naAvg:       38,    // ~14 t fossil CO2 per capita in Canada/US / 365
};

/* Comfortable-but-frugal daily baselines for the minimal-usage guide.
 * qty = suggested units/day; note = the habit that gets you there. */
const MINIMAL_BASELINES = {
  ac:        { qty: 4,    note: 'Run it at 26 °C for the hottest hours only; a fan covers the rest.' },
  heater:    { qty: 2,    note: 'Heat the room you are in, layer up, and switch off overnight.' },
  fan:       { qty: 10,   note: 'Fans are cheap to run — prefer them over AC whenever bearable.' },
  geyser:    { qty: 0.25, note: '15 minutes of heating covers one person’s shower.' },
  gas_furnace:{ qty: 6,   note: 'Set the thermostat to 20 °C when home, 17 °C at night; seal drafts.' },
  tv:        { qty: 2,    note: 'Switch off at the wall — standby still draws power.' },
  desktop:   { qty: 8,    note: 'Enable sleep mode; a laptop uses about a third of the power.' },
  lights:    { qty: 5,    note: 'Daylight first; switch rooms off as you leave them.' },
  iron:      { qty: 0.25, note: 'Iron clothes in one weekly batch instead of daily.' },
  microwave: { qty: 0.3,  note: 'Fine as-is — microwaving is usually the efficient choice.' },
  stream:    { qty: 2,    note: 'Stream over Wi-Fi at 720p on small screens; download repeats.' },
  shower_hot:{ qty: 1,    note: 'One hot shower a day; shorter and cooler both help.' },
};
